# @generated by tools/codegen -- do not edit

from remnawave._generated.enums import (
    CreateHostRequestAlpn as CreateHostRequestAlpn,
)
from remnawave._generated.enums import (
    CreateHostRequestFingerprint as CreateHostRequestFingerprint,
)
from remnawave._generated.enums import (
    HostSecurityLayer as HostSecurityLayer,
)
from remnawave._generated.enums import (
    OAuth2CallbackRequestProvider as OAuth2CallbackRequestProvider,
)
from remnawave._generated.enums import (
    SubscriptionControllerGetSubscriptionByClientType as SubscriptionControllerGetSubscriptionByClientType,
)
from remnawave._generated.enums import (
    TemplateTemplateType as TemplateTemplateType,
)
from remnawave._generated.enums import (
    UpdateUserRequestStatus as UpdateUserRequestStatus,
)
from remnawave._generated.enums import (
    UserStatus as UserStatus,
)
from remnawave._generated.enums import (
    UserTrafficLimitStrategy as UserTrafficLimitStrategy,
)
from remnawave._generated.models import (
    X25519 as X25519,
)
from remnawave._generated.models import (
    ApiToken as ApiToken,
)
from remnawave._generated.models import (
    BandwidthStats as BandwidthStats,
)
from remnawave._generated.models import (
    BandwidthStatsBandwidthLast30Day as BandwidthStatsBandwidthLast30Day,
)
from remnawave._generated.models import (
    BulkAllUpdateUsersRequest as BulkAllUpdateUsersRequest,
)
from remnawave._generated.models import (
    BulkDeleteHostsRequest as BulkDeleteHostsRequest,
)
from remnawave._generated.models import (
    BulkDeleteUsersByStatusRequest as BulkDeleteUsersByStatusRequest,
)
from remnawave._generated.models import (
    BulkUpdateUsersRequest as BulkUpdateUsersRequest,
)
from remnawave._generated.models import (
    BulkUpdateUsersSquadsRequest as BulkUpdateUsersSquadsRequest,
)
from remnawave._generated.models import (
    ConfigProfile as ConfigProfile,
)
from remnawave._generated.models import (
    ConfigProfileInbound as ConfigProfileInbound,
)
from remnawave._generated.models import (
    ConfigProfileNode as ConfigProfileNode,
)
from remnawave._generated.models import (
    ConfigProfiles as ConfigProfiles,
)
from remnawave._generated.models import (
    CreateApiTokenRequest as CreateApiTokenRequest,
)
from remnawave._generated.models import (
    CreateConfigProfileRequest as CreateConfigProfileRequest,
)
from remnawave._generated.models import (
    CreateHostRequest as CreateHostRequest,
)
from remnawave._generated.models import (
    CreateHostRequestInbound as CreateHostRequestInbound,
)
from remnawave._generated.models import (
    CreateInfraBillingHistoryRecordRequest as CreateInfraBillingHistoryRecordRequest,
)
from remnawave._generated.models import (
    CreateInfraBillingNodeRequest as CreateInfraBillingNodeRequest,
)
from remnawave._generated.models import (
    CreateInfraProviderRequest as CreateInfraProviderRequest,
)
from remnawave._generated.models import (
    CreateInternalSquadRequest as CreateInternalSquadRequest,
)
from remnawave._generated.models import (
    CreateNodeRequest as CreateNodeRequest,
)
from remnawave._generated.models import (
    CreateNodeRequestConfigProfile as CreateNodeRequestConfigProfile,
)
from remnawave._generated.models import (
    CreateUserHwidDeviceRequest as CreateUserHwidDeviceRequest,
)
from remnawave._generated.models import (
    CreateUserRequest as CreateUserRequest,
)
from remnawave._generated.models import (
    DeleteAllUserHwidDevicesRequest as DeleteAllUserHwidDevicesRequest,
)
from remnawave._generated.models import (
    DeleteUserHwidDeviceRequest as DeleteUserHwidDeviceRequest,
)
from remnawave._generated.models import (
    DeleteUsers as DeleteUsers,
)
from remnawave._generated.models import (
    Device as Device,
)
from remnawave._generated.models import (
    EncryptHappCryptoLink as EncryptHappCryptoLink,
)
from remnawave._generated.models import (
    EncryptHappCryptoLinkRequest as EncryptHappCryptoLinkRequest,
)
from remnawave._generated.models import (
    FindAllApiTokens as FindAllApiTokens,
)
from remnawave._generated.models import (
    FindAllApiTokensApiKey as FindAllApiTokensApiKey,
)
from remnawave._generated.models import (
    FindAllApiTokensDoc as FindAllApiTokensDoc,
)
from remnawave._generated.models import (
    Host as Host,
)
from remnawave._generated.models import (
    Host2 as Host2,
)
from remnawave._generated.models import (
    Host3 as Host3,
)
from remnawave._generated.models import (
    HostInbound as HostInbound,
)
from remnawave._generated.models import (
    HwidDevices as HwidDevices,
)
from remnawave._generated.models import (
    HwidDevicesStats as HwidDevicesStats,
)
from remnawave._generated.models import (
    HwidDevicesStatsByApp as HwidDevicesStatsByApp,
)
from remnawave._generated.models import (
    HwidDevicesStatsByPlatform as HwidDevicesStatsByPlatform,
)
from remnawave._generated.models import (
    HwidDevicesStatsStat as HwidDevicesStatsStat,
)
from remnawave._generated.models import (
    Inbounds as Inbounds,
)
from remnawave._generated.models import (
    InboundsInbound as InboundsInbound,
)
from remnawave._generated.models import (
    InfraBillingHistoryRecord as InfraBillingHistoryRecord,
)
from remnawave._generated.models import (
    InfraBillingHistoryRecordRecord as InfraBillingHistoryRecordRecord,
)
from remnawave._generated.models import (
    InfraBillingHistoryRecordRecordProvider as InfraBillingHistoryRecordRecordProvider,
)
from remnawave._generated.models import (
    InfraBillingNode as InfraBillingNode,
)
from remnawave._generated.models import (
    InfraBillingNodeBillingNode as InfraBillingNodeBillingNode,
)
from remnawave._generated.models import (
    InfraBillingNodeBillingNodeProvider as InfraBillingNodeBillingNodeProvider,
)
from remnawave._generated.models import (
    InfraBillingNodeStat as InfraBillingNodeStat,
)
from remnawave._generated.models import (
    InfraProvider as InfraProvider,
)
from remnawave._generated.models import (
    InfraProviderBillingHistory as InfraProviderBillingHistory,
)
from remnawave._generated.models import (
    InfraProviderBillingNode as InfraProviderBillingNode,
)
from remnawave._generated.models import (
    InfraProviders as InfraProviders,
)
from remnawave._generated.models import (
    InternalSquad as InternalSquad,
)
from remnawave._generated.models import (
    InternalSquadAccessibleNodes as InternalSquadAccessibleNodes,
)
from remnawave._generated.models import (
    InternalSquadAccessibleNodesAccessibleNode as InternalSquadAccessibleNodesAccessibleNode,
)
from remnawave._generated.models import (
    InternalSquadInfo as InternalSquadInfo,
)
from remnawave._generated.models import (
    InternalSquads as InternalSquads,
)
from remnawave._generated.models import (
    Login as Login,
)
from remnawave._generated.models import (
    LoginRequest as LoginRequest,
)
from remnawave._generated.models import (
    Node as Node,
)
from remnawave._generated.models import (
    Node2 as Node2,
)
from remnawave._generated.models import (
    NodeConfigProfile as NodeConfigProfile,
)
from remnawave._generated.models import (
    NodeProvider as NodeProvider,
)
from remnawave._generated.models import (
    NodesMetrics as NodesMetrics,
)
from remnawave._generated.models import (
    NodesMetricsNode as NodesMetricsNode,
)
from remnawave._generated.models import (
    NodesMetricsNodeInboundsStat as NodesMetricsNodeInboundsStat,
)
from remnawave._generated.models import (
    NodesRealtimeUsage as NodesRealtimeUsage,
)
from remnawave._generated.models import (
    NodesStatistics as NodesStatistics,
)
from remnawave._generated.models import (
    NodesStatisticsLastSevenDay as NodesStatisticsLastSevenDay,
)
from remnawave._generated.models import (
    NodesUsageByRange as NodesUsageByRange,
)
from remnawave._generated.models import (
    NodeUserUsageByRange as NodeUserUsageByRange,
)
from remnawave._generated.models import (
    OAuth2Authorize as OAuth2Authorize,
)
from remnawave._generated.models import (
    OAuth2AuthorizeRequest as OAuth2AuthorizeRequest,
)
from remnawave._generated.models import (
    OAuth2CallbackRequest as OAuth2CallbackRequest,
)
from remnawave._generated.models import (
    PubKey as PubKey,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuid as RawSubscriptionByShortUuid,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidConvertedUserInfo as RawSubscriptionByShortUuidConvertedUserInfo,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHost as RawSubscriptionByShortUuidRawHost,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHostAdditionalParam as RawSubscriptionByShortUuidRawHostAdditionalParam,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHostDbData as RawSubscriptionByShortUuidRawHostDbData,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHostPassword as RawSubscriptionByShortUuidRawHostPassword,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHostProtocolOption as RawSubscriptionByShortUuidRawHostProtocolOption,
)
from remnawave._generated.models import (
    RawSubscriptionByShortUuidRawHostProtocolOptionSs as RawSubscriptionByShortUuidRawHostProtocolOptionSs,
)
from remnawave._generated.models import (
    RemnawaveHealth as RemnawaveHealth,
)
from remnawave._generated.models import (
    RemnawaveHealthPm2Stat as RemnawaveHealthPm2Stat,
)
from remnawave._generated.models import (
    ReorderHostRequest as ReorderHostRequest,
)
from remnawave._generated.models import (
    ReorderHostRequestHost as ReorderHostRequestHost,
)
from remnawave._generated.models import (
    ReorderNodeRequest as ReorderNodeRequest,
)
from remnawave._generated.models import (
    RestartAllNodesRequestBody as RestartAllNodesRequestBody,
)
from remnawave._generated.models import (
    RevokeUserSubscriptionBody as RevokeUserSubscriptionBody,
)
from remnawave._generated.models import (
    SetInboundToManyHostsRequest as SetInboundToManyHostsRequest,
)
from remnawave._generated.models import (
    SetPortToManyHostsRequest as SetPortToManyHostsRequest,
)
from remnawave._generated.models import (
    Stats as Stats,
)
from remnawave._generated.models import (
    StatsCpu as StatsCpu,
)
from remnawave._generated.models import (
    StatsMemory as StatsMemory,
)
from remnawave._generated.models import (
    StatsNode as StatsNode,
)
from remnawave._generated.models import (
    StatsOnlineStat as StatsOnlineStat,
)
from remnawave._generated.models import (
    StatsUser as StatsUser,
)
from remnawave._generated.models import (
    Status as Status,
)
from remnawave._generated.models import (
    StatusBranding as StatusBranding,
)
from remnawave._generated.models import (
    StatusOauth2 as StatusOauth2,
)
from remnawave._generated.models import (
    StatusTgAuth as StatusTgAuth,
)
from remnawave._generated.models import (
    Subscription as Subscription,
)
from remnawave._generated.models import (
    SubscriptionInfo as SubscriptionInfo,
)
from remnawave._generated.models import (
    SubscriptionInfoUser as SubscriptionInfoUser,
)
from remnawave._generated.models import (
    SubscriptionRequestHistoryStats as SubscriptionRequestHistoryStats,
)
from remnawave._generated.models import (
    SubscriptionRequestHistoryStatsHourlyRequestStat as SubscriptionRequestHistoryStatsHourlyRequestStat,
)
from remnawave._generated.models import (
    SubscriptionRequestsPage as SubscriptionRequestsPage,
)
from remnawave._generated.models import (
    SubscriptionSettings as SubscriptionSettings,
)
from remnawave._generated.models import (
    SubscriptionsPage as SubscriptionsPage,
)
from remnawave._generated.models import (
    SubscriptionUser as SubscriptionUser,
)
from remnawave._generated.models import (
    Tags as Tags,
)
from remnawave._generated.models import (
    TelegramCallbackRequest as TelegramCallbackRequest,
)
from remnawave._generated.models import (
    Template as Template,
)
from remnawave._generated.models import (
    TorrentBlockerReport as TorrentBlockerReport,
)
from remnawave._generated.models import (
    UpdateConfigProfileRequest as UpdateConfigProfileRequest,
)
from remnawave._generated.models import (
    UpdateHostRequest as UpdateHostRequest,
)
from remnawave._generated.models import (
    UpdateInfraBillingNodeRequest as UpdateInfraBillingNodeRequest,
)
from remnawave._generated.models import (
    UpdateInfraProviderRequest as UpdateInfraProviderRequest,
)
from remnawave._generated.models import (
    UpdateInternalSquadRequest as UpdateInternalSquadRequest,
)
from remnawave._generated.models import (
    UpdateNodeRequest as UpdateNodeRequest,
)
from remnawave._generated.models import (
    UpdateSubscriptionSettingsRequest as UpdateSubscriptionSettingsRequest,
)
from remnawave._generated.models import (
    UpdateTemplateRequest as UpdateTemplateRequest,
)
from remnawave._generated.models import (
    UpdateUserRequest as UpdateUserRequest,
)
from remnawave._generated.models import (
    User as User,
)
from remnawave._generated.models import (
    UserAccessibleNodes as UserAccessibleNodes,
)
from remnawave._generated.models import (
    UserAccessibleNodesActiveNode as UserAccessibleNodesActiveNode,
)
from remnawave._generated.models import (
    UserAccessibleNodesActiveNodeActiveSquad as UserAccessibleNodesActiveNodeActiveSquad,
)
from remnawave._generated.models import (
    UserActiveInternalSquad as UserActiveInternalSquad,
)
from remnawave._generated.models import (
    UserHapp as UserHapp,
)
from remnawave._generated.models import (
    UserHwidDevice as UserHwidDevice,
)
from remnawave._generated.models import (
    UserLastConnectedNode as UserLastConnectedNode,
)
from remnawave._generated.models import (
    UsersPage as UsersPage,
)
from remnawave._generated.models import (
    UserSubscriptionRequestHistory as UserSubscriptionRequestHistory,
)
from remnawave._generated.models import (
    UserSubscriptionRequestHistoryRecord as UserSubscriptionRequestHistoryRecord,
)
from remnawave._generated.models import (
    UserUsageByRange as UserUsageByRange,
)
from remnawave._generated.models import (
    X25519Keypair as X25519Keypair,
)
