# @generated by tools/codegen -- do not edit
"""API Tokens Management."""

from remnawave._generated.models import (
    ApiToken,
    CreateApiTokenRequest,
    FindAllApiTokens,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

CREATE: Operation[ApiToken] = Operation(
    "POST",
    "/api/tokens",
    ApiToken,
)
FIND_ALL: Operation[FindAllApiTokens] = Operation(
    "GET",
    "/api/tokens",
    FindAllApiTokens,
)
DELETE: Operation[bool] = Operation(
    "DELETE",
    "/api/tokens/{uuid}",
    bool,
)


class ApiTokensManagementApi(SyncGroup):
    def create(self, body: CreateApiTokenRequest) -> ApiToken:
        """Create a new API token."""
        return self._executor.execute(CREATE, body=body)

    def find_all(self) -> FindAllApiTokens:
        """Get all API tokens."""
        return self._executor.execute(FIND_ALL)

    def delete(self, uuid: str) -> bool:
        """Delete an API token by UUID."""
        return self._executor.execute(DELETE, path={"uuid": uuid})


class AsyncApiTokensManagementApi(AsyncGroup):
    async def create(self, body: CreateApiTokenRequest) -> ApiToken:
        """Create a new API token."""
        return await self._executor.execute(CREATE, body=body)

    async def find_all(self) -> FindAllApiTokens:
        """Get all API tokens."""
        return await self._executor.execute(FIND_ALL)

    async def delete(self, uuid: str) -> bool:
        """Delete an API token by UUID."""
        return await self._executor.execute(DELETE, path={"uuid": uuid})
