# @generated by tools/codegen -- do not edit
"""Auth Controller."""

from remnawave._generated.models import (
    Login,
    LoginRequest,
    OAuth2Authorize,
    OAuth2AuthorizeRequest,
    OAuth2CallbackRequest,
    Status,
    TelegramCallbackRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

LOGIN: Operation[Login] = Operation(
    "POST",
    "/api/auth/login",
    Login,
)
REGISTER: Operation[Login] = Operation(
    "POST",
    "/api/auth/register",
    Login,
)
GET_STATUS: Operation[Status] = Operation(
    "GET",
    "/api/auth/status",
    Status,
)
TELEGRAM_CALLBACK: Operation[Login] = Operation(
    "POST",
    "/api/auth/oauth2/tg/callback",
    Login,
)
OAUTH2_AUTHORIZE: Operation[OAuth2Authorize] = Operation(
    "POST",
    "/api/auth/oauth2/authorize",
    OAuth2Authorize,
)
OAUTH2_CALLBACK: Operation[Login] = Operation(
    "POST",
    "/api/auth/oauth2/callback",
    Login,
)


class AuthApi(SyncGroup):
    def login(self, body: LoginRequest) -> Login:
        """Login as superadmin."""
        return self._executor.execute(LOGIN, body=body)

    def register(self, body: LoginRequest) -> Login:
        """Register as superadmin."""
        return self._executor.execute(REGISTER, body=body)

    def get_status(self) -> Status:
        """Get the status of the authentication."""
        return self._executor.execute(GET_STATUS)

    def telegram_callback(self, body: TelegramCallbackRequest) -> Login:
        """Callback from Telegram OAuth2."""
        return self._executor.execute(TELEGRAM_CALLBACK, body=body)

    def oauth2_authorize(self, body: OAuth2AuthorizeRequest) -> OAuth2Authorize:
        """Initiate OAuth2 authorization."""
        return self._executor.execute(OAUTH2_AUTHORIZE, body=body)

    def oauth2_callback(self, body: OAuth2CallbackRequest) -> Login:
        """Callback from OAuth2."""
        return self._executor.execute(OAUTH2_CALLBACK, body=body)


class AsyncAuthApi(AsyncGroup):
    async def login(self, body: LoginRequest) -> Login:
        """Login as superadmin."""
        return await self._executor.execute(LOGIN, body=body)

    async def register(self, body: LoginRequest) -> Login:
        """Register as superadmin."""
        return await self._executor.execute(REGISTER, body=body)

    async def get_status(self) -> Status:
        """Get the status of the authentication."""
        return await self._executor.execute(GET_STATUS)

    async def telegram_callback(self, body: TelegramCallbackRequest) -> Login:
        """Callback from Telegram OAuth2."""
        return await self._executor.execute(TELEGRAM_CALLBACK, body=body)

    async def oauth2_authorize(
        self, body: OAuth2AuthorizeRequest
    ) -> OAuth2Authorize:
        """Initiate OAuth2 authorization."""
        return await self._executor.execute(OAUTH2_AUTHORIZE, body=body)

    async def oauth2_callback(self, body: OAuth2CallbackRequest) -> Login:
        """Callback from OAuth2."""
        return await self._executor.execute(OAUTH2_CALLBACK, body=body)
