# @generated by tools/codegen -- do not edit
"""Bandwidth stats."""

from datetime import datetime

from remnawave._generated.models import (
    NodesRealtimeUsage,
    NodesUsageByRange,
    NodeUserUsageByRange,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_NODE_USER_USAGE: Operation[list[NodeUserUsageByRange]] = Operation(
    "GET",
    "/api/nodes/usage/{uuid}/users/range",
    list[NodeUserUsageByRange],
)
GET_NODES_REALTIME_USAGE: Operation[list[NodesRealtimeUsage]] = Operation(
    "GET",
    "/api/nodes/usage/realtime",
    list[NodesRealtimeUsage],
)
GET_NODES_USAGE_BY_RANGE: Operation[list[NodesUsageByRange]] = Operation(
    "GET",
    "/api/nodes/usage/range",
    list[NodesUsageByRange],
)


class BandwidthStatsApi(SyncGroup):
    def get_node_user_usage(
        self, uuid: str, start: datetime, end: datetime
    ) -> list[NodeUserUsageByRange]:
        """Get node user usage by range and Node UUID."""
        return self._executor.execute(
            GET_NODE_USER_USAGE,
            path={"uuid": uuid},
            query={"start": start, "end": end},
        )

    def get_nodes_realtime_usage(self) -> list[NodesRealtimeUsage]:
        """Get nodes realtime usage."""
        return self._executor.execute(GET_NODES_REALTIME_USAGE)

    def get_nodes_usage_by_range(
        self, start: datetime, end: datetime
    ) -> list[NodesUsageByRange]:
        """Get nodes usage by range."""
        return self._executor.execute(
            GET_NODES_USAGE_BY_RANGE, query={"start": start, "end": end}
        )


class AsyncBandwidthStatsApi(AsyncGroup):
    async def get_node_user_usage(
        self, uuid: str, start: datetime, end: datetime
    ) -> list[NodeUserUsageByRange]:
        """Get node user usage by range and Node UUID."""
        return await self._executor.execute(
            GET_NODE_USER_USAGE,
            path={"uuid": uuid},
            query={"start": start, "end": end},
        )

    async def get_nodes_realtime_usage(self) -> list[NodesRealtimeUsage]:
        """Get nodes realtime usage."""
        return await self._executor.execute(GET_NODES_REALTIME_USAGE)

    async def get_nodes_usage_by_range(
        self, start: datetime, end: datetime
    ) -> list[NodesUsageByRange]:
        """Get nodes usage by range."""
        return await self._executor.execute(
            GET_NODES_USAGE_BY_RANGE, query={"start": start, "end": end}
        )
