# @generated by tools/codegen -- do not edit
"""Bandwidth Stats Controller."""

from datetime import date
from uuid import UUID

from remnawave._generated.models import (
    GetNodeUsageBody,
    InternalSquadUsage,
    InternalSquadUserUsage,
    NodeUsage,
    StatsNodeUsersUsage,
    StatsUserUsage,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_INTERNAL_SQUAD_USAGE: Operation[InternalSquadUsage] = Operation(
    "GET",
    "/api/bandwidth-stats/internal-squads/{uuid}/usage",
    InternalSquadUsage,
)
GET_INTERNAL_SQUAD_USER_USAGE: Operation[InternalSquadUserUsage] = Operation(
    "GET",
    "/api/bandwidth-stats/internal-squads/{squadUuid}/users/{userId}/usage",
    InternalSquadUserUsage,
)
GET_NODE_USAGE: Operation[NodeUsage] = Operation(
    "POST",
    "/api/bandwidth-stats/nodes/usage",
    NodeUsage,
)
GET_STATS_NODE_USERS_USAGE: Operation[StatsNodeUsersUsage] = Operation(
    "GET",
    "/api/bandwidth-stats/nodes/{uuid}/users",
    StatsNodeUsersUsage,
)
GET_STATS_NODES_USERS_USAGE: Operation[StatsNodeUsersUsage] = Operation(
    "POST",
    "/api/bandwidth-stats/nodes/users",
    StatsNodeUsersUsage,
)
GET_STATS_NODES_USAGE: Operation[StatsUserUsage] = Operation(
    "GET",
    "/api/bandwidth-stats/users/{userId}",
    StatsUserUsage,
)
GET_NODES_USAGE: Operation[StatsUserUsage] = Operation(
    "GET",
    "/api/bandwidth-stats/nodes",
    StatsUserUsage,
)


class BandwidthStatsApi(SyncGroup):
    def get_internal_squad_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        min_total_bytes: int | None = None,
        limit: int | None = None,
        cursor: int | None = None,
    ) -> InternalSquadUsage:
        """Get internal squad users traffic usage for a period."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
                "limit": limit,
                "cursor": cursor,
            },
        )

    def get_internal_squad_user_usage(
        self, squad_uuid: UUID, user_id: int, start: date, end: date
    ) -> InternalSquadUserUsage:
        """
        Get a single user daily traffic usage on the internal squad
        nodes for a period.
        """
        return self._executor.execute(
            GET_INTERNAL_SQUAD_USER_USAGE,
            path={"squadUuid": squad_uuid, "userId": user_id},
            query={"start": start, "end": end},
        )

    def get_node_usage(
        self,
        start: date,
        end: date,
        body: GetNodeUsageBody,
        *,
        min_total_bytes: int | None = None,
    ) -> NodeUsage:
        """
        Get users exceeding a traffic threshold on the given nodes for a
        period.
        """
        return self._executor.execute(
            GET_NODE_USAGE,
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
            },
            body=body,
        )

    def get_stats_node_users_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        top_users_limit: int | None = None,
    ) -> StatsNodeUsersUsage:
        """Get Node Users Usage by Node UUID."""
        return self._executor.execute(
            GET_STATS_NODE_USERS_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "topUsersLimit": top_users_limit,
            },
        )

    def get_stats_nodes_users_usage(
        self,
        start: date,
        end: date,
        body: GetNodeUsageBody,
        *,
        top_users_limit: int | None = None,
    ) -> StatsNodeUsersUsage:
        """Get Nodes Users Usage by Nodes UUIDs."""
        return self._executor.execute(
            GET_STATS_NODES_USERS_USAGE,
            query={
                "start": start,
                "end": end,
                "topUsersLimit": top_users_limit,
            },
            body=body,
        )

    def get_stats_nodes_usage(
        self,
        user_id: int,
        start: date,
        end: date,
        *,
        top_nodes_limit: int | None = None,
    ) -> StatsUserUsage:
        """Get User Usage by Range."""
        return self._executor.execute(
            GET_STATS_NODES_USAGE,
            path={"userId": user_id},
            query={
                "start": start,
                "end": end,
                "topNodesLimit": top_nodes_limit,
            },
        )

    def get_nodes_usage(
        self, start: date, end: date, *, top_nodes_limit: int | None = None
    ) -> StatsUserUsage:
        """Get Nodes Usage by Range."""
        return self._executor.execute(
            GET_NODES_USAGE,
            query={
                "start": start,
                "end": end,
                "topNodesLimit": top_nodes_limit,
            },
        )


class AsyncBandwidthStatsApi(AsyncGroup):
    async def get_internal_squad_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        min_total_bytes: int | None = None,
        limit: int | None = None,
        cursor: int | None = None,
    ) -> InternalSquadUsage:
        """Get internal squad users traffic usage for a period."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
                "limit": limit,
                "cursor": cursor,
            },
        )

    async def get_internal_squad_user_usage(
        self, squad_uuid: UUID, user_id: int, start: date, end: date
    ) -> InternalSquadUserUsage:
        """
        Get a single user daily traffic usage on the internal squad
        nodes for a period.
        """
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_USER_USAGE,
            path={"squadUuid": squad_uuid, "userId": user_id},
            query={"start": start, "end": end},
        )

    async def get_node_usage(
        self,
        start: date,
        end: date,
        body: GetNodeUsageBody,
        *,
        min_total_bytes: int | None = None,
    ) -> NodeUsage:
        """
        Get users exceeding a traffic threshold on the given nodes for a
        period.
        """
        return await self._executor.execute(
            GET_NODE_USAGE,
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
            },
            body=body,
        )

    async def get_stats_node_users_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        top_users_limit: int | None = None,
    ) -> StatsNodeUsersUsage:
        """Get Node Users Usage by Node UUID."""
        return await self._executor.execute(
            GET_STATS_NODE_USERS_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "topUsersLimit": top_users_limit,
            },
        )

    async def get_stats_nodes_users_usage(
        self,
        start: date,
        end: date,
        body: GetNodeUsageBody,
        *,
        top_users_limit: int | None = None,
    ) -> StatsNodeUsersUsage:
        """Get Nodes Users Usage by Nodes UUIDs."""
        return await self._executor.execute(
            GET_STATS_NODES_USERS_USAGE,
            query={
                "start": start,
                "end": end,
                "topUsersLimit": top_users_limit,
            },
            body=body,
        )

    async def get_stats_nodes_usage(
        self,
        user_id: int,
        start: date,
        end: date,
        *,
        top_nodes_limit: int | None = None,
    ) -> StatsUserUsage:
        """Get User Usage by Range."""
        return await self._executor.execute(
            GET_STATS_NODES_USAGE,
            path={"userId": user_id},
            query={
                "start": start,
                "end": end,
                "topNodesLimit": top_nodes_limit,
            },
        )

    async def get_nodes_usage(
        self, start: date, end: date, *, top_nodes_limit: int | None = None
    ) -> StatsUserUsage:
        """Get Nodes Usage by Range."""
        return await self._executor.execute(
            GET_NODES_USAGE,
            query={
                "start": start,
                "end": end,
                "topNodesLimit": top_nodes_limit,
            },
        )
