# @generated by tools/codegen -- do not edit
"""Config Profiles Controller."""

from uuid import UUID

from remnawave._generated.models import (
    ConfigProfile,
    ConfigProfiles,
    CreateConfigProfileBody,
    Inbounds,
    ReorderNodePluginsBody,
    UpdateConfigProfileBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_CONFIG_PROFILES: Operation[ConfigProfiles] = Operation(
    "GET",
    "/api/config-profiles",
    ConfigProfiles,
)
CREATE_CONFIG_PROFILE: Operation[ConfigProfile] = Operation(
    "POST",
    "/api/config-profiles",
    ConfigProfile,
)
UPDATE_CONFIG_PROFILE: Operation[ConfigProfile] = Operation(
    "PATCH",
    "/api/config-profiles",
    ConfigProfile,
)
GET_ALL_INBOUNDS: Operation[Inbounds] = Operation(
    "GET",
    "/api/config-profiles/inbounds",
    Inbounds,
)
GET_INBOUNDS_BY_PROFILE_UUID: Operation[Inbounds] = Operation(
    "GET",
    "/api/config-profiles/{uuid}/inbounds",
    Inbounds,
)
GET_CONFIG_PROFILE_BY_UUID: Operation[ConfigProfile] = Operation(
    "GET",
    "/api/config-profiles/{uuid}",
    ConfigProfile,
)
DELETE_CONFIG_PROFILE_BY_UUID = NoContentOperation(
    "DELETE", "/api/config-profiles/{uuid}"
)
GET_COMPUTED_CONFIG_PROFILE_BY_UUID: Operation[ConfigProfile] = Operation(
    "GET",
    "/api/config-profiles/{uuid}/computed-config",
    ConfigProfile,
)
REORDER_CONFIG_PROFILES: Operation[ConfigProfiles] = Operation(
    "POST",
    "/api/config-profiles/actions/reorder",
    ConfigProfiles,
)


class ConfigProfilesApi(SyncGroup):
    def get_config_profiles(self) -> ConfigProfiles:
        """Get config profiles."""
        return self._executor.execute(GET_CONFIG_PROFILES)

    def create_config_profile(
        self, body: CreateConfigProfileBody
    ) -> ConfigProfile:
        """Create config profile."""
        return self._executor.execute(CREATE_CONFIG_PROFILE, body=body)

    def update_config_profile(
        self, body: UpdateConfigProfileBody
    ) -> ConfigProfile:
        """Update Core Config in specific config profile."""
        return self._executor.execute(UPDATE_CONFIG_PROFILE, body=body)

    def get_all_inbounds(self) -> Inbounds:
        """Get all inbounds from all config profiles."""
        return self._executor.execute(GET_ALL_INBOUNDS)

    def get_inbounds_by_profile_uuid(self, uuid: UUID) -> Inbounds:
        """Get inbounds by profile uuid."""
        return self._executor.execute(
            GET_INBOUNDS_BY_PROFILE_UUID, path={"uuid": uuid}
        )

    def get_config_profile_by_uuid(self, uuid: UUID) -> ConfigProfile:
        """Get config profile by uuid."""
        return self._executor.execute(
            GET_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    def delete_config_profile_by_uuid(self, uuid: UUID) -> None:
        """Delete config profile."""
        return self._executor.execute(
            DELETE_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    def get_computed_config_profile_by_uuid(self, uuid: UUID) -> ConfigProfile:
        """Get computed config profile by uuid."""
        return self._executor.execute(
            GET_COMPUTED_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    def reorder_config_profiles(
        self, body: ReorderNodePluginsBody
    ) -> ConfigProfiles:
        """Reorder config profiles."""
        return self._executor.execute(REORDER_CONFIG_PROFILES, body=body)


class AsyncConfigProfilesApi(AsyncGroup):
    async def get_config_profiles(self) -> ConfigProfiles:
        """Get config profiles."""
        return await self._executor.execute(GET_CONFIG_PROFILES)

    async def create_config_profile(
        self, body: CreateConfigProfileBody
    ) -> ConfigProfile:
        """Create config profile."""
        return await self._executor.execute(CREATE_CONFIG_PROFILE, body=body)

    async def update_config_profile(
        self, body: UpdateConfigProfileBody
    ) -> ConfigProfile:
        """Update Core Config in specific config profile."""
        return await self._executor.execute(UPDATE_CONFIG_PROFILE, body=body)

    async def get_all_inbounds(self) -> Inbounds:
        """Get all inbounds from all config profiles."""
        return await self._executor.execute(GET_ALL_INBOUNDS)

    async def get_inbounds_by_profile_uuid(self, uuid: UUID) -> Inbounds:
        """Get inbounds by profile uuid."""
        return await self._executor.execute(
            GET_INBOUNDS_BY_PROFILE_UUID, path={"uuid": uuid}
        )

    async def get_config_profile_by_uuid(self, uuid: UUID) -> ConfigProfile:
        """Get config profile by uuid."""
        return await self._executor.execute(
            GET_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    async def delete_config_profile_by_uuid(self, uuid: UUID) -> None:
        """Delete config profile."""
        return await self._executor.execute(
            DELETE_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    async def get_computed_config_profile_by_uuid(
        self, uuid: UUID
    ) -> ConfigProfile:
        """Get computed config profile by uuid."""
        return await self._executor.execute(
            GET_COMPUTED_CONFIG_PROFILE_BY_UUID, path={"uuid": uuid}
        )

    async def reorder_config_profiles(
        self, body: ReorderNodePluginsBody
    ) -> ConfigProfiles:
        """Reorder config profiles."""
        return await self._executor.execute(REORDER_CONFIG_PROFILES, body=body)
