# @generated by tools/codegen -- do not edit
"""Connections Controller."""

from uuid import UUID

from remnawave._generated.models import (
    ConnectionsByNodeResult,
    ConnectionsByNodeResultResult,
    ConnectionsByUserResult,
    ConnectionsByUserResultResult,
    DropConnectionsBody,
    GeocheckByNodeBody,
    GeocheckByNodeResult,
    GeocheckByNodeResultResult,
    JobRef,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

CONNECTIONS_BY_USER: Operation[JobRef] = Operation(
    "POST",
    "/api/connections/by-user/{userId}",
    JobRef,
)
CONNECTIONS_BY_USER_RESULT: Operation[ConnectionsByUserResult] = Operation(
    "GET",
    "/api/connections/by-user/{jobId}",
    ConnectionsByUserResult,
)
DROP_CONNECTIONS = NoContentOperation("POST", "/api/connections/drop")
CONNECTIONS_BY_NODE: Operation[JobRef] = Operation(
    "POST",
    "/api/connections/by-node/{nodeUuid}",
    JobRef,
)
CONNECTIONS_BY_NODE_RESULT: Operation[ConnectionsByNodeResult] = Operation(
    "GET",
    "/api/connections/by-node/{jobId}",
    ConnectionsByNodeResult,
)
GEOCHECK_BY_NODE: Operation[JobRef] = Operation(
    "POST",
    "/api/connections/geocheck/{nodeUuid}",
    JobRef,
)
GEOCHECK_BY_NODE_RESULT: Operation[GeocheckByNodeResult] = Operation(
    "GET",
    "/api/connections/geocheck/{jobId}",
    GeocheckByNodeResult,
)


class ConnectionsApi(SyncGroup):
    def connections_by_user(self, user_id: int) -> JobRef:
        """Request Connections for User."""
        return self._executor.execute(
            CONNECTIONS_BY_USER, path={"userId": user_id}
        )

    def wait_connections_by_user(
        self,
        user_id: int,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> ConnectionsByUserResultResult:
        return self._wait(
            CONNECTIONS_BY_USER,
            path={"userId": user_id},
            result=CONNECTIONS_BY_USER_RESULT,
            interval=interval,
            timeout=timeout,
        )

    def connections_by_user_result(
        self, job_id: str
    ) -> ConnectionsByUserResult:
        """Get Connections for User by Job ID."""
        return self._executor.execute(
            CONNECTIONS_BY_USER_RESULT, path={"jobId": job_id}
        )

    def drop_connections(self, body: DropConnectionsBody) -> None:
        """Drop Connections for Users or IPs."""
        return self._executor.execute(DROP_CONNECTIONS, body=body)

    def connections_by_node(self, node_uuid: UUID) -> JobRef:
        """Request Connections for Node."""
        return self._executor.execute(
            CONNECTIONS_BY_NODE, path={"nodeUuid": node_uuid}
        )

    def wait_connections_by_node(
        self,
        node_uuid: UUID,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> ConnectionsByNodeResultResult:
        return self._wait(
            CONNECTIONS_BY_NODE,
            path={"nodeUuid": node_uuid},
            result=CONNECTIONS_BY_NODE_RESULT,
            interval=interval,
            timeout=timeout,
        )

    def connections_by_node_result(
        self, job_id: str
    ) -> ConnectionsByNodeResult:
        """Get Connections for Node by Job ID."""
        return self._executor.execute(
            CONNECTIONS_BY_NODE_RESULT, path={"jobId": job_id}
        )

    def geocheck_by_node(
        self, node_uuid: UUID, body: GeocheckByNodeBody
    ) -> JobRef:
        """Request Geocheck for Node."""
        return self._executor.execute(
            GEOCHECK_BY_NODE, path={"nodeUuid": node_uuid}, body=body
        )

    def wait_geocheck_by_node(
        self,
        node_uuid: UUID,
        body: GeocheckByNodeBody,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> GeocheckByNodeResultResult:
        return self._wait(
            GEOCHECK_BY_NODE,
            path={"nodeUuid": node_uuid},
            body=body,
            result=GEOCHECK_BY_NODE_RESULT,
            interval=interval,
            timeout=timeout,
        )

    def geocheck_by_node_result(self, job_id: str) -> GeocheckByNodeResult:
        """Get Geocheck for Node by Job ID."""
        return self._executor.execute(
            GEOCHECK_BY_NODE_RESULT, path={"jobId": job_id}
        )


class AsyncConnectionsApi(AsyncGroup):
    async def connections_by_user(self, user_id: int) -> JobRef:
        """Request Connections for User."""
        return await self._executor.execute(
            CONNECTIONS_BY_USER, path={"userId": user_id}
        )

    async def wait_connections_by_user(
        self,
        user_id: int,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> ConnectionsByUserResultResult:
        return await self._wait(
            CONNECTIONS_BY_USER,
            path={"userId": user_id},
            result=CONNECTIONS_BY_USER_RESULT,
            interval=interval,
            timeout=timeout,
        )

    async def connections_by_user_result(
        self, job_id: str
    ) -> ConnectionsByUserResult:
        """Get Connections for User by Job ID."""
        return await self._executor.execute(
            CONNECTIONS_BY_USER_RESULT, path={"jobId": job_id}
        )

    async def drop_connections(self, body: DropConnectionsBody) -> None:
        """Drop Connections for Users or IPs."""
        return await self._executor.execute(DROP_CONNECTIONS, body=body)

    async def connections_by_node(self, node_uuid: UUID) -> JobRef:
        """Request Connections for Node."""
        return await self._executor.execute(
            CONNECTIONS_BY_NODE, path={"nodeUuid": node_uuid}
        )

    async def wait_connections_by_node(
        self,
        node_uuid: UUID,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> ConnectionsByNodeResultResult:
        return await self._wait(
            CONNECTIONS_BY_NODE,
            path={"nodeUuid": node_uuid},
            result=CONNECTIONS_BY_NODE_RESULT,
            interval=interval,
            timeout=timeout,
        )

    async def connections_by_node_result(
        self, job_id: str
    ) -> ConnectionsByNodeResult:
        """Get Connections for Node by Job ID."""
        return await self._executor.execute(
            CONNECTIONS_BY_NODE_RESULT, path={"jobId": job_id}
        )

    async def geocheck_by_node(
        self, node_uuid: UUID, body: GeocheckByNodeBody
    ) -> JobRef:
        """Request Geocheck for Node."""
        return await self._executor.execute(
            GEOCHECK_BY_NODE, path={"nodeUuid": node_uuid}, body=body
        )

    async def wait_geocheck_by_node(
        self,
        node_uuid: UUID,
        body: GeocheckByNodeBody,
        *,
        interval: float = 1.0,
        timeout: float | None = 60.0,
    ) -> GeocheckByNodeResultResult:
        return await self._wait(
            GEOCHECK_BY_NODE,
            path={"nodeUuid": node_uuid},
            body=body,
            result=GEOCHECK_BY_NODE_RESULT,
            interval=interval,
            timeout=timeout,
        )

    async def geocheck_by_node_result(
        self, job_id: str
    ) -> GeocheckByNodeResult:
        """Get Geocheck for Node by Job ID."""
        return await self._executor.execute(
            GEOCHECK_BY_NODE_RESULT, path={"jobId": job_id}
        )
