# @generated by tools/codegen -- do not edit
"""Connections Controller."""

from uuid import UUID

from remnawave._generated.models import (
    ConnectionsByNodeResult,
    ConnectionsByUserResult,
    DropConnectionsBody,
    GeocheckByNode,
    GeocheckByNodeBody,
    GeocheckByNodeResult,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

CONNECTIONS_BY_USER: Operation[GeocheckByNode] = Operation(
    "POST",
    "/api/connections/by-user/{userId}",
    GeocheckByNode,
)
CONNECTIONS_BY_USER_RESULT: Operation[ConnectionsByUserResult] = Operation(
    "GET",
    "/api/connections/by-user/{jobId}",
    ConnectionsByUserResult,
)
DROP_CONNECTIONS = NoContentOperation("POST", "/api/connections/drop")
CONNECTIONS_BY_NODE: Operation[GeocheckByNode] = Operation(
    "POST",
    "/api/connections/by-node/{nodeUuid}",
    GeocheckByNode,
)
CONNECTIONS_BY_NODE_RESULT: Operation[ConnectionsByNodeResult] = Operation(
    "GET",
    "/api/connections/by-node/{jobId}",
    ConnectionsByNodeResult,
)
GEOCHECK_BY_NODE: Operation[GeocheckByNode] = Operation(
    "POST",
    "/api/connections/geocheck/{nodeUuid}",
    GeocheckByNode,
)
GEOCHECK_BY_NODE_RESULT: Operation[GeocheckByNodeResult] = Operation(
    "GET",
    "/api/connections/geocheck/{jobId}",
    GeocheckByNodeResult,
)


class ConnectionsApi(SyncGroup):
    def connections_by_user(self, user_id: int) -> GeocheckByNode:
        """Request Connections for User."""
        return self._executor.execute(
            CONNECTIONS_BY_USER, path={"userId": user_id}
        )

    def connections_by_user_result(
        self, job_id: str
    ) -> ConnectionsByUserResult:
        """Get Connections for User by Job ID."""
        return self._executor.execute(
            CONNECTIONS_BY_USER_RESULT, path={"jobId": job_id}
        )

    def drop_connections(self, body: DropConnectionsBody) -> None:
        """Drop Connections for Users or IPs."""
        return self._executor.execute(DROP_CONNECTIONS, body=body)

    def connections_by_node(self, node_uuid: UUID) -> GeocheckByNode:
        """Request Connections for Node."""
        return self._executor.execute(
            CONNECTIONS_BY_NODE, path={"nodeUuid": node_uuid}
        )

    def connections_by_node_result(
        self, job_id: str
    ) -> ConnectionsByNodeResult:
        """Get Connections for Node by Job ID."""
        return self._executor.execute(
            CONNECTIONS_BY_NODE_RESULT, path={"jobId": job_id}
        )

    def geocheck_by_node(
        self, node_uuid: UUID, body: GeocheckByNodeBody
    ) -> GeocheckByNode:
        """Request Geocheck for Node."""
        return self._executor.execute(
            GEOCHECK_BY_NODE, path={"nodeUuid": node_uuid}, body=body
        )

    def geocheck_by_node_result(self, job_id: str) -> GeocheckByNodeResult:
        """Get Geocheck for Node by Job ID."""
        return self._executor.execute(
            GEOCHECK_BY_NODE_RESULT, path={"jobId": job_id}
        )


class AsyncConnectionsApi(AsyncGroup):
    async def connections_by_user(self, user_id: int) -> GeocheckByNode:
        """Request Connections for User."""
        return await self._executor.execute(
            CONNECTIONS_BY_USER, path={"userId": user_id}
        )

    async def connections_by_user_result(
        self, job_id: str
    ) -> ConnectionsByUserResult:
        """Get Connections for User by Job ID."""
        return await self._executor.execute(
            CONNECTIONS_BY_USER_RESULT, path={"jobId": job_id}
        )

    async def drop_connections(self, body: DropConnectionsBody) -> None:
        """Drop Connections for Users or IPs."""
        return await self._executor.execute(DROP_CONNECTIONS, body=body)

    async def connections_by_node(self, node_uuid: UUID) -> GeocheckByNode:
        """Request Connections for Node."""
        return await self._executor.execute(
            CONNECTIONS_BY_NODE, path={"nodeUuid": node_uuid}
        )

    async def connections_by_node_result(
        self, job_id: str
    ) -> ConnectionsByNodeResult:
        """Get Connections for Node by Job ID."""
        return await self._executor.execute(
            CONNECTIONS_BY_NODE_RESULT, path={"jobId": job_id}
        )

    async def geocheck_by_node(
        self, node_uuid: UUID, body: GeocheckByNodeBody
    ) -> GeocheckByNode:
        """Request Geocheck for Node."""
        return await self._executor.execute(
            GEOCHECK_BY_NODE, path={"nodeUuid": node_uuid}, body=body
        )

    async def geocheck_by_node_result(
        self, job_id: str
    ) -> GeocheckByNodeResult:
        """Get Geocheck for Node by Job ID."""
        return await self._executor.execute(
            GEOCHECK_BY_NODE_RESULT, path={"jobId": job_id}
        )
