# @generated by tools/codegen -- do not edit
"""External Squads Controller."""

from uuid import UUID

from remnawave._generated.models import (
    DeleteSnippetBody,
    ExternalSquad,
    ExternalSquads,
    ReorderNodePluginsBody,
    UpdateExternalSquadBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_EXTERNAL_SQUADS: Operation[ExternalSquads] = Operation(
    "GET",
    "/api/external-squads",
    ExternalSquads,
)
CREATE_EXTERNAL_SQUAD: Operation[ExternalSquad] = Operation(
    "POST",
    "/api/external-squads",
    ExternalSquad,
)
UPDATE_EXTERNAL_SQUAD: Operation[ExternalSquad] = Operation(
    "PATCH",
    "/api/external-squads",
    ExternalSquad,
)
GET_EXTERNAL_SQUAD_BY_UUID: Operation[ExternalSquad] = Operation(
    "GET",
    "/api/external-squads/{uuid}",
    ExternalSquad,
)
DELETE_EXTERNAL_SQUAD = NoContentOperation(
    "DELETE", "/api/external-squads/{uuid}"
)
ADD_USERS_TO_EXTERNAL_SQUAD = NoContentOperation(
    "POST", "/api/external-squads/{uuid}/bulk-actions/add-users"
)
REMOVE_USERS_FROM_EXTERNAL_SQUAD = NoContentOperation(
    "DELETE", "/api/external-squads/{uuid}/bulk-actions/remove-users"
)
REORDER_EXTERNAL_SQUADS: Operation[ExternalSquads] = Operation(
    "POST",
    "/api/external-squads/actions/reorder",
    ExternalSquads,
)


class ExternalSquadsApi(SyncGroup):
    def get_external_squads(self) -> ExternalSquads:
        """Get all external squads."""
        return self._executor.execute(GET_EXTERNAL_SQUADS)

    def create_external_squad(self, body: DeleteSnippetBody) -> ExternalSquad:
        """Create external squad."""
        return self._executor.execute(CREATE_EXTERNAL_SQUAD, body=body)

    def update_external_squad(
        self, body: UpdateExternalSquadBody
    ) -> ExternalSquad:
        """Update external squad."""
        return self._executor.execute(UPDATE_EXTERNAL_SQUAD, body=body)

    def get_external_squad_by_uuid(self, uuid: UUID) -> ExternalSquad:
        """Get external squad by uuid."""
        return self._executor.execute(
            GET_EXTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    def delete_external_squad(self, uuid: UUID) -> None:
        """Delete external squad."""
        return self._executor.execute(
            DELETE_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    def add_users_to_external_squad(self, uuid: UUID) -> None:
        """Add all users to external squad."""
        return self._executor.execute(
            ADD_USERS_TO_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    def remove_users_from_external_squad(self, uuid: UUID) -> None:
        """Delete users from external squad."""
        return self._executor.execute(
            REMOVE_USERS_FROM_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    def reorder_external_squads(
        self, body: ReorderNodePluginsBody
    ) -> ExternalSquads:
        """Reorder external squads."""
        return self._executor.execute(REORDER_EXTERNAL_SQUADS, body=body)


class AsyncExternalSquadsApi(AsyncGroup):
    async def get_external_squads(self) -> ExternalSquads:
        """Get all external squads."""
        return await self._executor.execute(GET_EXTERNAL_SQUADS)

    async def create_external_squad(
        self, body: DeleteSnippetBody
    ) -> ExternalSquad:
        """Create external squad."""
        return await self._executor.execute(CREATE_EXTERNAL_SQUAD, body=body)

    async def update_external_squad(
        self, body: UpdateExternalSquadBody
    ) -> ExternalSquad:
        """Update external squad."""
        return await self._executor.execute(UPDATE_EXTERNAL_SQUAD, body=body)

    async def get_external_squad_by_uuid(self, uuid: UUID) -> ExternalSquad:
        """Get external squad by uuid."""
        return await self._executor.execute(
            GET_EXTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    async def delete_external_squad(self, uuid: UUID) -> None:
        """Delete external squad."""
        return await self._executor.execute(
            DELETE_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def add_users_to_external_squad(self, uuid: UUID) -> None:
        """Add all users to external squad."""
        return await self._executor.execute(
            ADD_USERS_TO_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def remove_users_from_external_squad(self, uuid: UUID) -> None:
        """Delete users from external squad."""
        return await self._executor.execute(
            REMOVE_USERS_FROM_EXTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def reorder_external_squads(
        self, body: ReorderNodePluginsBody
    ) -> ExternalSquads:
        """Reorder external squads."""
        return await self._executor.execute(REORDER_EXTERNAL_SQUADS, body=body)
