# @generated by tools/codegen -- do not edit
"""Hosts Bulk Actions Controller."""

from remnawave._generated.models import (
    BulkDeleteHostsRequest,
    Host2,
    SetInboundToManyHostsRequest,
    SetPortToManyHostsRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

DELETE_HOSTS: Operation[list[Host2]] = Operation(
    "POST",
    "/api/hosts/bulk/delete",
    list[Host2],
)
DISABLE_HOSTS: Operation[list[Host2]] = Operation(
    "POST",
    "/api/hosts/bulk/disable",
    list[Host2],
)
ENABLE_HOSTS: Operation[list[Host2]] = Operation(
    "POST",
    "/api/hosts/bulk/enable",
    list[Host2],
)
SET_INBOUND_TO_HOSTS: Operation[list[Host2]] = Operation(
    "POST",
    "/api/hosts/bulk/set-inbound",
    list[Host2],
)
SET_PORT_TO_HOSTS: Operation[list[Host2]] = Operation(
    "POST",
    "/api/hosts/bulk/set-port",
    list[Host2],
)


class HostsBulkActionsApi(SyncGroup):
    def delete_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Delete hosts by UUIDs."""
        return self._executor.execute(DELETE_HOSTS, body=body)

    def disable_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Disable hosts by UUIDs."""
        return self._executor.execute(DISABLE_HOSTS, body=body)

    def enable_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Enable hosts by UUIDs."""
        return self._executor.execute(ENABLE_HOSTS, body=body)

    def set_inbound_to_hosts(
        self, body: SetInboundToManyHostsRequest
    ) -> list[Host2]:
        """Set inbound to hosts by UUIDs."""
        return self._executor.execute(SET_INBOUND_TO_HOSTS, body=body)

    def set_port_to_hosts(self, body: SetPortToManyHostsRequest) -> list[Host2]:
        """Set port to hosts by UUIDs."""
        return self._executor.execute(SET_PORT_TO_HOSTS, body=body)


class AsyncHostsBulkActionsApi(AsyncGroup):
    async def delete_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Delete hosts by UUIDs."""
        return await self._executor.execute(DELETE_HOSTS, body=body)

    async def disable_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Disable hosts by UUIDs."""
        return await self._executor.execute(DISABLE_HOSTS, body=body)

    async def enable_hosts(self, body: BulkDeleteHostsRequest) -> list[Host2]:
        """Enable hosts by UUIDs."""
        return await self._executor.execute(ENABLE_HOSTS, body=body)

    async def set_inbound_to_hosts(
        self, body: SetInboundToManyHostsRequest
    ) -> list[Host2]:
        """Set inbound to hosts by UUIDs."""
        return await self._executor.execute(SET_INBOUND_TO_HOSTS, body=body)

    async def set_port_to_hosts(
        self, body: SetPortToManyHostsRequest
    ) -> list[Host2]:
        """Set port to hosts by UUIDs."""
        return await self._executor.execute(SET_PORT_TO_HOSTS, body=body)
