# @generated by tools/codegen -- do not edit
"""Hosts Controller."""

from uuid import UUID

from remnawave._generated.models import (
    CreateHostBody,
    Host,
    Hosts,
    HostsTags,
    ReorderHostsBody,
    UpdateHostBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_HOSTS_TAGS: Operation[HostsTags] = Operation(
    "GET",
    "/api/hosts/tags",
    HostsTags,
)
CREATE_HOST: Operation[Host] = Operation(
    "POST",
    "/api/hosts",
    Host,
)
UPDATE_HOST: Operation[Host] = Operation(
    "PATCH",
    "/api/hosts",
    Host,
)
GET_HOSTS: Operation[list[Host]] = Operation(
    "GET",
    "/api/hosts",
    list[Host],
)
GET_ONE_HOST: Operation[Host] = Operation(
    "GET",
    "/api/hosts/{uuid}",
    Host,
)
DELETE_HOST = NoContentOperation("DELETE", "/api/hosts/{uuid}")
REORDER_HOSTS: Operation[Hosts] = Operation(
    "POST",
    "/api/hosts/actions/reorder",
    Hosts,
)


class HostsApi(SyncGroup):
    def get_hosts_tags(self) -> HostsTags:
        """Get tags of hosts."""
        return self._executor.execute(GET_HOSTS_TAGS)

    def create_host(self, body: CreateHostBody) -> Host:
        """Create a new host."""
        return self._executor.execute(CREATE_HOST, body=body)

    def update_host(self, body: UpdateHostBody) -> Host:
        """Update a host."""
        return self._executor.execute(UPDATE_HOST, body=body)

    def get_hosts(self) -> list[Host]:
        """Get hosts."""
        return self._executor.execute(GET_HOSTS)

    def get_one_host(self, uuid: UUID) -> Host:
        """Get a host by UUID."""
        return self._executor.execute(GET_ONE_HOST, path={"uuid": uuid})

    def delete_host(self, uuid: UUID) -> None:
        """Delete a host by UUID."""
        return self._executor.execute(DELETE_HOST, path={"uuid": uuid})

    def reorder_hosts(self, body: ReorderHostsBody) -> Hosts:
        """Reorder hosts."""
        return self._executor.execute(REORDER_HOSTS, body=body)


class AsyncHostsApi(AsyncGroup):
    async def get_hosts_tags(self) -> HostsTags:
        """Get tags of hosts."""
        return await self._executor.execute(GET_HOSTS_TAGS)

    async def create_host(self, body: CreateHostBody) -> Host:
        """Create a new host."""
        return await self._executor.execute(CREATE_HOST, body=body)

    async def update_host(self, body: UpdateHostBody) -> Host:
        """Update a host."""
        return await self._executor.execute(UPDATE_HOST, body=body)

    async def get_hosts(self) -> list[Host]:
        """Get hosts."""
        return await self._executor.execute(GET_HOSTS)

    async def get_one_host(self, uuid: UUID) -> Host:
        """Get a host by UUID."""
        return await self._executor.execute(GET_ONE_HOST, path={"uuid": uuid})

    async def delete_host(self, uuid: UUID) -> None:
        """Delete a host by UUID."""
        return await self._executor.execute(DELETE_HOST, path={"uuid": uuid})

    async def reorder_hosts(self, body: ReorderHostsBody) -> Hosts:
        """Reorder hosts."""
        return await self._executor.execute(REORDER_HOSTS, body=body)
