# @generated by tools/codegen -- do not edit
"""Hosts Controller."""

from remnawave._generated.models import (
    CreateHostRequest,
    Host,
    Host2,
    Host3,
    ReorderHostRequest,
    UpdateHostRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

CREATE_HOST: Operation[Host2] = Operation(
    "POST",
    "/api/hosts",
    Host2,
)
UPDATE_HOST: Operation[Host2] = Operation(
    "PATCH",
    "/api/hosts",
    Host2,
)
GET_ALL_HOSTS: Operation[list[Host2]] = Operation(
    "GET",
    "/api/hosts",
    list[Host2],
)
GET_ONE_HOST: Operation[Host2] = Operation(
    "GET",
    "/api/hosts/{uuid}",
    Host2,
)
DELETE_HOST: Operation[Host] = Operation(
    "DELETE",
    "/api/hosts/{uuid}",
    Host,
)
REORDER_HOSTS: Operation[Host3] = Operation(
    "POST",
    "/api/hosts/actions/reorder",
    Host3,
)


class HostsApi(SyncGroup):
    def create_host(self, body: CreateHostRequest) -> Host2:
        """Create a new host."""
        return self._executor.execute(CREATE_HOST, body=body)

    def update_host(self, body: UpdateHostRequest) -> Host2:
        """Update a host."""
        return self._executor.execute(UPDATE_HOST, body=body)

    def get_all_hosts(self) -> list[Host2]:
        """Get all hosts."""
        return self._executor.execute(GET_ALL_HOSTS)

    def get_one_host(self, uuid: str) -> Host2:
        """Get a host by UUID."""
        return self._executor.execute(GET_ONE_HOST, path={"uuid": uuid})

    def delete_host(self, uuid: str) -> Host:
        """Delete a host by UUID."""
        return self._executor.execute(DELETE_HOST, path={"uuid": uuid})

    def reorder_hosts(self, body: ReorderHostRequest) -> Host3:
        """Reorder hosts."""
        return self._executor.execute(REORDER_HOSTS, body=body)


class AsyncHostsApi(AsyncGroup):
    async def create_host(self, body: CreateHostRequest) -> Host2:
        """Create a new host."""
        return await self._executor.execute(CREATE_HOST, body=body)

    async def update_host(self, body: UpdateHostRequest) -> Host2:
        """Update a host."""
        return await self._executor.execute(UPDATE_HOST, body=body)

    async def get_all_hosts(self) -> list[Host2]:
        """Get all hosts."""
        return await self._executor.execute(GET_ALL_HOSTS)

    async def get_one_host(self, uuid: str) -> Host2:
        """Get a host by UUID."""
        return await self._executor.execute(GET_ONE_HOST, path={"uuid": uuid})

    async def delete_host(self, uuid: str) -> Host:
        """Delete a host by UUID."""
        return await self._executor.execute(DELETE_HOST, path={"uuid": uuid})

    async def reorder_hosts(self, body: ReorderHostRequest) -> Host3:
        """Reorder hosts."""
        return await self._executor.execute(REORDER_HOSTS, body=body)
