# @generated by tools/codegen -- do not edit
"""HWID User Devices Controller."""

from collections.abc import AsyncIterator, Iterator
from typing import Any

from remnawave._generated.models import (
    CreateUserHwidDeviceBody,
    DeleteAllUserHwidDevicesBody,
    DeleteUserHwidDeviceBody,
    Device,
    HwidDevicesPage,
    HwidDevicesStats,
    QueryFilter,
    QuerySort,
    TopUserByDevices,
    TopUsersPage,
    UserHwidDevice,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_ALL_USERS: Operation[HwidDevicesPage] = Operation(
    "GET",
    "/api/hwid/devices",
    HwidDevicesPage,
    pagination=Pagination(items_field="devices", max_page_size=1000),
)
CREATE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices",
    UserHwidDevice,
)
DELETE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices/delete",
    UserHwidDevice,
)
DELETE_ALL_USER_HWID_DEVICES: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices/delete-all",
    UserHwidDevice,
)
GET_HWID_DEVICES_STATS: Operation[HwidDevicesStats] = Operation(
    "GET",
    "/api/hwid/devices/stats",
    HwidDevicesStats,
)
GET_TOP_USERS_BY_HWID_DEVICES: Operation[TopUsersPage] = Operation(
    "GET",
    "/api/hwid/devices/top-users",
    TopUsersPage,
    pagination=Pagination(items_field="users", max_page_size=100),
)
GET_USER_HWID_DEVICES: Operation[UserHwidDevice] = Operation(
    "GET",
    "/api/hwid/devices/{userId}",
    UserHwidDevice,
)


class HwidUserDevicesApi(SyncGroup):
    def get_all_users(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> HwidDevicesPage:
        """Get HWID devices."""
        return self._executor.execute(
            GET_ALL_USERS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> Iterator[Device]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_USERS, page_size)

    def create_user_hwid_device(
        self, body: CreateUserHwidDeviceBody
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceBody
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    def delete_all_user_hwid_devices(
        self, body: DeleteAllUserHwidDevicesBody
    ) -> UserHwidDevice:
        """Delete all user HWID devices."""
        return self._executor.execute(DELETE_ALL_USER_HWID_DEVICES, body=body)

    def get_hwid_devices_stats(self) -> HwidDevicesStats:
        """Get HWID devices stats."""
        return self._executor.execute(GET_HWID_DEVICES_STATS)

    def get_top_users_by_hwid_devices(
        self, *, start: int | None = None, size: int | None = None
    ) -> TopUsersPage:
        """Get top users by HWID devices."""
        return self._executor.execute(
            GET_TOP_USERS_BY_HWID_DEVICES, query={"start": start, "size": size}
        )

    def iter_top_users_by_hwid_devices(
        self,
        page_size: int | None = None,
    ) -> Iterator[TopUserByDevices]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_TOP_USERS_BY_HWID_DEVICES, page_size)

    def get_user_hwid_devices(self, user_id: int) -> UserHwidDevice:
        """Get user HWID devices."""
        return self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userId": user_id}
        )


class AsyncHwidUserDevicesApi(AsyncGroup):
    async def get_all_users(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> HwidDevicesPage:
        """Get HWID devices."""
        return await self._executor.execute(
            GET_ALL_USERS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    async def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[Device]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_USERS, page_size):
            yield item

    async def create_user_hwid_device(
        self, body: CreateUserHwidDeviceBody
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return await self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    async def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceBody
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return await self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    async def delete_all_user_hwid_devices(
        self, body: DeleteAllUserHwidDevicesBody
    ) -> UserHwidDevice:
        """Delete all user HWID devices."""
        return await self._executor.execute(
            DELETE_ALL_USER_HWID_DEVICES, body=body
        )

    async def get_hwid_devices_stats(self) -> HwidDevicesStats:
        """Get HWID devices stats."""
        return await self._executor.execute(GET_HWID_DEVICES_STATS)

    async def get_top_users_by_hwid_devices(
        self, *, start: int | None = None, size: int | None = None
    ) -> TopUsersPage:
        """Get top users by HWID devices."""
        return await self._executor.execute(
            GET_TOP_USERS_BY_HWID_DEVICES, query={"start": start, "size": size}
        )

    async def iter_top_users_by_hwid_devices(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[TopUserByDevices]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(
            GET_TOP_USERS_BY_HWID_DEVICES, page_size
        ):
            yield item

    async def get_user_hwid_devices(self, user_id: int) -> UserHwidDevice:
        """Get user HWID devices."""
        return await self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userId": user_id}
        )
