# @generated by tools/codegen -- do not edit
"""HWID User Devices."""

from remnawave._generated.models import (
    CreateUserHwidDeviceRequest,
    DeleteUserHwidDeviceRequest,
    UserHwidDevice,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

CREATE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices",
    UserHwidDevice,
)
DELETE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices/delete",
    UserHwidDevice,
)
GET_USER_HWID_DEVICES: Operation[UserHwidDevice] = Operation(
    "GET",
    "/api/hwid/devices/{userUuid}",
    UserHwidDevice,
)


class HwidUserDevicesApi(SyncGroup):
    def create_user_hwid_device(
        self, body: CreateUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    def get_user_hwid_devices(self, user_uuid: str) -> UserHwidDevice:
        """Get user HWID devices."""
        return self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userUuid": user_uuid}
        )


class AsyncHwidUserDevicesApi(AsyncGroup):
    async def create_user_hwid_device(
        self, body: CreateUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return await self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    async def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return await self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    async def get_user_hwid_devices(self, user_uuid: str) -> UserHwidDevice:
        """Get user HWID devices."""
        return await self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userUuid": user_uuid}
        )
