# @generated by tools/codegen -- do not edit
"""HWID User Devices Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    CreateUserHwidDeviceRequest,
    DeleteAllUserHwidDevicesRequest,
    DeleteUserHwidDeviceRequest,
    Device,
    HwidDevices,
    HwidDevicesStats,
    TopUserByDevices,
    TopUsersPage,
    UserHwidDevice,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_ALL_USERS: Operation[HwidDevices] = Operation(
    "GET",
    "/api/hwid/devices",
    HwidDevices,
    pagination=Pagination(items_field="devices", max_page_size=100),
)
CREATE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices",
    UserHwidDevice,
)
DELETE_USER_HWID_DEVICE: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices/delete",
    UserHwidDevice,
)
DELETE_ALL_USER_HWID_DEVICES: Operation[UserHwidDevice] = Operation(
    "POST",
    "/api/hwid/devices/delete-all",
    UserHwidDevice,
)
GET_HWID_DEVICES_STATS: Operation[HwidDevicesStats] = Operation(
    "GET",
    "/api/hwid/devices/stats",
    HwidDevicesStats,
)
GET_TOP_USERS_BY_HWID_DEVICES: Operation[TopUsersPage] = Operation(
    "GET",
    "/api/hwid/devices/top-users",
    TopUsersPage,
    pagination=Pagination(items_field="users", max_page_size=100),
)
GET_USER_HWID_DEVICES: Operation[UserHwidDevice] = Operation(
    "GET",
    "/api/hwid/devices/{userUuid}",
    UserHwidDevice,
)


class HwidUserDevicesApi(SyncGroup):
    def get_all_users(
        self, *, size: int | None = None, start: int | None = None
    ) -> HwidDevices:
        """Get all HWID devices."""
        return self._executor.execute(
            GET_ALL_USERS, query={"size": size, "start": start}
        )

    def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> Iterator[Device]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_USERS, page_size)

    def create_user_hwid_device(
        self, body: CreateUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    def delete_all_user_hwid_devices(
        self, body: DeleteAllUserHwidDevicesRequest
    ) -> UserHwidDevice:
        """Delete all user HWID devices."""
        return self._executor.execute(DELETE_ALL_USER_HWID_DEVICES, body=body)

    def get_hwid_devices_stats(self) -> HwidDevicesStats:
        """Get HWID devices stats."""
        return self._executor.execute(GET_HWID_DEVICES_STATS)

    def get_top_users_by_hwid_devices(
        self, *, size: int | None = None, start: int | None = None
    ) -> TopUsersPage:
        """Get top users by HWID devices."""
        return self._executor.execute(
            GET_TOP_USERS_BY_HWID_DEVICES, query={"size": size, "start": start}
        )

    def iter_top_users_by_hwid_devices(
        self,
        page_size: int | None = None,
    ) -> Iterator[TopUserByDevices]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_TOP_USERS_BY_HWID_DEVICES, page_size)

    def get_user_hwid_devices(self, user_uuid: str) -> UserHwidDevice:
        """Get user HWID devices."""
        return self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userUuid": user_uuid}
        )


class AsyncHwidUserDevicesApi(AsyncGroup):
    async def get_all_users(
        self, *, size: int | None = None, start: int | None = None
    ) -> HwidDevices:
        """Get all HWID devices."""
        return await self._executor.execute(
            GET_ALL_USERS, query={"size": size, "start": start}
        )

    async def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[Device]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_USERS, page_size):
            yield item

    async def create_user_hwid_device(
        self, body: CreateUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Create a user HWID device."""
        return await self._executor.execute(CREATE_USER_HWID_DEVICE, body=body)

    async def delete_user_hwid_device(
        self, body: DeleteUserHwidDeviceRequest
    ) -> UserHwidDevice:
        """Delete a user HWID device."""
        return await self._executor.execute(DELETE_USER_HWID_DEVICE, body=body)

    async def delete_all_user_hwid_devices(
        self, body: DeleteAllUserHwidDevicesRequest
    ) -> UserHwidDevice:
        """Delete all user HWID devices."""
        return await self._executor.execute(
            DELETE_ALL_USER_HWID_DEVICES, body=body
        )

    async def get_hwid_devices_stats(self) -> HwidDevicesStats:
        """Get HWID devices stats."""
        return await self._executor.execute(GET_HWID_DEVICES_STATS)

    async def get_top_users_by_hwid_devices(
        self, *, size: int | None = None, start: int | None = None
    ) -> TopUsersPage:
        """Get top users by HWID devices."""
        return await self._executor.execute(
            GET_TOP_USERS_BY_HWID_DEVICES, query={"size": size, "start": start}
        )

    async def iter_top_users_by_hwid_devices(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[TopUserByDevices]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(
            GET_TOP_USERS_BY_HWID_DEVICES, page_size
        ):
            yield item

    async def get_user_hwid_devices(self, user_uuid: str) -> UserHwidDevice:
        """Get user HWID devices."""
        return await self._executor.execute(
            GET_USER_HWID_DEVICES, path={"userUuid": user_uuid}
        )
