# @generated by tools/codegen -- do not edit
"""Infra Billing Controller."""

from collections.abc import AsyncIterator, Iterator
from uuid import UUID

from remnawave._generated.models import (
    CreateInfraBillingNodeBody,
    CreateInfraBillingRecordBody,
    CreateInfraProviderBody,
    InfraBillingNode,
    InfraBillingRecord,
    InfraBillingRecordsPage,
    InfraProvider,
    InfraProviders,
    UpdateInfraBillingNodeBody,
    UpdateInfraProviderBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
    Pagination,
)

GET_INFRA_PROVIDERS: Operation[InfraProviders] = Operation(
    "GET",
    "/api/infra-billing/providers",
    InfraProviders,
)
CREATE_INFRA_PROVIDER: Operation[InfraProvider] = Operation(
    "POST",
    "/api/infra-billing/providers",
    InfraProvider,
)
UPDATE_INFRA_PROVIDER: Operation[InfraProvider] = Operation(
    "PATCH",
    "/api/infra-billing/providers",
    InfraProvider,
)
GET_INFRA_PROVIDER: Operation[InfraProvider] = Operation(
    "GET",
    "/api/infra-billing/providers/{uuid}",
    InfraProvider,
)
DELTE_INFRA_PROVIDER = NoContentOperation(
    "DELETE", "/api/infra-billing/providers/{uuid}"
)
CREATE_INFRA_BILLING_RECORD: Operation[InfraBillingRecordsPage] = Operation(
    "POST",
    "/api/infra-billing/history",
    InfraBillingRecordsPage,
)
GET_INFRA_BILLING_RECORDS: Operation[InfraBillingRecordsPage] = Operation(
    "GET",
    "/api/infra-billing/history",
    InfraBillingRecordsPage,
    pagination=Pagination(items_field="records", max_page_size=500),
)
DELETE_INFRA_BILLING_RECORD = NoContentOperation(
    "DELETE", "/api/infra-billing/history/{uuid}"
)
GET_BILLING_NODES: Operation[InfraBillingNode] = Operation(
    "GET",
    "/api/infra-billing/nodes",
    InfraBillingNode,
)
UPDATE_INFRA_BILLING_NODE: Operation[InfraBillingNode] = Operation(
    "PATCH",
    "/api/infra-billing/nodes",
    InfraBillingNode,
)
CREATE_INFRA_BILLING_NODE: Operation[InfraBillingNode] = Operation(
    "POST",
    "/api/infra-billing/nodes",
    InfraBillingNode,
)
DELETE_INFRA_BILLING_NODE = NoContentOperation(
    "DELETE", "/api/infra-billing/nodes/{uuid}"
)


class InfraBillingApi(SyncGroup):
    def get_infra_providers(self) -> InfraProviders:
        """Get all infra providers."""
        return self._executor.execute(GET_INFRA_PROVIDERS)

    def create_infra_provider(
        self, body: CreateInfraProviderBody
    ) -> InfraProvider:
        """Create infra provider."""
        return self._executor.execute(CREATE_INFRA_PROVIDER, body=body)

    def update_infra_provider(
        self, body: UpdateInfraProviderBody
    ) -> InfraProvider:
        """Update infra provider."""
        return self._executor.execute(UPDATE_INFRA_PROVIDER, body=body)

    def get_infra_provider(self, uuid: UUID) -> InfraProvider:
        """Get infra provider by uuid."""
        return self._executor.execute(GET_INFRA_PROVIDER, path={"uuid": uuid})

    def delte_infra_provider(self, uuid: UUID) -> None:
        """Delete infra provider by uuid."""
        return self._executor.execute(DELTE_INFRA_PROVIDER, path={"uuid": uuid})

    def create_infra_billing_record(
        self, body: CreateInfraBillingRecordBody
    ) -> InfraBillingRecordsPage:
        """Create infra billing history."""
        return self._executor.execute(CREATE_INFRA_BILLING_RECORD, body=body)

    def get_infra_billing_records(
        self, *, start: int | None = None, size: int | None = None
    ) -> InfraBillingRecordsPage:
        """Get infra billing history."""
        return self._executor.execute(
            GET_INFRA_BILLING_RECORDS, query={"start": start, "size": size}
        )

    def iter_infra_billing_records(
        self,
        page_size: int | None = None,
    ) -> Iterator[InfraBillingRecord]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_INFRA_BILLING_RECORDS, page_size)

    def delete_infra_billing_record(self, uuid: UUID) -> None:
        """Delete infra billing history."""
        return self._executor.execute(
            DELETE_INFRA_BILLING_RECORD, path={"uuid": uuid}
        )

    def get_billing_nodes(self) -> InfraBillingNode:
        """Get infra billing nodes."""
        return self._executor.execute(GET_BILLING_NODES)

    def update_infra_billing_node(
        self, body: UpdateInfraBillingNodeBody
    ) -> InfraBillingNode:
        """Update infra billing nodes."""
        return self._executor.execute(UPDATE_INFRA_BILLING_NODE, body=body)

    def create_infra_billing_node(
        self, body: CreateInfraBillingNodeBody
    ) -> InfraBillingNode:
        """Create infra billing node."""
        return self._executor.execute(CREATE_INFRA_BILLING_NODE, body=body)

    def delete_infra_billing_node(self, uuid: UUID) -> None:
        """Delete infra billing node."""
        return self._executor.execute(
            DELETE_INFRA_BILLING_NODE, path={"uuid": uuid}
        )


class AsyncInfraBillingApi(AsyncGroup):
    async def get_infra_providers(self) -> InfraProviders:
        """Get all infra providers."""
        return await self._executor.execute(GET_INFRA_PROVIDERS)

    async def create_infra_provider(
        self, body: CreateInfraProviderBody
    ) -> InfraProvider:
        """Create infra provider."""
        return await self._executor.execute(CREATE_INFRA_PROVIDER, body=body)

    async def update_infra_provider(
        self, body: UpdateInfraProviderBody
    ) -> InfraProvider:
        """Update infra provider."""
        return await self._executor.execute(UPDATE_INFRA_PROVIDER, body=body)

    async def get_infra_provider(self, uuid: UUID) -> InfraProvider:
        """Get infra provider by uuid."""
        return await self._executor.execute(
            GET_INFRA_PROVIDER, path={"uuid": uuid}
        )

    async def delte_infra_provider(self, uuid: UUID) -> None:
        """Delete infra provider by uuid."""
        return await self._executor.execute(
            DELTE_INFRA_PROVIDER, path={"uuid": uuid}
        )

    async def create_infra_billing_record(
        self, body: CreateInfraBillingRecordBody
    ) -> InfraBillingRecordsPage:
        """Create infra billing history."""
        return await self._executor.execute(
            CREATE_INFRA_BILLING_RECORD, body=body
        )

    async def get_infra_billing_records(
        self, *, start: int | None = None, size: int | None = None
    ) -> InfraBillingRecordsPage:
        """Get infra billing history."""
        return await self._executor.execute(
            GET_INFRA_BILLING_RECORDS, query={"start": start, "size": size}
        )

    async def iter_infra_billing_records(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[InfraBillingRecord]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_INFRA_BILLING_RECORDS, page_size):
            yield item

    async def delete_infra_billing_record(self, uuid: UUID) -> None:
        """Delete infra billing history."""
        return await self._executor.execute(
            DELETE_INFRA_BILLING_RECORD, path={"uuid": uuid}
        )

    async def get_billing_nodes(self) -> InfraBillingNode:
        """Get infra billing nodes."""
        return await self._executor.execute(GET_BILLING_NODES)

    async def update_infra_billing_node(
        self, body: UpdateInfraBillingNodeBody
    ) -> InfraBillingNode:
        """Update infra billing nodes."""
        return await self._executor.execute(
            UPDATE_INFRA_BILLING_NODE, body=body
        )

    async def create_infra_billing_node(
        self, body: CreateInfraBillingNodeBody
    ) -> InfraBillingNode:
        """Create infra billing node."""
        return await self._executor.execute(
            CREATE_INFRA_BILLING_NODE, body=body
        )

    async def delete_infra_billing_node(self, uuid: UUID) -> None:
        """Delete infra billing node."""
        return await self._executor.execute(
            DELETE_INFRA_BILLING_NODE, path={"uuid": uuid}
        )
