# @generated by tools/codegen -- do not edit
"""Internal Squads Controller."""

from datetime import date
from uuid import UUID

from remnawave._generated.models import (
    BulkDeleteUsersBody,
    CreateInternalSquadBody,
    InternalSquad,
    InternalSquadAccessibleNodes,
    InternalSquads,
    InternalSquadUsage,
    ReorderNodePluginsBody,
    UpdateInternalSquadBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_INTERNAL_SQUADS: Operation[InternalSquads] = Operation(
    "GET",
    "/api/internal-squads",
    InternalSquads,
)
CREATE_INTERNAL_SQUAD: Operation[InternalSquad] = Operation(
    "POST",
    "/api/internal-squads",
    InternalSquad,
)
UPDATE_INTERNAL_SQUAD: Operation[InternalSquad] = Operation(
    "PATCH",
    "/api/internal-squads",
    InternalSquad,
)
GET_INTERNAL_SQUAD_BY_UUID: Operation[InternalSquad] = Operation(
    "GET",
    "/api/internal-squads/{uuid}",
    InternalSquad,
)
DELETE_INTERNAL_SQUAD = NoContentOperation(
    "DELETE", "/api/internal-squads/{uuid}"
)
GET_INTERNAL_SQUAD_ACCESSIBLE_NODES: Operation[InternalSquadAccessibleNodes] = (
    Operation(
        "GET",
        "/api/internal-squads/{uuid}/accessible-nodes",
        InternalSquadAccessibleNodes,
    )
)
GET_INTERNAL_SQUAD_USAGE: Operation[InternalSquadUsage] = Operation(
    "GET",
    "/api/internal-squads/{uuid}/usage",
    InternalSquadUsage,
)
ADD_USERS_TO_INTERNAL_SQUAD = NoContentOperation(
    "POST", "/api/internal-squads/{uuid}/bulk-actions/add-users"
)
REMOVE_USERS_FROM_INTERNAL_SQUAD = NoContentOperation(
    "DELETE", "/api/internal-squads/{uuid}/bulk-actions/remove-users"
)
REORDER_INTERNAL_SQUADS: Operation[InternalSquads] = Operation(
    "POST",
    "/api/internal-squads/actions/reorder",
    InternalSquads,
)
ADD_MANY_USERS_TO_INTERNAL_SQUAD = NoContentOperation(
    "POST", "/api/internal-squads/{uuid}/bulk-actions/add-many-users"
)
REMOVE_MANY_USERS_FROM_INTERNAL_SQUAD = NoContentOperation(
    "DELETE", "/api/internal-squads/{uuid}/bulk-actions/remove-many-users"
)


class InternalSquadsApi(SyncGroup):
    def get_internal_squads(self) -> InternalSquads:
        """Get all internal squads."""
        return self._executor.execute(GET_INTERNAL_SQUADS)

    def create_internal_squad(
        self, body: CreateInternalSquadBody
    ) -> InternalSquad:
        """Create internal squad."""
        return self._executor.execute(CREATE_INTERNAL_SQUAD, body=body)

    def update_internal_squad(
        self, body: UpdateInternalSquadBody
    ) -> InternalSquad:
        """Update internal squad."""
        return self._executor.execute(UPDATE_INTERNAL_SQUAD, body=body)

    def get_internal_squad_by_uuid(self, uuid: UUID) -> InternalSquad:
        """Get internal squad by uuid."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    def delete_internal_squad(self, uuid: UUID) -> None:
        """Delete internal squad."""
        return self._executor.execute(
            DELETE_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def get_internal_squad_accessible_nodes(
        self, uuid: UUID
    ) -> InternalSquadAccessibleNodes:
        """Get internal squad accessible nodes."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    def get_internal_squad_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        min_total_bytes: int | None = None,
        limit: int | None = None,
        cursor: int | None = None,
    ) -> InternalSquadUsage:
        """Get internal squad users traffic usage for a period."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
                "limit": limit,
                "cursor": cursor,
            },
        )

    def add_users_to_internal_squad(self, uuid: UUID) -> None:
        """Add all users to internal squad."""
        return self._executor.execute(
            ADD_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def remove_users_from_internal_squad(self, uuid: UUID) -> None:
        """Delete users from internal squad."""
        return self._executor.execute(
            REMOVE_USERS_FROM_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def reorder_internal_squads(
        self, body: ReorderNodePluginsBody
    ) -> InternalSquads:
        """Reorder internal squads."""
        return self._executor.execute(REORDER_INTERNAL_SQUADS, body=body)

    def add_many_users_to_internal_squad(
        self, uuid: UUID, body: BulkDeleteUsersBody
    ) -> None:
        """Add many users to internal squad."""
        return self._executor.execute(
            ADD_MANY_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}, body=body
        )

    def remove_many_users_from_internal_squad(
        self, uuid: UUID, body: BulkDeleteUsersBody
    ) -> None:
        """Delete many users from internal squad."""
        return self._executor.execute(
            REMOVE_MANY_USERS_FROM_INTERNAL_SQUAD,
            path={"uuid": uuid},
            body=body,
        )


class AsyncInternalSquadsApi(AsyncGroup):
    async def get_internal_squads(self) -> InternalSquads:
        """Get all internal squads."""
        return await self._executor.execute(GET_INTERNAL_SQUADS)

    async def create_internal_squad(
        self, body: CreateInternalSquadBody
    ) -> InternalSquad:
        """Create internal squad."""
        return await self._executor.execute(CREATE_INTERNAL_SQUAD, body=body)

    async def update_internal_squad(
        self, body: UpdateInternalSquadBody
    ) -> InternalSquad:
        """Update internal squad."""
        return await self._executor.execute(UPDATE_INTERNAL_SQUAD, body=body)

    async def get_internal_squad_by_uuid(self, uuid: UUID) -> InternalSquad:
        """Get internal squad by uuid."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    async def delete_internal_squad(self, uuid: UUID) -> None:
        """Delete internal squad."""
        return await self._executor.execute(
            DELETE_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def get_internal_squad_accessible_nodes(
        self, uuid: UUID
    ) -> InternalSquadAccessibleNodes:
        """Get internal squad accessible nodes."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    async def get_internal_squad_usage(
        self,
        uuid: UUID,
        start: date,
        end: date,
        *,
        min_total_bytes: int | None = None,
        limit: int | None = None,
        cursor: int | None = None,
    ) -> InternalSquadUsage:
        """Get internal squad users traffic usage for a period."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_USAGE,
            path={"uuid": uuid},
            query={
                "start": start,
                "end": end,
                "minTotalBytes": min_total_bytes,
                "limit": limit,
                "cursor": cursor,
            },
        )

    async def add_users_to_internal_squad(self, uuid: UUID) -> None:
        """Add all users to internal squad."""
        return await self._executor.execute(
            ADD_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def remove_users_from_internal_squad(self, uuid: UUID) -> None:
        """Delete users from internal squad."""
        return await self._executor.execute(
            REMOVE_USERS_FROM_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def reorder_internal_squads(
        self, body: ReorderNodePluginsBody
    ) -> InternalSquads:
        """Reorder internal squads."""
        return await self._executor.execute(REORDER_INTERNAL_SQUADS, body=body)

    async def add_many_users_to_internal_squad(
        self, uuid: UUID, body: BulkDeleteUsersBody
    ) -> None:
        """Add many users to internal squad."""
        return await self._executor.execute(
            ADD_MANY_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}, body=body
        )

    async def remove_many_users_from_internal_squad(
        self, uuid: UUID, body: BulkDeleteUsersBody
    ) -> None:
        """Delete many users from internal squad."""
        return await self._executor.execute(
            REMOVE_MANY_USERS_FROM_INTERNAL_SQUAD,
            path={"uuid": uuid},
            body=body,
        )
