# @generated by tools/codegen -- do not edit
"""Internal Squads Controller."""

from remnawave._generated.models import (
    CreateInternalSquadRequest,
    Host,
    InternalSquad,
    InternalSquadAccessibleNodes,
    InternalSquads,
    Node,
    ReorderConfigProfilesRequest,
    UpdateInternalSquadRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_INTERNAL_SQUADS: Operation[InternalSquads] = Operation(
    "GET",
    "/api/internal-squads",
    InternalSquads,
)
CREATE_INTERNAL_SQUAD: Operation[InternalSquad] = Operation(
    "POST",
    "/api/internal-squads",
    InternalSquad,
)
UPDATE_INTERNAL_SQUAD: Operation[InternalSquad] = Operation(
    "PATCH",
    "/api/internal-squads",
    InternalSquad,
)
GET_INTERNAL_SQUAD_BY_UUID: Operation[InternalSquad] = Operation(
    "GET",
    "/api/internal-squads/{uuid}",
    InternalSquad,
)
DELETE_INTERNAL_SQUAD: Operation[Host] = Operation(
    "DELETE",
    "/api/internal-squads/{uuid}",
    Host,
)
GET_INTERNAL_SQUAD_ACCESSIBLE_NODES: Operation[InternalSquadAccessibleNodes] = (
    Operation(
        "GET",
        "/api/internal-squads/{uuid}/accessible-nodes",
        InternalSquadAccessibleNodes,
    )
)
ADD_USERS_TO_INTERNAL_SQUAD: Operation[Node] = Operation(
    "POST",
    "/api/internal-squads/{uuid}/bulk-actions/add-users",
    Node,
)
REMOVE_USERS_FROM_INTERNAL_SQUAD: Operation[Node] = Operation(
    "DELETE",
    "/api/internal-squads/{uuid}/bulk-actions/remove-users",
    Node,
)
REORDER_INTERNAL_SQUADS: Operation[InternalSquads] = Operation(
    "POST",
    "/api/internal-squads/actions/reorder",
    InternalSquads,
)


class InternalSquadsApi(SyncGroup):
    def get_internal_squads(self) -> InternalSquads:
        """Get all internal squads."""
        return self._executor.execute(GET_INTERNAL_SQUADS)

    def create_internal_squad(
        self, body: CreateInternalSquadRequest
    ) -> InternalSquad:
        """Create internal squad."""
        return self._executor.execute(CREATE_INTERNAL_SQUAD, body=body)

    def update_internal_squad(
        self, body: UpdateInternalSquadRequest
    ) -> InternalSquad:
        """Update internal squad."""
        return self._executor.execute(UPDATE_INTERNAL_SQUAD, body=body)

    def get_internal_squad_by_uuid(self, uuid: str) -> InternalSquad:
        """Get internal squad by uuid."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    def delete_internal_squad(self, uuid: str) -> Host:
        """Delete internal squad."""
        return self._executor.execute(
            DELETE_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def get_internal_squad_accessible_nodes(
        self, uuid: str
    ) -> InternalSquadAccessibleNodes:
        """Get internal squad accessible nodes."""
        return self._executor.execute(
            GET_INTERNAL_SQUAD_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    def add_users_to_internal_squad(self, uuid: str) -> Node:
        """Add all users to internal squad."""
        return self._executor.execute(
            ADD_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def remove_users_from_internal_squad(self, uuid: str) -> Node:
        """Delete users from internal squad."""
        return self._executor.execute(
            REMOVE_USERS_FROM_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    def reorder_internal_squads(
        self, body: ReorderConfigProfilesRequest
    ) -> InternalSquads:
        """Reorder internal squads."""
        return self._executor.execute(REORDER_INTERNAL_SQUADS, body=body)


class AsyncInternalSquadsApi(AsyncGroup):
    async def get_internal_squads(self) -> InternalSquads:
        """Get all internal squads."""
        return await self._executor.execute(GET_INTERNAL_SQUADS)

    async def create_internal_squad(
        self, body: CreateInternalSquadRequest
    ) -> InternalSquad:
        """Create internal squad."""
        return await self._executor.execute(CREATE_INTERNAL_SQUAD, body=body)

    async def update_internal_squad(
        self, body: UpdateInternalSquadRequest
    ) -> InternalSquad:
        """Update internal squad."""
        return await self._executor.execute(UPDATE_INTERNAL_SQUAD, body=body)

    async def get_internal_squad_by_uuid(self, uuid: str) -> InternalSquad:
        """Get internal squad by uuid."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_BY_UUID, path={"uuid": uuid}
        )

    async def delete_internal_squad(self, uuid: str) -> Host:
        """Delete internal squad."""
        return await self._executor.execute(
            DELETE_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def get_internal_squad_accessible_nodes(
        self, uuid: str
    ) -> InternalSquadAccessibleNodes:
        """Get internal squad accessible nodes."""
        return await self._executor.execute(
            GET_INTERNAL_SQUAD_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    async def add_users_to_internal_squad(self, uuid: str) -> Node:
        """Add all users to internal squad."""
        return await self._executor.execute(
            ADD_USERS_TO_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def remove_users_from_internal_squad(self, uuid: str) -> Node:
        """Delete users from internal squad."""
        return await self._executor.execute(
            REMOVE_USERS_FROM_INTERNAL_SQUAD, path={"uuid": uuid}
        )

    async def reorder_internal_squads(
        self, body: ReorderConfigProfilesRequest
    ) -> InternalSquads:
        """Reorder internal squads."""
        return await self._executor.execute(REORDER_INTERNAL_SQUADS, body=body)
