# @generated by tools/codegen -- do not edit
"""IP Management Controller."""

from remnawave._generated.models import (
    DropConnectionsRequest,
    FetchIps,
    FetchIpsResult,
    Node,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

FETCH_USER_IPS: Operation[FetchIps] = Operation(
    "POST",
    "/api/ip-control/fetch-ips/{uuid}",
    FetchIps,
)
GET_FETCH_IPS_RESULT: Operation[FetchIpsResult] = Operation(
    "GET",
    "/api/ip-control/fetch-ips/result/{jobId}",
    FetchIpsResult,
)
DROP_CONNECTIONS: Operation[Node] = Operation(
    "POST",
    "/api/ip-control/drop-connections",
    Node,
)


class IpManagementApi(SyncGroup):
    def fetch_user_ips(self, uuid: str) -> FetchIps:
        """Request IP List for User."""
        return self._executor.execute(FETCH_USER_IPS, path={"uuid": uuid})

    def get_fetch_ips_result(self, job_id: str) -> FetchIpsResult:
        """Get IP List Result by Job ID."""
        return self._executor.execute(
            GET_FETCH_IPS_RESULT, path={"jobId": job_id}
        )

    def drop_connections(self, body: DropConnectionsRequest) -> Node:
        """Drop Connections for Users or IPs."""
        return self._executor.execute(DROP_CONNECTIONS, body=body)


class AsyncIpManagementApi(AsyncGroup):
    async def fetch_user_ips(self, uuid: str) -> FetchIps:
        """Request IP List for User."""
        return await self._executor.execute(FETCH_USER_IPS, path={"uuid": uuid})

    async def get_fetch_ips_result(self, job_id: str) -> FetchIpsResult:
        """Get IP List Result by Job ID."""
        return await self._executor.execute(
            GET_FETCH_IPS_RESULT, path={"jobId": job_id}
        )

    async def drop_connections(self, body: DropConnectionsRequest) -> Node:
        """Drop Connections for Users or IPs."""
        return await self._executor.execute(DROP_CONNECTIONS, body=body)
