# @generated by tools/codegen -- do not edit
"""Keygen Controller."""

from remnawave._generated.models import (
    PubKey,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GENERATE_KEY: Operation[PubKey] = Operation(
    "GET",
    "/api/keygen",
    PubKey,
)


class KeygenApi(SyncGroup):
    def generate_key(self) -> PubKey:
        """Get SECRET_KEY for Remnawave Node."""
        return self._executor.execute(GENERATE_KEY)


class AsyncKeygenApi(AsyncGroup):
    async def generate_key(self) -> PubKey:
        """Get SECRET_KEY for Remnawave Node."""
        return await self._executor.execute(GENERATE_KEY)
