# @generated by tools/codegen -- do not edit
"""Metadata Controller."""

from uuid import UUID

from remnawave._generated.models import (
    NodeMetadata,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_USER_METADATA: Operation[NodeMetadata] = Operation(
    "GET",
    "/api/metadata/user/{userId}",
    NodeMetadata,
)
UPSERT_USER_METADATA: Operation[NodeMetadata] = Operation(
    "PUT",
    "/api/metadata/user/{userId}",
    NodeMetadata,
)
GET_NODE_METADATA: Operation[NodeMetadata] = Operation(
    "GET",
    "/api/metadata/node/{uuid}",
    NodeMetadata,
)
UPSERT_NODE_METADATA: Operation[NodeMetadata] = Operation(
    "PUT",
    "/api/metadata/node/{uuid}",
    NodeMetadata,
)


class MetadataApi(SyncGroup):
    def get_user_metadata(self, user_id: int) -> NodeMetadata:
        """Get user metadata."""
        return self._executor.execute(
            GET_USER_METADATA, path={"userId": user_id}
        )

    def upsert_user_metadata(
        self, user_id: int, body: NodeMetadata
    ) -> NodeMetadata:
        """Update or create User Metadata."""
        return self._executor.execute(
            UPSERT_USER_METADATA, path={"userId": user_id}, body=body
        )

    def get_node_metadata(self, uuid: UUID) -> NodeMetadata:
        """Get node metadata."""
        return self._executor.execute(GET_NODE_METADATA, path={"uuid": uuid})

    def upsert_node_metadata(
        self, uuid: UUID, body: NodeMetadata
    ) -> NodeMetadata:
        """Update or create Node Metadata."""
        return self._executor.execute(
            UPSERT_NODE_METADATA, path={"uuid": uuid}, body=body
        )


class AsyncMetadataApi(AsyncGroup):
    async def get_user_metadata(self, user_id: int) -> NodeMetadata:
        """Get user metadata."""
        return await self._executor.execute(
            GET_USER_METADATA, path={"userId": user_id}
        )

    async def upsert_user_metadata(
        self, user_id: int, body: NodeMetadata
    ) -> NodeMetadata:
        """Update or create User Metadata."""
        return await self._executor.execute(
            UPSERT_USER_METADATA, path={"userId": user_id}, body=body
        )

    async def get_node_metadata(self, uuid: UUID) -> NodeMetadata:
        """Get node metadata."""
        return await self._executor.execute(
            GET_NODE_METADATA, path={"uuid": uuid}
        )

    async def upsert_node_metadata(
        self, uuid: UUID, body: NodeMetadata
    ) -> NodeMetadata:
        """Update or create Node Metadata."""
        return await self._executor.execute(
            UPSERT_NODE_METADATA, path={"uuid": uuid}, body=body
        )
