# @generated by tools/codegen -- do not edit
"""Node Plugins Controller."""

from collections.abc import AsyncIterator, Iterator
from typing import Any
from uuid import UUID

from remnawave._generated.models import (
    CloneNodePluginBody,
    NodePlugin,
    NodePlugins,
    PluginExecutorBody,
    QueryFilter,
    QuerySort,
    ReorderNodePluginsBody,
    SyncSnippetBody,
    TorrentBlockerReport,
    TorrentBlockerReportsPage,
    TorrentBlockerReportsStats,
    UpdateNodePluginBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
    Pagination,
)

GET_TORRENT_BLOCKER_REPORTS: Operation[TorrentBlockerReportsPage] = Operation(
    "GET",
    "/api/node-plugins/torrent-blocker",
    TorrentBlockerReportsPage,
    pagination=Pagination(items_field="records", max_page_size=1000),
)
GET_TORRENT_BLOCKER_REPORTS_STATS: Operation[TorrentBlockerReportsStats] = (
    Operation(
        "GET",
        "/api/node-plugins/torrent-blocker/stats",
        TorrentBlockerReportsStats,
    )
)
TRUNCATE_TORRENT_BLOCKER_REPORTS = NoContentOperation(
    "DELETE", "/api/node-plugins/torrent-blocker/truncate"
)
GET_ALL_CONFIGS: Operation[NodePlugins] = Operation(
    "GET",
    "/api/node-plugins",
    NodePlugins,
)
UPDATE_CONFIG: Operation[NodePlugin] = Operation(
    "PATCH",
    "/api/node-plugins",
    NodePlugin,
)
CREATE_CONFIG: Operation[NodePlugin] = Operation(
    "POST",
    "/api/node-plugins",
    NodePlugin,
)
GET_CONFIG_BY_UUID: Operation[NodePlugin] = Operation(
    "GET",
    "/api/node-plugins/{uuid}",
    NodePlugin,
)
DELETE_CONFIG = NoContentOperation("DELETE", "/api/node-plugins/{uuid}")
REORDER_NODE_PLUGINS: Operation[NodePlugins] = Operation(
    "POST",
    "/api/node-plugins/actions/reorder",
    NodePlugins,
)
CLONE_NODE_PLUGIN: Operation[NodePlugin] = Operation(
    "POST",
    "/api/node-plugins/actions/clone",
    NodePlugin,
)
PLUGIN_EXECUTOR = NoContentOperation("POST", "/api/node-plugins/executor")


class NodePluginsApi(SyncGroup):
    def get_torrent_blocker_reports(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> TorrentBlockerReportsPage:
        """Get Torrent Blocker Reports."""
        return self._executor.execute(
            GET_TORRENT_BLOCKER_REPORTS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    def iter_torrent_blocker_reports(
        self,
        page_size: int | None = None,
    ) -> Iterator[TorrentBlockerReport]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_TORRENT_BLOCKER_REPORTS, page_size)

    def get_torrent_blocker_reports_stats(self) -> TorrentBlockerReportsStats:
        """Get Torrent Blocker Reports Stats."""
        return self._executor.execute(GET_TORRENT_BLOCKER_REPORTS_STATS)

    def truncate_torrent_blocker_reports(self) -> None:
        """Truncate Torrent Blocker Reports."""
        return self._executor.execute(TRUNCATE_TORRENT_BLOCKER_REPORTS)

    def get_all_configs(self) -> NodePlugins:
        """Get all Node Plugins."""
        return self._executor.execute(GET_ALL_CONFIGS)

    def update_config(self, body: UpdateNodePluginBody) -> NodePlugin:
        """Update Node Plugin."""
        return self._executor.execute(UPDATE_CONFIG, body=body)

    def create_config(self, body: SyncSnippetBody) -> NodePlugin:
        """Create Node Plugin."""
        return self._executor.execute(CREATE_CONFIG, body=body)

    def get_config_by_uuid(self, uuid: UUID) -> NodePlugin:
        """Get Node Plugin by uuid."""
        return self._executor.execute(GET_CONFIG_BY_UUID, path={"uuid": uuid})

    def delete_config(self, uuid: UUID) -> None:
        """Delete Node Plugin."""
        return self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    def reorder_node_plugins(self, body: ReorderNodePluginsBody) -> NodePlugins:
        """Reorder Node Plugins."""
        return self._executor.execute(REORDER_NODE_PLUGINS, body=body)

    def clone_node_plugin(self, body: CloneNodePluginBody) -> NodePlugin:
        """Clone Node Plugin."""
        return self._executor.execute(CLONE_NODE_PLUGIN, body=body)

    def plugin_executor(self, body: PluginExecutorBody) -> None:
        """Execute command on node plugins."""
        return self._executor.execute(PLUGIN_EXECUTOR, body=body)


class AsyncNodePluginsApi(AsyncGroup):
    async def get_torrent_blocker_reports(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> TorrentBlockerReportsPage:
        """Get Torrent Blocker Reports."""
        return await self._executor.execute(
            GET_TORRENT_BLOCKER_REPORTS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    async def iter_torrent_blocker_reports(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[TorrentBlockerReport]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(
            GET_TORRENT_BLOCKER_REPORTS, page_size
        ):
            yield item

    async def get_torrent_blocker_reports_stats(
        self,
    ) -> TorrentBlockerReportsStats:
        """Get Torrent Blocker Reports Stats."""
        return await self._executor.execute(GET_TORRENT_BLOCKER_REPORTS_STATS)

    async def truncate_torrent_blocker_reports(self) -> None:
        """Truncate Torrent Blocker Reports."""
        return await self._executor.execute(TRUNCATE_TORRENT_BLOCKER_REPORTS)

    async def get_all_configs(self) -> NodePlugins:
        """Get all Node Plugins."""
        return await self._executor.execute(GET_ALL_CONFIGS)

    async def update_config(self, body: UpdateNodePluginBody) -> NodePlugin:
        """Update Node Plugin."""
        return await self._executor.execute(UPDATE_CONFIG, body=body)

    async def create_config(self, body: SyncSnippetBody) -> NodePlugin:
        """Create Node Plugin."""
        return await self._executor.execute(CREATE_CONFIG, body=body)

    async def get_config_by_uuid(self, uuid: UUID) -> NodePlugin:
        """Get Node Plugin by uuid."""
        return await self._executor.execute(
            GET_CONFIG_BY_UUID, path={"uuid": uuid}
        )

    async def delete_config(self, uuid: UUID) -> None:
        """Delete Node Plugin."""
        return await self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    async def reorder_node_plugins(
        self, body: ReorderNodePluginsBody
    ) -> NodePlugins:
        """Reorder Node Plugins."""
        return await self._executor.execute(REORDER_NODE_PLUGINS, body=body)

    async def clone_node_plugin(self, body: CloneNodePluginBody) -> NodePlugin:
        """Clone Node Plugin."""
        return await self._executor.execute(CLONE_NODE_PLUGIN, body=body)

    async def plugin_executor(self, body: PluginExecutorBody) -> None:
        """Execute command on node plugins."""
        return await self._executor.execute(PLUGIN_EXECUTOR, body=body)
