# @generated by tools/codegen -- do not edit
"""Nodes Controller."""

from uuid import UUID

from remnawave._generated.models import (
    BulkNodesActionsBody,
    BulkNodesUpdateBody,
    CreateNodeBody,
    HostsTags,
    Node,
    ProfileModificationBody,
    ReorderNodesBody,
    RestartNodeBody,
    UpdateNodeBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_NODES_TAGS: Operation[HostsTags] = Operation(
    "GET",
    "/api/nodes/tags",
    HostsTags,
)
CREATE_NODE: Operation[Node] = Operation(
    "POST",
    "/api/nodes",
    Node,
)
GET_NODES: Operation[list[Node]] = Operation(
    "GET",
    "/api/nodes",
    list[Node],
)
UPDATE_NODE: Operation[Node] = Operation(
    "PATCH",
    "/api/nodes",
    Node,
)
GET_NODE: Operation[Node] = Operation(
    "GET",
    "/api/nodes/{uuid}",
    Node,
)
DELETE_NODE = NoContentOperation("DELETE", "/api/nodes/{uuid}")
ENABLE_NODE: Operation[Node] = Operation(
    "POST",
    "/api/nodes/{uuid}/actions/enable",
    Node,
)
DISABLE_NODE: Operation[Node] = Operation(
    "POST",
    "/api/nodes/{uuid}/actions/disable",
    Node,
)
RESTART_NODE = NoContentOperation("POST", "/api/nodes/{uuid}/actions/restart")
RESET_NODE_TRAFFIC = NoContentOperation(
    "POST", "/api/nodes/{uuid}/actions/reset-traffic"
)
RESTART_ALL_NODES = NoContentOperation("POST", "/api/nodes/actions/restart-all")
REORDER_NODES: Operation[list[Node]] = Operation(
    "POST",
    "/api/nodes/actions/reorder",
    list[Node],
)
PROFILE_MODIFICATION = NoContentOperation(
    "POST", "/api/nodes/bulk-actions/profile-modification"
)
BULK_NODES_ACTIONS = NoContentOperation("POST", "/api/nodes/bulk-actions")
BULK_NODES_UPDATE = NoContentOperation("POST", "/api/nodes/bulk-actions/update")


class NodesApi(SyncGroup):
    def get_nodes_tags(self) -> HostsTags:
        """Get nodes tags."""
        return self._executor.execute(GET_NODES_TAGS)

    def create_node(self, body: CreateNodeBody) -> Node:
        """Create a new node."""
        return self._executor.execute(CREATE_NODE, body=body)

    def get_nodes(self) -> list[Node]:
        """Get nodes."""
        return self._executor.execute(GET_NODES)

    def update_node(self, body: UpdateNodeBody) -> Node:
        """Update node."""
        return self._executor.execute(UPDATE_NODE, body=body)

    def get_node(self, uuid: UUID) -> Node:
        """Get node by UUID."""
        return self._executor.execute(GET_NODE, path={"uuid": uuid})

    def delete_node(self, uuid: UUID) -> None:
        """Delete a node."""
        return self._executor.execute(DELETE_NODE, path={"uuid": uuid})

    def enable_node(self, uuid: UUID) -> Node:
        """Enable a node."""
        return self._executor.execute(ENABLE_NODE, path={"uuid": uuid})

    def disable_node(self, uuid: UUID) -> Node:
        """Disable a node."""
        return self._executor.execute(DISABLE_NODE, path={"uuid": uuid})

    def restart_node(self, uuid: UUID, body: RestartNodeBody) -> None:
        """Restart node."""
        return self._executor.execute(
            RESTART_NODE, path={"uuid": uuid}, body=body
        )

    def reset_node_traffic(self, uuid: UUID) -> None:
        """Reset Node Traffic."""
        return self._executor.execute(RESET_NODE_TRAFFIC, path={"uuid": uuid})

    def restart_all_nodes(self, body: RestartNodeBody) -> None:
        """Restart all nodes."""
        return self._executor.execute(RESTART_ALL_NODES, body=body)

    def reorder_nodes(self, body: ReorderNodesBody) -> list[Node]:
        """Reorder nodes."""
        return self._executor.execute(REORDER_NODES, body=body)

    def profile_modification(self, body: ProfileModificationBody) -> None:
        """Modify Inbounds & Profile for many nodes."""
        return self._executor.execute(PROFILE_MODIFICATION, body=body)

    def bulk_nodes_actions(self, body: BulkNodesActionsBody) -> None:
        """Perform actions for many nodes."""
        return self._executor.execute(BULK_NODES_ACTIONS, body=body)

    def bulk_nodes_update(self, body: BulkNodesUpdateBody) -> None:
        """Update many nodes."""
        return self._executor.execute(BULK_NODES_UPDATE, body=body)


class AsyncNodesApi(AsyncGroup):
    async def get_nodes_tags(self) -> HostsTags:
        """Get nodes tags."""
        return await self._executor.execute(GET_NODES_TAGS)

    async def create_node(self, body: CreateNodeBody) -> Node:
        """Create a new node."""
        return await self._executor.execute(CREATE_NODE, body=body)

    async def get_nodes(self) -> list[Node]:
        """Get nodes."""
        return await self._executor.execute(GET_NODES)

    async def update_node(self, body: UpdateNodeBody) -> Node:
        """Update node."""
        return await self._executor.execute(UPDATE_NODE, body=body)

    async def get_node(self, uuid: UUID) -> Node:
        """Get node by UUID."""
        return await self._executor.execute(GET_NODE, path={"uuid": uuid})

    async def delete_node(self, uuid: UUID) -> None:
        """Delete a node."""
        return await self._executor.execute(DELETE_NODE, path={"uuid": uuid})

    async def enable_node(self, uuid: UUID) -> Node:
        """Enable a node."""
        return await self._executor.execute(ENABLE_NODE, path={"uuid": uuid})

    async def disable_node(self, uuid: UUID) -> Node:
        """Disable a node."""
        return await self._executor.execute(DISABLE_NODE, path={"uuid": uuid})

    async def restart_node(self, uuid: UUID, body: RestartNodeBody) -> None:
        """Restart node."""
        return await self._executor.execute(
            RESTART_NODE, path={"uuid": uuid}, body=body
        )

    async def reset_node_traffic(self, uuid: UUID) -> None:
        """Reset Node Traffic."""
        return await self._executor.execute(
            RESET_NODE_TRAFFIC, path={"uuid": uuid}
        )

    async def restart_all_nodes(self, body: RestartNodeBody) -> None:
        """Restart all nodes."""
        return await self._executor.execute(RESTART_ALL_NODES, body=body)

    async def reorder_nodes(self, body: ReorderNodesBody) -> list[Node]:
        """Reorder nodes."""
        return await self._executor.execute(REORDER_NODES, body=body)

    async def profile_modification(self, body: ProfileModificationBody) -> None:
        """Modify Inbounds & Profile for many nodes."""
        return await self._executor.execute(PROFILE_MODIFICATION, body=body)

    async def bulk_nodes_actions(self, body: BulkNodesActionsBody) -> None:
        """Perform actions for many nodes."""
        return await self._executor.execute(BULK_NODES_ACTIONS, body=body)

    async def bulk_nodes_update(self, body: BulkNodesUpdateBody) -> None:
        """Update many nodes."""
        return await self._executor.execute(BULK_NODES_UPDATE, body=body)
