# @generated by tools/codegen -- do not edit
"""Nodes Controller."""

from remnawave._generated.models import (
    CreateNodeRequest,
    Host,
    Node,
    Node2,
    ReorderNodeRequest,
    RestartAllNodesRequestBody,
    UpdateNodeRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

CREATE_NODE: Operation[Node2] = Operation(
    "POST",
    "/api/nodes",
    Node2,
)
GET_ALL_NODES: Operation[list[Node2]] = Operation(
    "GET",
    "/api/nodes",
    list[Node2],
)
UPDATE_NODE: Operation[Node2] = Operation(
    "PATCH",
    "/api/nodes",
    Node2,
)
GET_ONE_NODE: Operation[Node2] = Operation(
    "GET",
    "/api/nodes/{uuid}",
    Node2,
)
DELETE_NODE: Operation[Host] = Operation(
    "DELETE",
    "/api/nodes/{uuid}",
    Host,
)
ENABLE_NODE: Operation[Node2] = Operation(
    "POST",
    "/api/nodes/{uuid}/actions/enable",
    Node2,
)
DISABLE_NODE: Operation[Node2] = Operation(
    "POST",
    "/api/nodes/{uuid}/actions/disable",
    Node2,
)
RESTART_NODE: Operation[Node] = Operation(
    "POST",
    "/api/nodes/{uuid}/actions/restart",
    Node,
)
RESTART_ALL_NODES: Operation[Node] = Operation(
    "POST",
    "/api/nodes/actions/restart-all",
    Node,
)
REORDER_NODES: Operation[list[Node2]] = Operation(
    "POST",
    "/api/nodes/actions/reorder",
    list[Node2],
)


class NodesApi(SyncGroup):
    def create_node(self, body: CreateNodeRequest) -> Node2:
        """Create a new node."""
        return self._executor.execute(CREATE_NODE, body=body)

    def get_all_nodes(self) -> list[Node2]:
        """Get all nodes."""
        return self._executor.execute(GET_ALL_NODES)

    def update_node(self, body: UpdateNodeRequest) -> Node2:
        """Update node."""
        return self._executor.execute(UPDATE_NODE, body=body)

    def get_one_node(self, uuid: str) -> Node2:
        """Get node by UUID."""
        return self._executor.execute(GET_ONE_NODE, path={"uuid": uuid})

    def delete_node(self, uuid: str) -> Host:
        """Delete a node."""
        return self._executor.execute(DELETE_NODE, path={"uuid": uuid})

    def enable_node(self, uuid: str) -> Node2:
        """Enable a node."""
        return self._executor.execute(ENABLE_NODE, path={"uuid": uuid})

    def disable_node(self, uuid: str) -> Node2:
        """Disable a node."""
        return self._executor.execute(DISABLE_NODE, path={"uuid": uuid})

    def restart_node(self, uuid: str) -> Node:
        """Restart node."""
        return self._executor.execute(RESTART_NODE, path={"uuid": uuid})

    def restart_all_nodes(self, body: RestartAllNodesRequestBody) -> Node:
        """Restart all nodes."""
        return self._executor.execute(RESTART_ALL_NODES, body=body)

    def reorder_nodes(self, body: ReorderNodeRequest) -> list[Node2]:
        """Reorder nodes."""
        return self._executor.execute(REORDER_NODES, body=body)


class AsyncNodesApi(AsyncGroup):
    async def create_node(self, body: CreateNodeRequest) -> Node2:
        """Create a new node."""
        return await self._executor.execute(CREATE_NODE, body=body)

    async def get_all_nodes(self) -> list[Node2]:
        """Get all nodes."""
        return await self._executor.execute(GET_ALL_NODES)

    async def update_node(self, body: UpdateNodeRequest) -> Node2:
        """Update node."""
        return await self._executor.execute(UPDATE_NODE, body=body)

    async def get_one_node(self, uuid: str) -> Node2:
        """Get node by UUID."""
        return await self._executor.execute(GET_ONE_NODE, path={"uuid": uuid})

    async def delete_node(self, uuid: str) -> Host:
        """Delete a node."""
        return await self._executor.execute(DELETE_NODE, path={"uuid": uuid})

    async def enable_node(self, uuid: str) -> Node2:
        """Enable a node."""
        return await self._executor.execute(ENABLE_NODE, path={"uuid": uuid})

    async def disable_node(self, uuid: str) -> Node2:
        """Disable a node."""
        return await self._executor.execute(DISABLE_NODE, path={"uuid": uuid})

    async def restart_node(self, uuid: str) -> Node:
        """Restart node."""
        return await self._executor.execute(RESTART_NODE, path={"uuid": uuid})

    async def restart_all_nodes(self, body: RestartAllNodesRequestBody) -> Node:
        """Restart all nodes."""
        return await self._executor.execute(RESTART_ALL_NODES, body=body)

    async def reorder_nodes(self, body: ReorderNodeRequest) -> list[Node2]:
        """Reorder nodes."""
        return await self._executor.execute(REORDER_NODES, body=body)
