# @generated by tools/codegen -- do not edit
"""Node Integrations Controller."""

from uuid import UUID

from remnawave._generated.models import (
    CreateNodeIntegrationBody,
    NodeIntegration,
    NodeIntegrations,
    UpdateNodeIntegrationBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_ALL_INTEGRATIONS: Operation[NodeIntegrations] = Operation(
    "GET",
    "/api/node-integrations",
    NodeIntegrations,
)
CREATE_INTEGRATION: Operation[NodeIntegration] = Operation(
    "POST",
    "/api/node-integrations",
    NodeIntegration,
)
UPDATE_INTEGRATION: Operation[NodeIntegration] = Operation(
    "PATCH",
    "/api/node-integrations",
    NodeIntegration,
)
GET_INTEGRATION_BY_UUID: Operation[NodeIntegration] = Operation(
    "GET",
    "/api/node-integrations/{uuid}",
    NodeIntegration,
)
DELETE_INTEGRATION = NoContentOperation(
    "DELETE", "/api/node-integrations/{uuid}"
)


class NodeIntegrationsApi(SyncGroup):
    def get_all_integrations(self) -> NodeIntegrations:
        """Get all Node Integrations."""
        return self._executor.execute(GET_ALL_INTEGRATIONS)

    def create_integration(
        self, body: CreateNodeIntegrationBody
    ) -> NodeIntegration:
        """Create Node Integration."""
        return self._executor.execute(CREATE_INTEGRATION, body=body)

    def update_integration(
        self, body: UpdateNodeIntegrationBody
    ) -> NodeIntegration:
        """Update Node Integration."""
        return self._executor.execute(UPDATE_INTEGRATION, body=body)

    def get_integration_by_uuid(self, uuid: UUID) -> NodeIntegration:
        """Get Node Integration by uuid."""
        return self._executor.execute(
            GET_INTEGRATION_BY_UUID, path={"uuid": uuid}
        )

    def delete_integration(self, uuid: UUID) -> None:
        """Delete Node Integration."""
        return self._executor.execute(DELETE_INTEGRATION, path={"uuid": uuid})


class AsyncNodeIntegrationsApi(AsyncGroup):
    async def get_all_integrations(self) -> NodeIntegrations:
        """Get all Node Integrations."""
        return await self._executor.execute(GET_ALL_INTEGRATIONS)

    async def create_integration(
        self, body: CreateNodeIntegrationBody
    ) -> NodeIntegration:
        """Create Node Integration."""
        return await self._executor.execute(CREATE_INTEGRATION, body=body)

    async def update_integration(
        self, body: UpdateNodeIntegrationBody
    ) -> NodeIntegration:
        """Update Node Integration."""
        return await self._executor.execute(UPDATE_INTEGRATION, body=body)

    async def get_integration_by_uuid(self, uuid: UUID) -> NodeIntegration:
        """Get Node Integration by uuid."""
        return await self._executor.execute(
            GET_INTEGRATION_BY_UUID, path={"uuid": uuid}
        )

    async def delete_integration(self, uuid: UUID) -> None:
        """Delete Node Integration."""
        return await self._executor.execute(
            DELETE_INTEGRATION, path={"uuid": uuid}
        )
