# @generated by tools/codegen -- do not edit
"""Passkeys Controller."""

from typing import Any

from remnawave._generated.models import (
    DeletePasskeyRequest,
    Passkey,
    VerifyPasskeyRegistration,
    VerifyPasskeyRegistrationRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

PASSKEY_REGISTRATION_OPTIONS: Operation[Any] = Operation(
    "GET",
    "/api/passkeys/registration/options",
    Any,
)
PASSKEY_REGISTRATION_VERIFY: Operation[VerifyPasskeyRegistration] = Operation(
    "POST",
    "/api/passkeys/registration/verify",
    VerifyPasskeyRegistration,
)
GET_ACTIVE_PASSKEYS: Operation[Passkey] = Operation(
    "GET",
    "/api/passkeys",
    Passkey,
)
DELETE_PASSKEY: Operation[Passkey] = Operation(
    "DELETE",
    "/api/passkeys",
    Passkey,
)


class PasskeysApi(SyncGroup):
    def passkey_registration_options(self) -> Any:
        """Get registration options for passkey."""
        return self._executor.execute(PASSKEY_REGISTRATION_OPTIONS)

    def passkey_registration_verify(
        self, body: VerifyPasskeyRegistrationRequest
    ) -> VerifyPasskeyRegistration:
        """Verify registration for passkey."""
        return self._executor.execute(PASSKEY_REGISTRATION_VERIFY, body=body)

    def get_active_passkeys(self) -> Passkey:
        """Get all passkeys."""
        return self._executor.execute(GET_ACTIVE_PASSKEYS)

    def delete_passkey(self, body: DeletePasskeyRequest) -> Passkey:
        """Delete a passkey by ID."""
        return self._executor.execute(DELETE_PASSKEY, body=body)


class AsyncPasskeysApi(AsyncGroup):
    async def passkey_registration_options(self) -> Any:
        """Get registration options for passkey."""
        return await self._executor.execute(PASSKEY_REGISTRATION_OPTIONS)

    async def passkey_registration_verify(
        self, body: VerifyPasskeyRegistrationRequest
    ) -> VerifyPasskeyRegistration:
        """Verify registration for passkey."""
        return await self._executor.execute(
            PASSKEY_REGISTRATION_VERIFY, body=body
        )

    async def get_active_passkeys(self) -> Passkey:
        """Get all passkeys."""
        return await self._executor.execute(GET_ACTIVE_PASSKEYS)

    async def delete_passkey(self, body: DeletePasskeyRequest) -> Passkey:
        """Delete a passkey by ID."""
        return await self._executor.execute(DELETE_PASSKEY, body=body)
