# @generated by tools/codegen -- do not edit
"""Remnawave Settings Controller."""

from remnawave._generated.models import (
    RemnawaveSettings,
    UpdateRemnawaveSettingsRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_SETTINGS: Operation[RemnawaveSettings] = Operation(
    "GET",
    "/api/remnawave-settings",
    RemnawaveSettings,
)
UPDATE_SETTINGS: Operation[RemnawaveSettings] = Operation(
    "PATCH",
    "/api/remnawave-settings",
    RemnawaveSettings,
)


class RemnawaveSettingsApi(SyncGroup):
    def get_settings(self) -> RemnawaveSettings:
        """Get Remnawave settings."""
        return self._executor.execute(GET_SETTINGS)

    def update_settings(
        self, body: UpdateRemnawaveSettingsRequest
    ) -> RemnawaveSettings:
        """Update Remnawave settings."""
        return self._executor.execute(UPDATE_SETTINGS, body=body)


class AsyncRemnawaveSettingsApi(AsyncGroup):
    async def get_settings(self) -> RemnawaveSettings:
        """Get Remnawave settings."""
        return await self._executor.execute(GET_SETTINGS)

    async def update_settings(
        self, body: UpdateRemnawaveSettingsRequest
    ) -> RemnawaveSettings:
        """Update Remnawave settings."""
        return await self._executor.execute(UPDATE_SETTINGS, body=body)
