# @generated by tools/codegen -- do not edit
"""Snippets Controller."""

from remnawave._generated.models import (
    CreateSnippetRequest,
    DeleteSnippetRequest,
    Snippet,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_SNIPPETS: Operation[Snippet] = Operation(
    "GET",
    "/api/snippets",
    Snippet,
)
DELETE_SNIPPET_BY_NAME: Operation[Snippet] = Operation(
    "DELETE",
    "/api/snippets",
    Snippet,
)
CREATE_SNIPPET: Operation[Snippet] = Operation(
    "POST",
    "/api/snippets",
    Snippet,
)
UPDATE_SNIPPET: Operation[Snippet] = Operation(
    "PATCH",
    "/api/snippets",
    Snippet,
)


class SnippetsApi(SyncGroup):
    def get_snippets(self) -> Snippet:
        """Get snippets."""
        return self._executor.execute(GET_SNIPPETS)

    def delete_snippet_by_name(self, body: DeleteSnippetRequest) -> Snippet:
        """Delete snippet."""
        return self._executor.execute(DELETE_SNIPPET_BY_NAME, body=body)

    def create_snippet(self, body: CreateSnippetRequest) -> Snippet:
        """Create snippet."""
        return self._executor.execute(CREATE_SNIPPET, body=body)

    def update_snippet(self, body: CreateSnippetRequest) -> Snippet:
        """Update snippet."""
        return self._executor.execute(UPDATE_SNIPPET, body=body)


class AsyncSnippetsApi(AsyncGroup):
    async def get_snippets(self) -> Snippet:
        """Get snippets."""
        return await self._executor.execute(GET_SNIPPETS)

    async def delete_snippet_by_name(
        self, body: DeleteSnippetRequest
    ) -> Snippet:
        """Delete snippet."""
        return await self._executor.execute(DELETE_SNIPPET_BY_NAME, body=body)

    async def create_snippet(self, body: CreateSnippetRequest) -> Snippet:
        """Create snippet."""
        return await self._executor.execute(CREATE_SNIPPET, body=body)

    async def update_snippet(self, body: CreateSnippetRequest) -> Snippet:
        """Update snippet."""
        return await self._executor.execute(UPDATE_SNIPPET, body=body)
