# @generated by tools/codegen -- do not edit
"""Subscription Page Configs Controller."""

from uuid import UUID

from remnawave._generated.models import (
    CloneNodePluginBody,
    DeleteSnippetBody,
    ReorderNodePluginsBody,
    SubpageConfig,
    SubpageConfigs,
    UpdateSubpageConfigBody,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
)

GET_ALL_CONFIGS: Operation[SubpageConfigs] = Operation(
    "GET",
    "/api/subscription-page-configs",
    SubpageConfigs,
)
UPDATE_CONFIG: Operation[SubpageConfig] = Operation(
    "PATCH",
    "/api/subscription-page-configs",
    SubpageConfig,
)
CREATE_CONFIG: Operation[SubpageConfig] = Operation(
    "POST",
    "/api/subscription-page-configs",
    SubpageConfig,
)
GET_CONFIG_BY_UUID: Operation[SubpageConfig] = Operation(
    "GET",
    "/api/subscription-page-configs/{uuid}",
    SubpageConfig,
)
DELETE_CONFIG = NoContentOperation(
    "DELETE", "/api/subscription-page-configs/{uuid}"
)
REORDER_SUBSCRIPTION_PAGE_CONFIGS: Operation[SubpageConfigs] = Operation(
    "POST",
    "/api/subscription-page-configs/actions/reorder",
    SubpageConfigs,
)
CLONE_SUBSCRIPTION_PAGE_CONFIG: Operation[SubpageConfig] = Operation(
    "POST",
    "/api/subscription-page-configs/actions/clone",
    SubpageConfig,
)


class SubscriptionPageConfigsApi(SyncGroup):
    def get_all_configs(self) -> SubpageConfigs:
        """Get all subscription page configs."""
        return self._executor.execute(GET_ALL_CONFIGS)

    def update_config(self, body: UpdateSubpageConfigBody) -> SubpageConfig:
        """Update subscription page config."""
        return self._executor.execute(UPDATE_CONFIG, body=body)

    def create_config(self, body: DeleteSnippetBody) -> SubpageConfig:
        """Create subscription page config."""
        return self._executor.execute(CREATE_CONFIG, body=body)

    def get_config_by_uuid(self, uuid: UUID) -> SubpageConfig:
        """Get subscription page config by uuid."""
        return self._executor.execute(GET_CONFIG_BY_UUID, path={"uuid": uuid})

    def delete_config(self, uuid: UUID) -> None:
        """Delete subscription page config."""
        return self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    def reorder_subscription_page_configs(
        self, body: ReorderNodePluginsBody
    ) -> SubpageConfigs:
        """Reorder subscription page configs."""
        return self._executor.execute(
            REORDER_SUBSCRIPTION_PAGE_CONFIGS, body=body
        )

    def clone_subscription_page_config(
        self, body: CloneNodePluginBody
    ) -> SubpageConfig:
        """Clone subscription page config."""
        return self._executor.execute(CLONE_SUBSCRIPTION_PAGE_CONFIG, body=body)


class AsyncSubscriptionPageConfigsApi(AsyncGroup):
    async def get_all_configs(self) -> SubpageConfigs:
        """Get all subscription page configs."""
        return await self._executor.execute(GET_ALL_CONFIGS)

    async def update_config(
        self, body: UpdateSubpageConfigBody
    ) -> SubpageConfig:
        """Update subscription page config."""
        return await self._executor.execute(UPDATE_CONFIG, body=body)

    async def create_config(self, body: DeleteSnippetBody) -> SubpageConfig:
        """Create subscription page config."""
        return await self._executor.execute(CREATE_CONFIG, body=body)

    async def get_config_by_uuid(self, uuid: UUID) -> SubpageConfig:
        """Get subscription page config by uuid."""
        return await self._executor.execute(
            GET_CONFIG_BY_UUID, path={"uuid": uuid}
        )

    async def delete_config(self, uuid: UUID) -> None:
        """Delete subscription page config."""
        return await self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    async def reorder_subscription_page_configs(
        self, body: ReorderNodePluginsBody
    ) -> SubpageConfigs:
        """Reorder subscription page configs."""
        return await self._executor.execute(
            REORDER_SUBSCRIPTION_PAGE_CONFIGS, body=body
        )

    async def clone_subscription_page_config(
        self, body: CloneNodePluginBody
    ) -> SubpageConfig:
        """Clone subscription page config."""
        return await self._executor.execute(
            CLONE_SUBSCRIPTION_PAGE_CONFIG, body=body
        )
