# @generated by tools/codegen -- do not edit
"""[Public] Subscription Controller."""

from remnawave._generated.enums import (
    SubscriptionControllerGetSubscriptionByClientType,
)
from remnawave._generated.models import (
    Subscription,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    RawOperation,
)

GET_SUBSCRIPTION_INFO_BY_SHORT_UUID: Operation[Subscription] = Operation(
    "GET",
    "/api/sub/{shortUuid}/info",
    Subscription,
)
GET_SUBSCRIPTION = RawOperation("GET", "/api/sub/{shortUuid}")
GET_SUBSCRIPTION_BY_CLIENT_TYPE = RawOperation(
    "GET", "/api/sub/{shortUuid}/{clientType}"
)


class SubscriptionApi(SyncGroup):
    def get_subscription_info_by_short_uuid(
        self, short_uuid: str
    ) -> Subscription:
        """Get Subscription Info by Short UUID."""
        return self._executor.execute(
            GET_SUBSCRIPTION_INFO_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    def get_subscription(self, short_uuid: str) -> bytes:
        return self._executor.execute(
            GET_SUBSCRIPTION, path={"shortUuid": short_uuid}
        )

    def get_subscription_by_client_type(
        self,
        short_uuid: str,
        client_type: SubscriptionControllerGetSubscriptionByClientType,
    ) -> bytes:
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_CLIENT_TYPE,
            path={"shortUuid": short_uuid, "clientType": client_type},
        )


class AsyncSubscriptionApi(AsyncGroup):
    async def get_subscription_info_by_short_uuid(
        self, short_uuid: str
    ) -> Subscription:
        """Get Subscription Info by Short UUID."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_INFO_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    async def get_subscription(self, short_uuid: str) -> bytes:
        return await self._executor.execute(
            GET_SUBSCRIPTION, path={"shortUuid": short_uuid}
        )

    async def get_subscription_by_client_type(
        self,
        short_uuid: str,
        client_type: SubscriptionControllerGetSubscriptionByClientType,
    ) -> bytes:
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_CLIENT_TYPE,
            path={"shortUuid": short_uuid, "clientType": client_type},
        )
