# @generated by tools/codegen -- do not edit
"""[Protected] Subscriptions Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    RawSubscriptionByShortUuid,
    Subscription,
    SubscriptionInfo,
    SubscriptionsPage,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_ALL_SUBSCRIPTIONS: Operation[SubscriptionsPage] = Operation(
    "GET",
    "/api/subscriptions",
    SubscriptionsPage,
    pagination=Pagination(items_field="subscriptions", max_page_size=100),
)
GET_SUBSCRIPTION_BY_USERNAME: Operation[SubscriptionInfo] = Operation(
    "GET",
    "/api/subscriptions/by-username/{username}",
    SubscriptionInfo,
)
GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED: Operation[SubscriptionInfo] = (
    Operation(
        "GET",
        "/api/subscriptions/by-short-uuid/{shortUuid}",
        SubscriptionInfo,
    )
)
GET_SUBSCRIPTION_BY_UUID: Operation[SubscriptionInfo] = Operation(
    "GET",
    "/api/subscriptions/by-uuid/{uuid}",
    SubscriptionInfo,
)
GET_RAW_SUBSCRIPTION_BY_SHORT_UUID: Operation[RawSubscriptionByShortUuid] = (
    Operation(
        "GET",
        "/api/subscriptions/by-short-uuid/{shortUuid}/raw",
        RawSubscriptionByShortUuid,
    )
)


class SubscriptionsApi(SyncGroup):
    def get_all_subscriptions(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"size": size, "start": start}
        )

    def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> Iterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_SUBSCRIPTIONS, page_size)

    def get_subscription_by_username(self, username: str) -> SubscriptionInfo:
        """Get subscription by username."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )

    def get_subscription_by_short_uuid_protected(
        self, short_uuid: str
    ) -> SubscriptionInfo:
        """Get subscription by short uuid (protected route)."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED,
            path={"shortUuid": short_uuid},
        )

    def get_subscription_by_uuid(self, uuid: str) -> SubscriptionInfo:
        """Get subscription by uuid."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_UUID, path={"uuid": uuid}
        )

    def get_raw_subscription_by_short_uuid(
        self, short_uuid: str, *, with_disabled_hosts: bool | None = None
    ) -> RawSubscriptionByShortUuid:
        """Get Raw Subscription by Short UUID."""
        return self._executor.execute(
            GET_RAW_SUBSCRIPTION_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            query={"withDisabledHosts": with_disabled_hosts},
        )


class AsyncSubscriptionsApi(AsyncGroup):
    async def get_all_subscriptions(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return await self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"size": size, "start": start}
        )

    async def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_SUBSCRIPTIONS, page_size):
            yield item

    async def get_subscription_by_username(
        self, username: str
    ) -> SubscriptionInfo:
        """Get subscription by username."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )

    async def get_subscription_by_short_uuid_protected(
        self, short_uuid: str
    ) -> SubscriptionInfo:
        """Get subscription by short uuid (protected route)."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED,
            path={"shortUuid": short_uuid},
        )

    async def get_subscription_by_uuid(self, uuid: str) -> SubscriptionInfo:
        """Get subscription by uuid."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_UUID, path={"uuid": uuid}
        )

    async def get_raw_subscription_by_short_uuid(
        self, short_uuid: str, *, with_disabled_hosts: bool | None = None
    ) -> RawSubscriptionByShortUuid:
        """Get Raw Subscription by Short UUID."""
        return await self._executor.execute(
            GET_RAW_SUBSCRIPTION_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            query={"withDisabledHosts": with_disabled_hosts},
        )
