# @generated by tools/codegen -- do not edit
"""Subscription Request History Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    SubscriptionRequestHistoryStats,
    SubscriptionRequestsPage,
    TorrentBlockerReport,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_SUBSCRIPTION_REQUEST_HISTORY: Operation[SubscriptionRequestsPage] = (
    Operation(
        "GET",
        "/api/subscription-request-history",
        SubscriptionRequestsPage,
        pagination=Pagination(items_field="records", max_page_size=100),
    )
)
GET_SUBSCRIPTION_REQUEST_HISTORY_STATS: Operation[
    SubscriptionRequestHistoryStats
] = Operation(
    "GET",
    "/api/subscription-request-history/stats",
    SubscriptionRequestHistoryStats,
)


class SubscriptionRequestHistoryApi(SyncGroup):
    def get_subscription_request_history(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionRequestsPage:
        """Get all subscription request history."""
        return self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY,
            query={"size": size, "start": start},
        )

    def iter_subscription_request_history(
        self,
        page_size: int | None = None,
    ) -> Iterator[TorrentBlockerReport]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_SUBSCRIPTION_REQUEST_HISTORY, page_size)

    def get_subscription_request_history_stats(
        self,
    ) -> SubscriptionRequestHistoryStats:
        """Get subscription request history stats."""
        return self._executor.execute(GET_SUBSCRIPTION_REQUEST_HISTORY_STATS)


class AsyncSubscriptionRequestHistoryApi(AsyncGroup):
    async def get_subscription_request_history(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionRequestsPage:
        """Get all subscription request history."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY,
            query={"size": size, "start": start},
        )

    async def iter_subscription_request_history(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[TorrentBlockerReport]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(
            GET_SUBSCRIPTION_REQUEST_HISTORY, page_size
        ):
            yield item

    async def get_subscription_request_history_stats(
        self,
    ) -> SubscriptionRequestHistoryStats:
        """Get subscription request history stats."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY_STATS
        )
