# @generated by tools/codegen -- do not edit
"""Subscription Request History Controller."""

from collections.abc import AsyncIterator, Iterator
from typing import Any

from remnawave._generated.models import (
    QueryFilter,
    QuerySort,
    SubscriptionRequest,
    SubscriptionRequestHistoryStats,
    SubscriptionRequestsPage,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_SUBSCRIPTION_REQUEST_HISTORY: Operation[SubscriptionRequestsPage] = (
    Operation(
        "GET",
        "/api/subscription-request-history",
        SubscriptionRequestsPage,
        pagination=Pagination(items_field="records", max_page_size=1000),
    )
)
GET_SUBSCRIPTION_REQUEST_HISTORY_STATS: Operation[
    SubscriptionRequestHistoryStats
] = Operation(
    "GET",
    "/api/subscription-request-history/stats",
    SubscriptionRequestHistoryStats,
)


class SubscriptionRequestHistoryApi(SyncGroup):
    def get_subscription_request_history(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> SubscriptionRequestsPage:
        """Get all subscription request history."""
        return self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    def iter_subscription_request_history(
        self,
        page_size: int | None = None,
    ) -> Iterator[SubscriptionRequest]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_SUBSCRIPTION_REQUEST_HISTORY, page_size)

    def get_subscription_request_history_stats(
        self,
    ) -> SubscriptionRequestHistoryStats:
        """Get subscription request history stats."""
        return self._executor.execute(GET_SUBSCRIPTION_REQUEST_HISTORY_STATS)


class AsyncSubscriptionRequestHistoryApi(AsyncGroup):
    async def get_subscription_request_history(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> SubscriptionRequestsPage:
        """Get all subscription request history."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    async def iter_subscription_request_history(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[SubscriptionRequest]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(
            GET_SUBSCRIPTION_REQUEST_HISTORY, page_size
        ):
            yield item

    async def get_subscription_request_history_stats(
        self,
    ) -> SubscriptionRequestHistoryStats:
        """Get subscription request history stats."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_REQUEST_HISTORY_STATS
        )
