# @generated by tools/codegen -- do not edit
"""[Protected] Subscriptions Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    ConnectionKeysByUserId,
    GetSubpageConfigByShortUuidBody,
    RawSubscriptionByShortUuid,
    SubpageConfigByShortUuid,
    Subscription,
    SubscriptionsPage,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_ALL_SUBSCRIPTIONS: Operation[SubscriptionsPage] = Operation(
    "GET",
    "/api/subscriptions",
    SubscriptionsPage,
    pagination=Pagination(items_field="subscriptions", max_page_size=500),
)
GET_SUBSCRIPTION_BY_USERNAME: Operation[Subscription] = Operation(
    "GET",
    "/api/subscriptions/by-username/{username}",
    Subscription,
)
GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED: Operation[Subscription] = Operation(
    "GET",
    "/api/subscriptions/by-short-uuid/{shortUuid}",
    Subscription,
)
GET_SUBSCRIPTION_BY_UUID: Operation[Subscription] = Operation(
    "GET",
    "/api/subscriptions/by-id/{userId}",
    Subscription,
)
GET_RAW_SUBSCRIPTION_BY_SHORT_UUID: Operation[RawSubscriptionByShortUuid] = (
    Operation(
        "GET",
        "/api/subscriptions/by-short-uuid/{shortUuid}/raw",
        RawSubscriptionByShortUuid,
    )
)
GET_SUBPAGE_CONFIG_BY_SHORT_UUID: Operation[SubpageConfigByShortUuid] = (
    Operation(
        "GET",
        "/api/subscriptions/subpage-config/{shortUuid}",
        SubpageConfigByShortUuid,
    )
)
GET_CONNECTION_KEYS_BY_USER_ID: Operation[ConnectionKeysByUserId] = Operation(
    "GET",
    "/api/subscriptions/connection-keys/{userId}",
    ConnectionKeysByUserId,
)


class SubscriptionsApi(SyncGroup):
    def get_all_subscriptions(
        self, *, start: int | None = None, size: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"start": start, "size": size}
        )

    def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> Iterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_SUBSCRIPTIONS, page_size)

    def get_subscription_by_username(self, username: str) -> Subscription:
        """Get subscription by username."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )

    def get_subscription_by_short_uuid_protected(
        self, short_uuid: str
    ) -> Subscription:
        """Get subscription by short uuid (protected route)."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED,
            path={"shortUuid": short_uuid},
        )

    def get_subscription_by_uuid(self, user_id: int) -> Subscription:
        """Get subscription by User ID."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_UUID, path={"userId": user_id}
        )

    def get_raw_subscription_by_short_uuid(
        self, short_uuid: str, *, with_disabled_hosts: str | None = None
    ) -> RawSubscriptionByShortUuid:
        """Get Raw Subscription by Short UUID."""
        return self._executor.execute(
            GET_RAW_SUBSCRIPTION_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            query={"withDisabledHosts": with_disabled_hosts},
        )

    def get_subpage_config_by_short_uuid(
        self, short_uuid: str, body: GetSubpageConfigByShortUuidBody
    ) -> SubpageConfigByShortUuid:
        """Get Subpage Config by Short UUID."""
        return self._executor.execute(
            GET_SUBPAGE_CONFIG_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            body=body,
        )

    def get_connection_keys_by_user_id(
        self, user_id: int
    ) -> ConnectionKeysByUserId:
        """Get connection keys (base64 format) by user id."""
        return self._executor.execute(
            GET_CONNECTION_KEYS_BY_USER_ID, path={"userId": user_id}
        )


class AsyncSubscriptionsApi(AsyncGroup):
    async def get_all_subscriptions(
        self, *, start: int | None = None, size: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return await self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"start": start, "size": size}
        )

    async def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_SUBSCRIPTIONS, page_size):
            yield item

    async def get_subscription_by_username(self, username: str) -> Subscription:
        """Get subscription by username."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )

    async def get_subscription_by_short_uuid_protected(
        self, short_uuid: str
    ) -> Subscription:
        """Get subscription by short uuid (protected route)."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_SHORT_UUID_PROTECTED,
            path={"shortUuid": short_uuid},
        )

    async def get_subscription_by_uuid(self, user_id: int) -> Subscription:
        """Get subscription by User ID."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_UUID, path={"userId": user_id}
        )

    async def get_raw_subscription_by_short_uuid(
        self, short_uuid: str, *, with_disabled_hosts: str | None = None
    ) -> RawSubscriptionByShortUuid:
        """Get Raw Subscription by Short UUID."""
        return await self._executor.execute(
            GET_RAW_SUBSCRIPTION_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            query={"withDisabledHosts": with_disabled_hosts},
        )

    async def get_subpage_config_by_short_uuid(
        self, short_uuid: str, body: GetSubpageConfigByShortUuidBody
    ) -> SubpageConfigByShortUuid:
        """Get Subpage Config by Short UUID."""
        return await self._executor.execute(
            GET_SUBPAGE_CONFIG_BY_SHORT_UUID,
            path={"shortUuid": short_uuid},
            body=body,
        )

    async def get_connection_keys_by_user_id(
        self, user_id: int
    ) -> ConnectionKeysByUserId:
        """Get connection keys (base64 format) by user id."""
        return await self._executor.execute(
            GET_CONNECTION_KEYS_BY_USER_ID, path={"userId": user_id}
        )
