# @generated by tools/codegen -- do not edit
"""Subscriptions Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    Subscription,
    SubscriptionsPage,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

GET_ALL_SUBSCRIPTIONS: Operation[SubscriptionsPage] = Operation(
    "GET",
    "/api/subscriptions",
    SubscriptionsPage,
    pagination=Pagination(items_field="subscriptions", max_page_size=100),
)
GET_SUBSCRIPTION_BY_USERNAME: Operation[Subscription] = Operation(
    "GET",
    "/api/subscriptions/by-username/{username}",
    Subscription,
)


class SubscriptionsApi(SyncGroup):
    def get_all_subscriptions(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"size": size, "start": start}
        )

    def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> Iterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_SUBSCRIPTIONS, page_size)

    def get_subscription_by_username(self, username: str) -> Subscription:
        """Get subscription by username."""
        return self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )


class AsyncSubscriptionsApi(AsyncGroup):
    async def get_all_subscriptions(
        self, *, size: int | None = None, start: int | None = None
    ) -> SubscriptionsPage:
        """Get all subscriptions."""
        return await self._executor.execute(
            GET_ALL_SUBSCRIPTIONS, query={"size": size, "start": start}
        )

    async def iter_all_subscriptions(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[Subscription]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_SUBSCRIPTIONS, page_size):
            yield item

    async def get_subscription_by_username(self, username: str) -> Subscription:
        """Get subscription by username."""
        return await self._executor.execute(
            GET_SUBSCRIPTION_BY_USERNAME, path={"username": username}
        )
