# @generated by tools/codegen -- do not edit
"""Subscription Template Controller."""

from remnawave._generated.models import (
    CreateSubscriptionTemplateRequest,
    Host,
    Template,
    Templates,
    UpdateTemplateRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_ALL_TEMPLATES: Operation[Templates] = Operation(
    "GET",
    "/api/subscription-templates",
    Templates,
)
UPDATE_TEMPLATE: Operation[Template] = Operation(
    "PATCH",
    "/api/subscription-templates",
    Template,
)
CREATE_TEMPLATE: Operation[Template] = Operation(
    "POST",
    "/api/subscription-templates",
    Template,
)
GET_TEMPLATE_BY_UUID: Operation[Template] = Operation(
    "GET",
    "/api/subscription-templates/{uuid}",
    Template,
)
DELETE_TEMPLATE: Operation[Host] = Operation(
    "DELETE",
    "/api/subscription-templates/{uuid}",
    Host,
)


class SubscriptionTemplateApi(SyncGroup):
    def get_all_templates(self) -> Templates:
        """Get all subscription templates (wihout content)."""
        return self._executor.execute(GET_ALL_TEMPLATES)

    def update_template(self, body: UpdateTemplateRequest) -> Template:
        """Update subscription template."""
        return self._executor.execute(UPDATE_TEMPLATE, body=body)

    def create_template(
        self, body: CreateSubscriptionTemplateRequest
    ) -> Template:
        """Create subscription template."""
        return self._executor.execute(CREATE_TEMPLATE, body=body)

    def get_template_by_uuid(self) -> Template:
        """Get subscription template by uuid."""
        return self._executor.execute(GET_TEMPLATE_BY_UUID)

    def delete_template(self, uuid: str) -> Host:
        """Delete subscription template."""
        return self._executor.execute(DELETE_TEMPLATE, path={"uuid": uuid})


class AsyncSubscriptionTemplateApi(AsyncGroup):
    async def get_all_templates(self) -> Templates:
        """Get all subscription templates (wihout content)."""
        return await self._executor.execute(GET_ALL_TEMPLATES)

    async def update_template(self, body: UpdateTemplateRequest) -> Template:
        """Update subscription template."""
        return await self._executor.execute(UPDATE_TEMPLATE, body=body)

    async def create_template(
        self, body: CreateSubscriptionTemplateRequest
    ) -> Template:
        """Create subscription template."""
        return await self._executor.execute(CREATE_TEMPLATE, body=body)

    async def get_template_by_uuid(self) -> Template:
        """Get subscription template by uuid."""
        return await self._executor.execute(GET_TEMPLATE_BY_UUID)

    async def delete_template(self, uuid: str) -> Host:
        """Delete subscription template."""
        return await self._executor.execute(
            DELETE_TEMPLATE, path={"uuid": uuid}
        )
