# @generated by tools/codegen -- do not edit
"""Subscriptions Template Controller."""

from remnawave._generated.enums import (
    TemplateTemplateType,
)
from remnawave._generated.models import (
    Template,
    UpdateTemplateRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_TEMPLATE: Operation[Template] = Operation(
    "GET",
    "/api/subscription-templates/{templateType}",
    Template,
)
UPDATE_TEMPLATE: Operation[Template] = Operation(
    "PUT",
    "/api/subscription-templates",
    Template,
)


class SubscriptionsTemplateApi(SyncGroup):
    def get_template(self, template_type: TemplateTemplateType) -> Template:
        """Get subscription template."""
        return self._executor.execute(
            GET_TEMPLATE, path={"templateType": template_type}
        )

    def update_template(self, body: UpdateTemplateRequest) -> Template:
        """Update subscription template."""
        return self._executor.execute(UPDATE_TEMPLATE, body=body)


class AsyncSubscriptionsTemplateApi(AsyncGroup):
    async def get_template(
        self, template_type: TemplateTemplateType
    ) -> Template:
        """Get subscription template."""
        return await self._executor.execute(
            GET_TEMPLATE, path={"templateType": template_type}
        )

    async def update_template(self, body: UpdateTemplateRequest) -> Template:
        """Update subscription template."""
        return await self._executor.execute(UPDATE_TEMPLATE, body=body)
