# @generated by tools/codegen -- do not edit
"""Subscription Page Configs Controller."""

from remnawave._generated.models import (
    CloneSubscriptionPageConfigRequest,
    DeleteSnippetRequest,
    Host,
    ReorderConfigProfilesRequest,
    SubscriptionPageConfig,
    SubscriptionPageConfigs,
    UpdateSubscriptionPageConfigRequest,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_ALL_CONFIGS: Operation[SubscriptionPageConfigs] = Operation(
    "GET",
    "/api/subscription-page-configs",
    SubscriptionPageConfigs,
)
UPDATE_CONFIG: Operation[SubscriptionPageConfig] = Operation(
    "PATCH",
    "/api/subscription-page-configs",
    SubscriptionPageConfig,
)
CREATE_CONFIG: Operation[SubscriptionPageConfig] = Operation(
    "POST",
    "/api/subscription-page-configs",
    SubscriptionPageConfig,
)
GET_CONFIG_BY_UUID: Operation[SubscriptionPageConfig] = Operation(
    "GET",
    "/api/subscription-page-configs/{uuid}",
    SubscriptionPageConfig,
)
DELETE_CONFIG: Operation[Host] = Operation(
    "DELETE",
    "/api/subscription-page-configs/{uuid}",
    Host,
)
REORDER_SUBSCRIPTION_PAGE_CONFIGS: Operation[SubscriptionPageConfigs] = (
    Operation(
        "POST",
        "/api/subscription-page-configs/actions/reorder",
        SubscriptionPageConfigs,
    )
)
CLONE_SUBSCRIPTION_PAGE_CONFIG: Operation[SubscriptionPageConfig] = Operation(
    "POST",
    "/api/subscription-page-configs/actions/clone",
    SubscriptionPageConfig,
)


class SubscriptionPageConfigsApi(SyncGroup):
    def get_all_configs(self) -> SubscriptionPageConfigs:
        """Get all subscription page configs."""
        return self._executor.execute(GET_ALL_CONFIGS)

    def update_config(
        self, body: UpdateSubscriptionPageConfigRequest
    ) -> SubscriptionPageConfig:
        """Update subscription page config."""
        return self._executor.execute(UPDATE_CONFIG, body=body)

    def create_config(
        self, body: DeleteSnippetRequest
    ) -> SubscriptionPageConfig:
        """Create subscription page config."""
        return self._executor.execute(CREATE_CONFIG, body=body)

    def get_config_by_uuid(self, uuid: str) -> SubscriptionPageConfig:
        """Get subscription page config by uuid."""
        return self._executor.execute(GET_CONFIG_BY_UUID, path={"uuid": uuid})

    def delete_config(self, uuid: str) -> Host:
        """Delete subscription page config."""
        return self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    def reorder_subscription_page_configs(
        self, body: ReorderConfigProfilesRequest
    ) -> SubscriptionPageConfigs:
        """Reorder subscription page configs."""
        return self._executor.execute(
            REORDER_SUBSCRIPTION_PAGE_CONFIGS, body=body
        )

    def clone_subscription_page_config(
        self, body: CloneSubscriptionPageConfigRequest
    ) -> SubscriptionPageConfig:
        """Clone subscription page config."""
        return self._executor.execute(CLONE_SUBSCRIPTION_PAGE_CONFIG, body=body)


class AsyncSubscriptionPageConfigsApi(AsyncGroup):
    async def get_all_configs(self) -> SubscriptionPageConfigs:
        """Get all subscription page configs."""
        return await self._executor.execute(GET_ALL_CONFIGS)

    async def update_config(
        self, body: UpdateSubscriptionPageConfigRequest
    ) -> SubscriptionPageConfig:
        """Update subscription page config."""
        return await self._executor.execute(UPDATE_CONFIG, body=body)

    async def create_config(
        self, body: DeleteSnippetRequest
    ) -> SubscriptionPageConfig:
        """Create subscription page config."""
        return await self._executor.execute(CREATE_CONFIG, body=body)

    async def get_config_by_uuid(self, uuid: str) -> SubscriptionPageConfig:
        """Get subscription page config by uuid."""
        return await self._executor.execute(
            GET_CONFIG_BY_UUID, path={"uuid": uuid}
        )

    async def delete_config(self, uuid: str) -> Host:
        """Delete subscription page config."""
        return await self._executor.execute(DELETE_CONFIG, path={"uuid": uuid})

    async def reorder_subscription_page_configs(
        self, body: ReorderConfigProfilesRequest
    ) -> SubscriptionPageConfigs:
        """Reorder subscription page configs."""
        return await self._executor.execute(
            REORDER_SUBSCRIPTION_PAGE_CONFIGS, body=body
        )

    async def clone_subscription_page_config(
        self, body: CloneSubscriptionPageConfigRequest
    ) -> SubscriptionPageConfig:
        """Clone subscription page config."""
        return await self._executor.execute(
            CLONE_SUBSCRIPTION_PAGE_CONFIG, body=body
        )
