# @generated by tools/codegen -- do not edit
"""System Controller."""

from remnawave._generated.models import (
    BandwidthStats,
    NodesMetrics,
    NodesStatistics,
    RemnawaveHealth,
    Stats,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_STATS: Operation[Stats] = Operation(
    "GET",
    "/api/system/stats",
    Stats,
)
GET_BANDWIDTH_STATS: Operation[BandwidthStats] = Operation(
    "GET",
    "/api/system/stats/bandwidth",
    BandwidthStats,
)
GET_NODES_STATISTICS: Operation[NodesStatistics] = Operation(
    "GET",
    "/api/system/stats/nodes",
    NodesStatistics,
)
GET_REMNAWAVE_HEALTH: Operation[RemnawaveHealth] = Operation(
    "GET",
    "/api/system/health",
    RemnawaveHealth,
)
GET_NODES_METRICS: Operation[NodesMetrics] = Operation(
    "GET",
    "/api/system/nodes/metrics",
    NodesMetrics,
)


class SystemApi(SyncGroup):
    def get_stats(self) -> Stats:
        """Get Stats."""
        return self._executor.execute(GET_STATS)

    def get_bandwidth_stats(self) -> BandwidthStats:
        """Get Bandwidth Stats."""
        return self._executor.execute(GET_BANDWIDTH_STATS)

    def get_nodes_statistics(self) -> NodesStatistics:
        """Get Nodes Statistics."""
        return self._executor.execute(GET_NODES_STATISTICS)

    def get_remnawave_health(self) -> RemnawaveHealth:
        """Get Remnawave Health."""
        return self._executor.execute(GET_REMNAWAVE_HEALTH)

    def get_nodes_metrics(self) -> NodesMetrics:
        """Get Nodes Metrics."""
        return self._executor.execute(GET_NODES_METRICS)


class AsyncSystemApi(AsyncGroup):
    async def get_stats(self) -> Stats:
        """Get Stats."""
        return await self._executor.execute(GET_STATS)

    async def get_bandwidth_stats(self) -> BandwidthStats:
        """Get Bandwidth Stats."""
        return await self._executor.execute(GET_BANDWIDTH_STATS)

    async def get_nodes_statistics(self) -> NodesStatistics:
        """Get Nodes Statistics."""
        return await self._executor.execute(GET_NODES_STATISTICS)

    async def get_remnawave_health(self) -> RemnawaveHealth:
        """Get Remnawave Health."""
        return await self._executor.execute(GET_REMNAWAVE_HEALTH)

    async def get_nodes_metrics(self) -> NodesMetrics:
        """Get Nodes Metrics."""
        return await self._executor.execute(GET_NODES_METRICS)
