# @generated by tools/codegen -- do not edit
"""Users Controller."""

from collections.abc import AsyncIterator, Iterator

from remnawave._generated.models import (
    CreateUserRequest,
    Host,
    ResolveUserRequestBody,
    RevokeUserSubscriptionBody,
    Tags,
    UpdateUserRequest,
    User,
    UserAccessibleNodes,
    UserRef,
    UsersPage,
    UsersStream,
    UserSubscriptionRequestHistory,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
    Pagination,
)

CREATE_USER: Operation[User] = Operation(
    "POST",
    "/api/users",
    User,
)
UPDATE_USER: Operation[User] = Operation(
    "PATCH",
    "/api/users",
    User,
)
GET_ALL_USERS: Operation[UsersPage] = Operation(
    "GET",
    "/api/users",
    UsersPage,
    pagination=Pagination(items_field="users", max_page_size=100),
)
DELETE_USER: Operation[Host] = Operation(
    "DELETE",
    "/api/users/{uuid}",
    Host,
)
GET_USER_BY_UUID: Operation[User] = Operation(
    "GET",
    "/api/users/{uuid}",
    User,
)
GET_USERS_STREAM: Operation[UsersStream] = Operation(
    "GET",
    "/api/users/stream",
    UsersStream,
)
GET_ALL_TAGS: Operation[Tags] = Operation(
    "GET",
    "/api/users/tags",
    Tags,
)
GET_USER_ACCESSIBLE_NODES: Operation[UserAccessibleNodes] = Operation(
    "GET",
    "/api/users/{uuid}/accessible-nodes",
    UserAccessibleNodes,
)
GET_USER_SUBSCRIPTION_REQUEST_HISTORY: Operation[
    UserSubscriptionRequestHistory
] = Operation(
    "GET",
    "/api/users/{uuid}/subscription-request-history",
    UserSubscriptionRequestHistory,
)
GET_USER_BY_SHORT_UUID: Operation[User] = Operation(
    "GET",
    "/api/users/by-short-uuid/{shortUuid}",
    User,
)
GET_USER_BY_USERNAME: Operation[User] = Operation(
    "GET",
    "/api/users/by-username/{username}",
    User,
)
GET_USER_BY_ID: Operation[User] = Operation(
    "GET",
    "/api/users/by-id/{id}",
    User,
)
GET_USER_BY_TELEGRAM_ID: Operation[list[User]] = Operation(
    "GET",
    "/api/users/by-telegram-id/{telegramId}",
    list[User],
)
GET_USERS_BY_EMAIL: Operation[list[User]] = Operation(
    "GET",
    "/api/users/by-email/{email}",
    list[User],
)
GET_USERS_BY_TAG: Operation[list[User]] = Operation(
    "GET",
    "/api/users/by-tag/{tag}",
    list[User],
)
REVOKE_USER_SUBSCRIPTION: Operation[User] = Operation(
    "POST",
    "/api/users/{uuid}/actions/revoke",
    User,
)
DISABLE_USER: Operation[User] = Operation(
    "POST",
    "/api/users/{uuid}/actions/disable",
    User,
)
ENABLE_USER: Operation[User] = Operation(
    "POST",
    "/api/users/{uuid}/actions/enable",
    User,
)
RESET_USER_TRAFFIC: Operation[User] = Operation(
    "POST",
    "/api/users/{uuid}/actions/reset-traffic",
    User,
)
RESOLVE_USER: Operation[UserRef] = Operation(
    "POST",
    "/api/users/resolve",
    UserRef,
)


class UsersApi(SyncGroup):
    def create_user(self, body: CreateUserRequest) -> User:
        """Create a new user."""
        return self._executor.execute(CREATE_USER, body=body)

    def update_user(self, body: UpdateUserRequest) -> User:
        """Update a user by UUID or username."""
        return self._executor.execute(UPDATE_USER, body=body)

    def get_all_users(
        self, *, size: int | None = None, start: int | None = None
    ) -> UsersPage:
        """Get all users using offset-based pagination."""
        return self._executor.execute(
            GET_ALL_USERS, query={"size": size, "start": start}
        )

    def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> Iterator[User]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_ALL_USERS, page_size)

    def delete_user(self, uuid: str) -> Host:
        """Delete user."""
        return self._executor.execute(DELETE_USER, path={"uuid": uuid})

    def get_user_by_uuid(self, uuid: str) -> User:
        """Get user by UUID."""
        return self._executor.execute(GET_USER_BY_UUID, path={"uuid": uuid})

    def get_users_stream(
        self, *, size: int | None = None, cursor: str | None = None
    ) -> UsersStream:
        """Get all users using cursor-based (keyset) pagination."""
        return self._executor.execute(
            GET_USERS_STREAM, query={"size": size, "cursor": cursor}
        )

    def get_all_tags(self) -> Tags:
        """Get all existing user tags."""
        return self._executor.execute(GET_ALL_TAGS)

    def get_user_accessible_nodes(self, uuid: str) -> UserAccessibleNodes:
        """Get user accessible nodes."""
        return self._executor.execute(
            GET_USER_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    def get_user_subscription_request_history(
        self, uuid: str
    ) -> UserSubscriptionRequestHistory:
        """Get user subscription request history, recent 24 records."""
        return self._executor.execute(
            GET_USER_SUBSCRIPTION_REQUEST_HISTORY, path={"uuid": uuid}
        )

    def get_user_by_short_uuid(self, short_uuid: str) -> User:
        """Get user by Short UUID."""
        return self._executor.execute(
            GET_USER_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    def get_user_by_username(self, username: str) -> User:
        """Get user by username."""
        return self._executor.execute(
            GET_USER_BY_USERNAME, path={"username": username}
        )

    def get_user_by_id(self, id: str) -> User:
        """Get user by ID."""
        return self._executor.execute(GET_USER_BY_ID, path={"id": id})

    def get_user_by_telegram_id(self, telegram_id: str) -> list[User]:
        """Get users by telegram ID."""
        return self._executor.execute(
            GET_USER_BY_TELEGRAM_ID, path={"telegramId": telegram_id}
        )

    def get_users_by_email(self, email: str) -> list[User]:
        """Get users by email."""
        return self._executor.execute(GET_USERS_BY_EMAIL, path={"email": email})

    def get_users_by_tag(self, tag: str) -> list[User]:
        """Get users by tag."""
        return self._executor.execute(GET_USERS_BY_TAG, path={"tag": tag})

    def revoke_user_subscription(
        self, uuid: str, body: RevokeUserSubscriptionBody
    ) -> User:
        """Revoke user subscription."""
        return self._executor.execute(
            REVOKE_USER_SUBSCRIPTION, path={"uuid": uuid}, body=body
        )

    def disable_user(self, uuid: str) -> User:
        """Disable user."""
        return self._executor.execute(DISABLE_USER, path={"uuid": uuid})

    def enable_user(self, uuid: str) -> User:
        """Enable user."""
        return self._executor.execute(ENABLE_USER, path={"uuid": uuid})

    def reset_user_traffic(self, uuid: str) -> User:
        """Reset user traffic."""
        return self._executor.execute(RESET_USER_TRAFFIC, path={"uuid": uuid})

    def resolve_user(self, body: ResolveUserRequestBody) -> UserRef:
        """Resolve a user."""
        return self._executor.execute(RESOLVE_USER, body=body)


class AsyncUsersApi(AsyncGroup):
    async def create_user(self, body: CreateUserRequest) -> User:
        """Create a new user."""
        return await self._executor.execute(CREATE_USER, body=body)

    async def update_user(self, body: UpdateUserRequest) -> User:
        """Update a user by UUID or username."""
        return await self._executor.execute(UPDATE_USER, body=body)

    async def get_all_users(
        self, *, size: int | None = None, start: int | None = None
    ) -> UsersPage:
        """Get all users using offset-based pagination."""
        return await self._executor.execute(
            GET_ALL_USERS, query={"size": size, "start": start}
        )

    async def iter_all_users(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[User]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_ALL_USERS, page_size):
            yield item

    async def delete_user(self, uuid: str) -> Host:
        """Delete user."""
        return await self._executor.execute(DELETE_USER, path={"uuid": uuid})

    async def get_user_by_uuid(self, uuid: str) -> User:
        """Get user by UUID."""
        return await self._executor.execute(
            GET_USER_BY_UUID, path={"uuid": uuid}
        )

    async def get_users_stream(
        self, *, size: int | None = None, cursor: str | None = None
    ) -> UsersStream:
        """Get all users using cursor-based (keyset) pagination."""
        return await self._executor.execute(
            GET_USERS_STREAM, query={"size": size, "cursor": cursor}
        )

    async def get_all_tags(self) -> Tags:
        """Get all existing user tags."""
        return await self._executor.execute(GET_ALL_TAGS)

    async def get_user_accessible_nodes(self, uuid: str) -> UserAccessibleNodes:
        """Get user accessible nodes."""
        return await self._executor.execute(
            GET_USER_ACCESSIBLE_NODES, path={"uuid": uuid}
        )

    async def get_user_subscription_request_history(
        self, uuid: str
    ) -> UserSubscriptionRequestHistory:
        """Get user subscription request history, recent 24 records."""
        return await self._executor.execute(
            GET_USER_SUBSCRIPTION_REQUEST_HISTORY, path={"uuid": uuid}
        )

    async def get_user_by_short_uuid(self, short_uuid: str) -> User:
        """Get user by Short UUID."""
        return await self._executor.execute(
            GET_USER_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    async def get_user_by_username(self, username: str) -> User:
        """Get user by username."""
        return await self._executor.execute(
            GET_USER_BY_USERNAME, path={"username": username}
        )

    async def get_user_by_id(self, id: str) -> User:
        """Get user by ID."""
        return await self._executor.execute(GET_USER_BY_ID, path={"id": id})

    async def get_user_by_telegram_id(self, telegram_id: str) -> list[User]:
        """Get users by telegram ID."""
        return await self._executor.execute(
            GET_USER_BY_TELEGRAM_ID, path={"telegramId": telegram_id}
        )

    async def get_users_by_email(self, email: str) -> list[User]:
        """Get users by email."""
        return await self._executor.execute(
            GET_USERS_BY_EMAIL, path={"email": email}
        )

    async def get_users_by_tag(self, tag: str) -> list[User]:
        """Get users by tag."""
        return await self._executor.execute(GET_USERS_BY_TAG, path={"tag": tag})

    async def revoke_user_subscription(
        self, uuid: str, body: RevokeUserSubscriptionBody
    ) -> User:
        """Revoke user subscription."""
        return await self._executor.execute(
            REVOKE_USER_SUBSCRIPTION, path={"uuid": uuid}, body=body
        )

    async def disable_user(self, uuid: str) -> User:
        """Disable user."""
        return await self._executor.execute(DISABLE_USER, path={"uuid": uuid})

    async def enable_user(self, uuid: str) -> User:
        """Enable user."""
        return await self._executor.execute(ENABLE_USER, path={"uuid": uuid})

    async def reset_user_traffic(self, uuid: str) -> User:
        """Reset user traffic."""
        return await self._executor.execute(
            RESET_USER_TRAFFIC, path={"uuid": uuid}
        )

    async def resolve_user(self, body: ResolveUserRequestBody) -> UserRef:
        """Resolve a user."""
        return await self._executor.execute(RESOLVE_USER, body=body)
