# @generated by tools/codegen -- do not edit
"""Users Stats Controller."""

from datetime import datetime

from remnawave._generated.models import (
    UserUsageByRange,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

GET_USER_USAGE_BY_RANGE: Operation[list[UserUsageByRange]] = Operation(
    "GET",
    "/api/users/stats/usage/{uuid}/range",
    list[UserUsageByRange],
)


class UsersStatsApi(SyncGroup):
    def get_user_usage_by_range(
        self, uuid: str, start: datetime, end: datetime
    ) -> list[UserUsageByRange]:
        """Get user usage by range."""
        return self._executor.execute(
            GET_USER_USAGE_BY_RANGE,
            path={"uuid": uuid},
            query={"start": start, "end": end},
        )


class AsyncUsersStatsApi(AsyncGroup):
    async def get_user_usage_by_range(
        self, uuid: str, start: datetime, end: datetime
    ) -> list[UserUsageByRange]:
        """Get user usage by range."""
        return await self._executor.execute(
            GET_USER_USAGE_BY_RANGE,
            path={"uuid": uuid},
            query={"start": start, "end": end},
        )
