# @generated by tools/codegen -- do not edit
"""Users Bulk Actions Controller."""

from remnawave._generated.models import (
    BulkAllUpdateUsersRequest,
    BulkDeleteHostsRequest,
    BulkDeleteUsersByStatusRequest,
    BulkUpdateUsersRequest,
    BulkUpdateUsersSquadsRequest,
    DeleteUsers,
    Node,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    Operation,
)

BULK_DELETE_USERS_BY_STATUS: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/delete-by-status",
    DeleteUsers,
)
BULK_DELETE_USERS: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/delete",
    DeleteUsers,
)
BULK_REVOKE_USERS_SUBSCRIPTION: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/revoke-subscription",
    DeleteUsers,
)
BULK_RESET_USER_TRAFFIC: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/reset-traffic",
    DeleteUsers,
)
BULK_UPDATE_USERS: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/update",
    DeleteUsers,
)
BULK_UPDATE_USERS_INTERNAL_SQUADS: Operation[DeleteUsers] = Operation(
    "POST",
    "/api/users/bulk/update-squads",
    DeleteUsers,
)
BULK_UPDATE_ALL_USERS: Operation[Node] = Operation(
    "POST",
    "/api/users/bulk/all/update",
    Node,
)
BULK_ALL_RESET_USER_TRAFFIC: Operation[Node] = Operation(
    "POST",
    "/api/users/bulk/all/reset-traffic",
    Node,
)


class UsersBulkActionsApi(SyncGroup):
    def bulk_delete_users_by_status(
        self, body: BulkDeleteUsersByStatusRequest
    ) -> DeleteUsers:
        """Bulk delete users by status."""
        return self._executor.execute(BULK_DELETE_USERS_BY_STATUS, body=body)

    def bulk_delete_users(self, body: BulkDeleteHostsRequest) -> DeleteUsers:
        """Bulk delete users by UUIDs."""
        return self._executor.execute(BULK_DELETE_USERS, body=body)

    def bulk_revoke_users_subscription(
        self, body: BulkDeleteHostsRequest
    ) -> DeleteUsers:
        """Revoke users subscription by User UUIDs."""
        return self._executor.execute(BULK_REVOKE_USERS_SUBSCRIPTION, body=body)

    def bulk_reset_user_traffic(
        self, body: BulkDeleteHostsRequest
    ) -> DeleteUsers:
        """Bulk reset traffic users by UUIDs."""
        return self._executor.execute(BULK_RESET_USER_TRAFFIC, body=body)

    def bulk_update_users(self, body: BulkUpdateUsersRequest) -> DeleteUsers:
        """Bulk update users by UUIDs."""
        return self._executor.execute(BULK_UPDATE_USERS, body=body)

    def bulk_update_users_internal_squads(
        self, body: BulkUpdateUsersSquadsRequest
    ) -> DeleteUsers:
        """Bulk update users internal squads by UUIDs."""
        return self._executor.execute(
            BULK_UPDATE_USERS_INTERNAL_SQUADS, body=body
        )

    def bulk_update_all_users(self, body: BulkAllUpdateUsersRequest) -> Node:
        """Bulk update all users."""
        return self._executor.execute(BULK_UPDATE_ALL_USERS, body=body)

    def bulk_all_reset_user_traffic(self) -> Node:
        """Bulk Reset All Users Traffic."""
        return self._executor.execute(BULK_ALL_RESET_USER_TRAFFIC)


class AsyncUsersBulkActionsApi(AsyncGroup):
    async def bulk_delete_users_by_status(
        self, body: BulkDeleteUsersByStatusRequest
    ) -> DeleteUsers:
        """Bulk delete users by status."""
        return await self._executor.execute(
            BULK_DELETE_USERS_BY_STATUS, body=body
        )

    async def bulk_delete_users(
        self, body: BulkDeleteHostsRequest
    ) -> DeleteUsers:
        """Bulk delete users by UUIDs."""
        return await self._executor.execute(BULK_DELETE_USERS, body=body)

    async def bulk_revoke_users_subscription(
        self, body: BulkDeleteHostsRequest
    ) -> DeleteUsers:
        """Revoke users subscription by User UUIDs."""
        return await self._executor.execute(
            BULK_REVOKE_USERS_SUBSCRIPTION, body=body
        )

    async def bulk_reset_user_traffic(
        self, body: BulkDeleteHostsRequest
    ) -> DeleteUsers:
        """Bulk reset traffic users by UUIDs."""
        return await self._executor.execute(BULK_RESET_USER_TRAFFIC, body=body)

    async def bulk_update_users(
        self, body: BulkUpdateUsersRequest
    ) -> DeleteUsers:
        """Bulk update users by UUIDs."""
        return await self._executor.execute(BULK_UPDATE_USERS, body=body)

    async def bulk_update_users_internal_squads(
        self, body: BulkUpdateUsersSquadsRequest
    ) -> DeleteUsers:
        """Bulk update users internal squads by UUIDs."""
        return await self._executor.execute(
            BULK_UPDATE_USERS_INTERNAL_SQUADS, body=body
        )

    async def bulk_update_all_users(
        self, body: BulkAllUpdateUsersRequest
    ) -> Node:
        """Bulk update all users."""
        return await self._executor.execute(BULK_UPDATE_ALL_USERS, body=body)

    async def bulk_all_reset_user_traffic(self) -> Node:
        """Bulk Reset All Users Traffic."""
        return await self._executor.execute(BULK_ALL_RESET_USER_TRAFFIC)
