# @generated by tools/codegen -- do not edit
"""Users Controller."""

from collections.abc import AsyncIterator, Iterator
from typing import Any
from uuid import UUID

from remnawave._generated.enums import (
    UserStatus,
    UserTrafficLimitStrategy,
)
from remnawave._generated.models import (
    CreateUserBody,
    ExtendUserBody,
    HostsTags,
    QueryFilter,
    QuerySort,
    ResolveUserBody,
    RevokeUserSubscriptionBody,
    UpdateUserBody,
    User,
    UserAccessibleNodes,
    UserRef,
    UsersPage,
    UsersStream,
    UserSubscriptionRequestHistory,
)
from remnawave.execution import AsyncGroup, SyncGroup
from remnawave.operations import (
    NoContentOperation,
    Operation,
    Pagination,
)

CREATE_USER: Operation[User] = Operation(
    "POST",
    "/api/users",
    User,
)
UPDATE_USER: Operation[User] = Operation(
    "PATCH",
    "/api/users",
    User,
)
GET_USERS: Operation[UsersPage] = Operation(
    "GET",
    "/api/users",
    UsersPage,
    pagination=Pagination(items_field="users", max_page_size=1000),
)
DELETE_USER = NoContentOperation("DELETE", "/api/users/{userId}")
GET_USER_BY_ID: Operation[User] = Operation(
    "GET",
    "/api/users/{userId}",
    User,
)
GET_USERS_STREAM: Operation[UsersStream] = Operation(
    "GET",
    "/api/users/stream",
    UsersStream,
)
GET_USERS_TAGS: Operation[HostsTags] = Operation(
    "GET",
    "/api/users/tags",
    HostsTags,
)
GET_USER_ACCESSIBLE_NODES: Operation[UserAccessibleNodes] = Operation(
    "GET",
    "/api/users/{userId}/accessible-nodes",
    UserAccessibleNodes,
)
GET_USER_SUBSCRIPTION_REQUEST_HISTORY: Operation[
    UserSubscriptionRequestHistory
] = Operation(
    "GET",
    "/api/users/{userId}/subscription-request-history",
    UserSubscriptionRequestHistory,
)
GET_USER_BY_SHORT_UUID: Operation[User] = Operation(
    "GET",
    "/api/users/by-short-uuid/{shortUuid}",
    User,
)
GET_USER_BY_USERNAME: Operation[User] = Operation(
    "GET",
    "/api/users/by-username/{username}",
    User,
)
REVOKE_USER_SUBSCRIPTION: Operation[User] = Operation(
    "POST",
    "/api/users/{userId}/actions/revoke",
    User,
)
DISABLE_USER: Operation[User] = Operation(
    "POST",
    "/api/users/{userId}/actions/disable",
    User,
)
ENABLE_USER: Operation[User] = Operation(
    "POST",
    "/api/users/{userId}/actions/enable",
    User,
)
RESET_USER_TRAFFIC: Operation[User] = Operation(
    "POST",
    "/api/users/{userId}/actions/reset-traffic",
    User,
)
EXTEND_USER_EXPIRATION_DATE: Operation[User] = Operation(
    "POST",
    "/api/users/{userId}/actions/extend",
    User,
)
RESOLVE_USER: Operation[UserRef] = Operation(
    "POST",
    "/api/users/resolve",
    UserRef,
)


class UsersApi(SyncGroup):
    def create_user(self, body: CreateUserBody) -> User:
        """Create a new user."""
        return self._executor.execute(CREATE_USER, body=body)

    def update_user(self, body: UpdateUserBody) -> User:
        """Update a user."""
        return self._executor.execute(UPDATE_USER, body=body)

    def get_users(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> UsersPage:
        """Get all users using offset-based pagination."""
        return self._executor.execute(
            GET_USERS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    def iter_users(
        self,
        page_size: int | None = None,
    ) -> Iterator[User]:
        """Все страницы одним ленивым потоком."""
        yield from self._paginate(GET_USERS, page_size)

    def delete_user(self, user_id: int) -> None:
        """Delete user."""
        return self._executor.execute(DELETE_USER, path={"userId": user_id})

    def get_user_by_id(self, user_id: int) -> User:
        """Get user by ID."""
        return self._executor.execute(GET_USER_BY_ID, path={"userId": user_id})

    def get_users_stream(
        self,
        *,
        cursor: int | None = None,
        size: int | None = None,
        status: UserStatus | None = None,
        traffic_limit_strategy: UserTrafficLimitStrategy | None = None,
        telegram_id: str | None = None,
        email: str | None = None,
        tag: str | None = None,
        external_squad_uuid: UUID | None = None,
    ) -> UsersStream:
        """
        Get all users using cursor-based (keyset) pagination with
        filtering options.
        """
        return self._executor.execute(
            GET_USERS_STREAM,
            query={
                "cursor": cursor,
                "size": size,
                "status": status,
                "trafficLimitStrategy": traffic_limit_strategy,
                "telegramId": telegram_id,
                "email": email,
                "tag": tag,
                "externalSquadUuid": external_squad_uuid,
            },
        )

    def get_users_tags(self) -> HostsTags:
        """Get users tags."""
        return self._executor.execute(GET_USERS_TAGS)

    def get_user_accessible_nodes(self, user_id: int) -> UserAccessibleNodes:
        """Get user accessible nodes."""
        return self._executor.execute(
            GET_USER_ACCESSIBLE_NODES, path={"userId": user_id}
        )

    def get_user_subscription_request_history(
        self, user_id: int
    ) -> UserSubscriptionRequestHistory:
        """Get user subscription request history, recent 24 records."""
        return self._executor.execute(
            GET_USER_SUBSCRIPTION_REQUEST_HISTORY, path={"userId": user_id}
        )

    def get_user_by_short_uuid(self, short_uuid: str) -> User:
        """Get user by Short UUID."""
        return self._executor.execute(
            GET_USER_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    def get_user_by_username(self, username: str) -> User:
        """Get user by username."""
        return self._executor.execute(
            GET_USER_BY_USERNAME, path={"username": username}
        )

    def revoke_user_subscription(
        self, user_id: int, body: RevokeUserSubscriptionBody
    ) -> User:
        """Revoke user subscription."""
        return self._executor.execute(
            REVOKE_USER_SUBSCRIPTION, path={"userId": user_id}, body=body
        )

    def disable_user(self, user_id: int) -> User:
        """Disable user."""
        return self._executor.execute(DISABLE_USER, path={"userId": user_id})

    def enable_user(self, user_id: int) -> User:
        """Enable user."""
        return self._executor.execute(ENABLE_USER, path={"userId": user_id})

    def reset_user_traffic(self, user_id: int) -> User:
        """Reset user traffic."""
        return self._executor.execute(
            RESET_USER_TRAFFIC, path={"userId": user_id}
        )

    def extend_user_expiration_date(
        self, user_id: int, body: ExtendUserBody
    ) -> User:
        """Extend user expiration date."""
        return self._executor.execute(
            EXTEND_USER_EXPIRATION_DATE, path={"userId": user_id}, body=body
        )

    def resolve_user(self, body: ResolveUserBody) -> UserRef:
        """Resolve a user."""
        return self._executor.execute(RESOLVE_USER, body=body)


class AsyncUsersApi(AsyncGroup):
    async def create_user(self, body: CreateUserBody) -> User:
        """Create a new user."""
        return await self._executor.execute(CREATE_USER, body=body)

    async def update_user(self, body: UpdateUserBody) -> User:
        """Update a user."""
        return await self._executor.execute(UPDATE_USER, body=body)

    async def get_users(
        self,
        *,
        start: int | None = None,
        size: int | None = None,
        filters: list[QueryFilter] | None = None,
        filter_modes: dict[str, Any] | None = None,
        global_filter_mode: str | None = None,
        sorting: list[QuerySort] | None = None,
    ) -> UsersPage:
        """Get all users using offset-based pagination."""
        return await self._executor.execute(
            GET_USERS,
            query={
                "start": start,
                "size": size,
                "filters": filters,
                "filterModes": filter_modes,
                "globalFilterMode": global_filter_mode,
                "sorting": sorting,
            },
        )

    async def iter_users(
        self,
        page_size: int | None = None,
    ) -> AsyncIterator[User]:
        """Все страницы одним ленивым потоком."""
        async for item in self._paginate(GET_USERS, page_size):
            yield item

    async def delete_user(self, user_id: int) -> None:
        """Delete user."""
        return await self._executor.execute(
            DELETE_USER, path={"userId": user_id}
        )

    async def get_user_by_id(self, user_id: int) -> User:
        """Get user by ID."""
        return await self._executor.execute(
            GET_USER_BY_ID, path={"userId": user_id}
        )

    async def get_users_stream(
        self,
        *,
        cursor: int | None = None,
        size: int | None = None,
        status: UserStatus | None = None,
        traffic_limit_strategy: UserTrafficLimitStrategy | None = None,
        telegram_id: str | None = None,
        email: str | None = None,
        tag: str | None = None,
        external_squad_uuid: UUID | None = None,
    ) -> UsersStream:
        """
        Get all users using cursor-based (keyset) pagination with
        filtering options.
        """
        return await self._executor.execute(
            GET_USERS_STREAM,
            query={
                "cursor": cursor,
                "size": size,
                "status": status,
                "trafficLimitStrategy": traffic_limit_strategy,
                "telegramId": telegram_id,
                "email": email,
                "tag": tag,
                "externalSquadUuid": external_squad_uuid,
            },
        )

    async def get_users_tags(self) -> HostsTags:
        """Get users tags."""
        return await self._executor.execute(GET_USERS_TAGS)

    async def get_user_accessible_nodes(
        self, user_id: int
    ) -> UserAccessibleNodes:
        """Get user accessible nodes."""
        return await self._executor.execute(
            GET_USER_ACCESSIBLE_NODES, path={"userId": user_id}
        )

    async def get_user_subscription_request_history(
        self, user_id: int
    ) -> UserSubscriptionRequestHistory:
        """Get user subscription request history, recent 24 records."""
        return await self._executor.execute(
            GET_USER_SUBSCRIPTION_REQUEST_HISTORY, path={"userId": user_id}
        )

    async def get_user_by_short_uuid(self, short_uuid: str) -> User:
        """Get user by Short UUID."""
        return await self._executor.execute(
            GET_USER_BY_SHORT_UUID, path={"shortUuid": short_uuid}
        )

    async def get_user_by_username(self, username: str) -> User:
        """Get user by username."""
        return await self._executor.execute(
            GET_USER_BY_USERNAME, path={"username": username}
        )

    async def revoke_user_subscription(
        self, user_id: int, body: RevokeUserSubscriptionBody
    ) -> User:
        """Revoke user subscription."""
        return await self._executor.execute(
            REVOKE_USER_SUBSCRIPTION, path={"userId": user_id}, body=body
        )

    async def disable_user(self, user_id: int) -> User:
        """Disable user."""
        return await self._executor.execute(
            DISABLE_USER, path={"userId": user_id}
        )

    async def enable_user(self, user_id: int) -> User:
        """Enable user."""
        return await self._executor.execute(
            ENABLE_USER, path={"userId": user_id}
        )

    async def reset_user_traffic(self, user_id: int) -> User:
        """Reset user traffic."""
        return await self._executor.execute(
            RESET_USER_TRAFFIC, path={"userId": user_id}
        )

    async def extend_user_expiration_date(
        self, user_id: int, body: ExtendUserBody
    ) -> User:
        """Extend user expiration date."""
        return await self._executor.execute(
            EXTEND_USER_EXPIRATION_DATE, path={"userId": user_id}, body=body
        )

    async def resolve_user(self, body: ResolveUserBody) -> UserRef:
        """Resolve a user."""
        return await self._executor.execute(RESOLVE_USER, body=body)
