# @generated by tools/codegen -- do not edit
from enum import StrEnum


class OAuth2CallbackRequestProvider(StrEnum):
    TELEGRAM = "telegram"
    GITHUB = "github"
    POCKETID = "pocketid"
    YANDEX = "yandex"
    KEYCLOAK = "keycloak"
    GENERIC = "generic"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    LIMITED = "LIMITED"
    EXPIRED = "EXPIRED"


class UserTrafficLimitStrategy(StrEnum):
    NO_RESET = "NO_RESET"
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    MONTH_ROLLING = "MONTH_ROLLING"


class UpdateUserRequestStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class SubscriptionControllerGetSubscriptionByClientType(StrEnum):
    STASH = "stash"
    SINGBOX = "singbox"
    MIHOMO = "mihomo"
    JSON = "json"
    V2RAY_JSON = "v2ray-json"
    CLASH = "clash"


class RawSubscriptionByShortUuidResolvedProxyConfigProtocol(StrEnum):
    VLESS = "vless"
    TROJAN = "trojan"
    SHADOWSOCKS = "shadowsocks"
    HYSTERIA = "hysteria"


class RawSubscriptionByShortUuidResolvedProxyConfigTransport(StrEnum):
    TCP = "tcp"
    XHTTP = "xhttp"
    WS = "ws"
    HTTPUPGRADE = "httpupgrade"
    GRPC = "grpc"
    KCP = "kcp"
    HYSTERIA = "hysteria"


class RawSubscriptionByShortUuidResolvedProxyConfigSecurity(StrEnum):
    TLS = "tls"
    REALITY = "reality"
    NONE = "none"


class HostMihomoIpVersion(StrEnum):
    DUAL = "dual"
    IPV4 = "ipv4"
    IPV6 = "ipv6"
    IPV4_PREFER = "ipv4-prefer"
    IPV6_PREFER = "ipv6-prefer"


class TemplateTemplateType(StrEnum):
    XRAY_JSON = "XRAY_JSON"
    XRAY_BASE64 = "XRAY_BASE64"
    MIHOMO = "MIHOMO"
    STASH = "STASH"
    CLASH = "CLASH"
    SINGBOX = "SINGBOX"


class ApiTokenScopesResourceEndpointKind(StrEnum):
    READ = "read"
    WRITE = "write"


class BulkNodesActionsRequestAction(StrEnum):
    ENABLE = "ENABLE"
    DISABLE = "DISABLE"
    RESTART = "RESTART"
    RESET_TRAFFIC = "RESET_TRAFFIC"


class HostAlpn(StrEnum):
    H3 = "h3"
    H2 = "h2"
    HTTP_1_1 = "http/1.1"
    H2_HTTP_1_1 = "h2,http/1.1"
    H3_H2_HTTP_1_1 = "h3,h2,http/1.1"
    H3_H2 = "h3,h2"


class HostSecurityLayer(StrEnum):
    DEFAULT = "DEFAULT"
    TLS = "TLS"
    NONE = "NONE"


class SrrMatcherResponseType(StrEnum):
    XRAY_JSON = "XRAY_JSON"
    XRAY_BASE64 = "XRAY_BASE64"
    MIHOMO = "MIHOMO"
    STASH = "STASH"
    CLASH = "CLASH"
    SINGBOX = "SINGBOX"
    BROWSER = "BROWSER"
    BLOCK = "BLOCK"
    STATUS_CODE_404 = "STATUS_CODE_404"
    STATUS_CODE_451 = "STATUS_CODE_451"
    SOCKET_DROP = "SOCKET_DROP"


class SrrMatcherMatchedRuleOperator(StrEnum):
    AND_ = "AND"
    OR_ = "OR"


class SrrMatcherMatchedRuleConditionOperator(StrEnum):
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    CONTAINS = "CONTAINS"
    NOT_CONTAINS = "NOT_CONTAINS"
    STARTS_WITH = "STARTS_WITH"
    NOT_STARTS_WITH = "NOT_STARTS_WITH"
    ENDS_WITH = "ENDS_WITH"
    NOT_ENDS_WITH = "NOT_ENDS_WITH"
    REGEX = "REGEX"
    NOT_REGEX = "NOT_REGEX"


class SrrMatcherMatchedRuleResponseModificationEncryptionMethod(StrEnum):
    AGE1 = "age1"
    AGE1PQ1 = "age1pq1"


class CrmEventEvent(StrEnum):
    CRM_INFRA_BILLING_NODE_PAYMENT_IN_7_DAYS = (
        "crm.infra_billing_node_payment_in_7_days"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_IN_48HRS = (
        "crm.infra_billing_node_payment_in_48hrs"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_IN_24HRS = (
        "crm.infra_billing_node_payment_in_24hrs"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_DUE_TODAY = (
        "crm.infra_billing_node_payment_due_today"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_OVERDUE_24HRS = (
        "crm.infra_billing_node_payment_overdue_24hrs"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_OVERDUE_48HRS = (
        "crm.infra_billing_node_payment_overdue_48hrs"
    )
    CRM_INFRA_BILLING_NODE_PAYMENT_OVERDUE_7_DAYS = (
        "crm.infra_billing_node_payment_overdue_7_days"
    )


class NodeEventEvent(StrEnum):
    NODE_CREATED = "node.created"
    NODE_MODIFIED = "node.modified"
    NODE_DISABLED = "node.disabled"
    NODE_ENABLED = "node.enabled"
    NODE_DELETED = "node.deleted"
    NODE_CONNECTION_LOST = "node.connection_lost"
    NODE_CONNECTION_RESTORED = "node.connection_restored"
    NODE_TRAFFIC_NOTIFY = "node.traffic_notify"


class ServiceEventEvent(StrEnum):
    SERVICE_PANEL_STARTED = "service.panel_started"
    SERVICE_LOGIN_ATTEMPT_FAILED = "service.login_attempt_failed"
    SERVICE_LOGIN_ATTEMPT_SUCCESS = "service.login_attempt_success"
    SERVICE_SUBPAGE_CONFIG_CHANGED = "service.subpage_config_changed"
    SERVICE_API_TOKEN_CREATED = "service.api_token_created"
    SERVICE_API_TOKEN_DELETED = "service.api_token_deleted"


class ServiceEventDataSubpageConfigAction(StrEnum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DELETED = "DELETED"


class UserEventEvent(StrEnum):
    USER_CREATED = "user.created"
    USER_MODIFIED = "user.modified"
    USER_DELETED = "user.deleted"
    USER_REVOKED = "user.revoked"
    USER_DISABLED = "user.disabled"
    USER_ENABLED = "user.enabled"
    USER_LIMITED = "user.limited"
    USER_EXPIRED = "user.expired"
    USER_TRAFFIC_RESET = "user.traffic_reset"
    USER_FIRST_CONNECTED = "user.first_connected"
    USER_BANDWIDTH_USAGE_THRESHOLD_REACHED = (
        "user.bandwidth_usage_threshold_reached"
    )
    USER_NOT_CONNECTED = "user.not_connected"
    USER_EXPIRATION = "user.expiration"


class UserHwidDevicesEventEvent(StrEnum):
    USER_HWID_DEVICES_ADDED = "user_hwid_devices.added"
    USER_HWID_DEVICES_DELETED = "user_hwid_devices.deleted"
