# @generated by tools/codegen -- do not edit
from enum import StrEnum


class OAuth2CallbackRequestProvider(StrEnum):
    GITHUB = "github"
    POCKETID = "pocketid"
    YANDEX = "yandex"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    LIMITED = "LIMITED"
    EXPIRED = "EXPIRED"


class UserTrafficLimitStrategy(StrEnum):
    NO_RESET = "NO_RESET"
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"


class SubscriptionControllerGetSubscriptionByClientType(StrEnum):
    STASH = "stash"
    SINGBOX = "singbox"
    SINGBOX_LEGACY = "singbox-legacy"
    MIHOMO = "mihomo"
    JSON = "json"
    V2RAY_JSON = "v2ray-json"
    CLASH = "clash"


class TemplateTemplateType(StrEnum):
    STASH = "STASH"
    SINGBOX = "SINGBOX"
    SINGBOX_LEGACY = "SINGBOX_LEGACY"
    MIHOMO = "MIHOMO"
    XRAY_JSON = "XRAY_JSON"
    CLASH = "CLASH"


class HostSecurityLayer(StrEnum):
    DEFAULT = "DEFAULT"
    TLS = "TLS"
    NONE = "NONE"


class CreateHostRequestAlpn(StrEnum):
    H3 = "h3"
    H2 = "h2"
    HTTP_1_1 = "http/1.1"
    H2_HTTP_1_1 = "h2,http/1.1"
    H3_H2_HTTP_1_1 = "h3,h2,http/1.1"
    H3_H2 = "h3,h2"


class CreateHostRequestFingerprint(StrEnum):
    CHROME = "chrome"
    FIREFOX = "firefox"
    SAFARI = "safari"
    IOS = "ios"
    ANDROID = "android"
    EDGE = "edge"
    QQ = "qq"
    RANDOM = "random"
    RANDOMIZED = "randomized"
