# @generated by tools/codegen -- do not edit

from remnawave._generated.methods.api_tokens import (
    ApiTokensApi,
    AsyncApiTokensApi,
)
from remnawave._generated.methods.auth import (
    AsyncAuthApi,
    AuthApi,
)
from remnawave._generated.methods.bandwidth_stats import (
    AsyncBandwidthStatsApi,
    BandwidthStatsApi,
)
from remnawave._generated.methods.config_profiles import (
    AsyncConfigProfilesApi,
    ConfigProfilesApi,
)
from remnawave._generated.methods.hosts import (
    AsyncHostsApi,
    HostsApi,
)
from remnawave._generated.methods.hosts_bulk_actions import (
    AsyncHostsBulkActionsApi,
    HostsBulkActionsApi,
)
from remnawave._generated.methods.hwid_user_devices import (
    AsyncHwidUserDevicesApi,
    HwidUserDevicesApi,
)
from remnawave._generated.methods.infra_billing import (
    AsyncInfraBillingApi,
    InfraBillingApi,
)
from remnawave._generated.methods.internal_squads import (
    AsyncInternalSquadsApi,
    InternalSquadsApi,
)
from remnawave._generated.methods.keygen import (
    AsyncKeygenApi,
    KeygenApi,
)
from remnawave._generated.methods.nodes import (
    AsyncNodesApi,
    NodesApi,
)
from remnawave._generated.methods.subscription import (
    AsyncSubscriptionApi,
    SubscriptionApi,
)
from remnawave._generated.methods.subscription_request_history import (
    AsyncSubscriptionRequestHistoryApi,
    SubscriptionRequestHistoryApi,
)
from remnawave._generated.methods.subscription_settings import (
    AsyncSubscriptionSettingsApi,
    SubscriptionSettingsApi,
)
from remnawave._generated.methods.subscription_template import (
    AsyncSubscriptionTemplateApi,
    SubscriptionTemplateApi,
)
from remnawave._generated.methods.subscriptions import (
    AsyncSubscriptionsApi,
    SubscriptionsApi,
)
from remnawave._generated.methods.system import (
    AsyncSystemApi,
    SystemApi,
)
from remnawave._generated.methods.users import (
    AsyncUsersApi,
    UsersApi,
)
from remnawave._generated.methods.users_bulk_actions import (
    AsyncUsersBulkActionsApi,
    UsersBulkActionsApi,
)
from remnawave._generated.methods.users_stats import (
    AsyncUsersStatsApi,
    UsersStatsApi,
)
from remnawave.execution import AsyncExecutor, SyncExecutor


class SyncGroups:
    api_tokens: ApiTokensApi
    auth: AuthApi
    bandwidth_stats: BandwidthStatsApi
    config_profiles: ConfigProfilesApi
    hosts: HostsApi
    hosts_bulk_actions: HostsBulkActionsApi
    hwid_user_devices: HwidUserDevicesApi
    infra_billing: InfraBillingApi
    internal_squads: InternalSquadsApi
    keygen: KeygenApi
    nodes: NodesApi
    subscription: SubscriptionApi
    subscription_request_history: SubscriptionRequestHistoryApi
    subscription_settings: SubscriptionSettingsApi
    subscription_template: SubscriptionTemplateApi
    subscriptions: SubscriptionsApi
    system: SystemApi
    users: UsersApi
    users_bulk_actions: UsersBulkActionsApi
    users_stats: UsersStatsApi

    def _attach(self, executor: SyncExecutor) -> None:
        self.api_tokens = ApiTokensApi(executor)
        self.auth = AuthApi(executor)
        self.bandwidth_stats = BandwidthStatsApi(executor)
        self.config_profiles = ConfigProfilesApi(executor)
        self.hosts = HostsApi(executor)
        self.hosts_bulk_actions = HostsBulkActionsApi(executor)
        self.hwid_user_devices = HwidUserDevicesApi(executor)
        self.infra_billing = InfraBillingApi(executor)
        self.internal_squads = InternalSquadsApi(executor)
        self.keygen = KeygenApi(executor)
        self.nodes = NodesApi(executor)
        self.subscription = SubscriptionApi(executor)
        self.subscription_request_history = SubscriptionRequestHistoryApi(
            executor
        )
        self.subscription_settings = SubscriptionSettingsApi(executor)
        self.subscription_template = SubscriptionTemplateApi(executor)
        self.subscriptions = SubscriptionsApi(executor)
        self.system = SystemApi(executor)
        self.users = UsersApi(executor)
        self.users_bulk_actions = UsersBulkActionsApi(executor)
        self.users_stats = UsersStatsApi(executor)


class AsyncGroups:
    api_tokens: AsyncApiTokensApi
    auth: AsyncAuthApi
    bandwidth_stats: AsyncBandwidthStatsApi
    config_profiles: AsyncConfigProfilesApi
    hosts: AsyncHostsApi
    hosts_bulk_actions: AsyncHostsBulkActionsApi
    hwid_user_devices: AsyncHwidUserDevicesApi
    infra_billing: AsyncInfraBillingApi
    internal_squads: AsyncInternalSquadsApi
    keygen: AsyncKeygenApi
    nodes: AsyncNodesApi
    subscription: AsyncSubscriptionApi
    subscription_request_history: AsyncSubscriptionRequestHistoryApi
    subscription_settings: AsyncSubscriptionSettingsApi
    subscription_template: AsyncSubscriptionTemplateApi
    subscriptions: AsyncSubscriptionsApi
    system: AsyncSystemApi
    users: AsyncUsersApi
    users_bulk_actions: AsyncUsersBulkActionsApi
    users_stats: AsyncUsersStatsApi

    def _attach(self, executor: AsyncExecutor) -> None:
        self.api_tokens = AsyncApiTokensApi(executor)
        self.auth = AsyncAuthApi(executor)
        self.bandwidth_stats = AsyncBandwidthStatsApi(executor)
        self.config_profiles = AsyncConfigProfilesApi(executor)
        self.hosts = AsyncHostsApi(executor)
        self.hosts_bulk_actions = AsyncHostsBulkActionsApi(executor)
        self.hwid_user_devices = AsyncHwidUserDevicesApi(executor)
        self.infra_billing = AsyncInfraBillingApi(executor)
        self.internal_squads = AsyncInternalSquadsApi(executor)
        self.keygen = AsyncKeygenApi(executor)
        self.nodes = AsyncNodesApi(executor)
        self.subscription = AsyncSubscriptionApi(executor)
        self.subscription_request_history = AsyncSubscriptionRequestHistoryApi(
            executor
        )
        self.subscription_settings = AsyncSubscriptionSettingsApi(executor)
        self.subscription_template = AsyncSubscriptionTemplateApi(executor)
        self.subscriptions = AsyncSubscriptionsApi(executor)
        self.system = AsyncSystemApi(executor)
        self.users = AsyncUsersApi(executor)
        self.users_bulk_actions = AsyncUsersBulkActionsApi(executor)
        self.users_stats = AsyncUsersStatsApi(executor)
