# @generated by tools/codegen -- do not edit
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from adaptix import Omittable, Omitted

from remnawave._generated.enums import (
    ApiTokenScopesResourceEndpointKind,
    BulkNodesActionsBodyAction,
    CrmEventName,
    HostAlpn,
    HostInternalSquadMode,
    HostMihomoIpVersion,
    HostSecurityLayer,
    NodeEventName,
    NodeIpStatus,
    OAuth2CallbackBodyProvider,
    ServiceEventDataSubpageConfigAction,
    ServiceEventName,
    SrrMatcherMatchedRuleConditionOperator,
    SrrMatcherMatchedRuleOperator,
    SrrMatcherMatchedRuleResponseModificationEncryptionMethod,
    SrrMatcherResponseType,
    TemplateType,
    UpdateUserBodyStatus,
    UserEventName,
    UserHwidDevicesEventName,
    UserStatus,
    UserTrafficLimitStrategy,
)

OMITTED = Omitted()


@dataclass(slots=True)
class RemnawaveSettingsPasskeySetting:
    enabled: bool
    rp_id: str | None
    origin: str | None


@dataclass(slots=True)
class RemnawaveSettingsOauth2SettingGithub:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    allowed_emails: list[str]


@dataclass(slots=True)
class RemnawaveSettingsOauth2SettingPocketid:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    frontend_domain: str | None
    plain_domain: str | None
    allowed_emails: list[str]


@dataclass(slots=True)
class RemnawaveSettingsOauth2SettingKeycloak:
    enabled: bool
    realm: str | None
    client_id: str | None
    client_secret: str | None
    frontend_domain: str | None
    keycloak_domain: str | None
    allowed_emails: list[str]


@dataclass(slots=True)
class RemnawaveSettingsOauth2SettingGeneric:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    with_pkce: bool
    authorization_url: str | None
    token_url: str | None
    frontend_domain: str | None
    allowed_emails: list[str]


@dataclass(slots=True)
class RemnawaveSettingsOauth2SettingTelegram:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    allowed_ids: list[str]
    frontend_domain: str | None


@dataclass(slots=True)
class RemnawaveSettingsOauth2Setting:
    github: RemnawaveSettingsOauth2SettingGithub
    pocketid: RemnawaveSettingsOauth2SettingPocketid
    yandex: RemnawaveSettingsOauth2SettingGithub
    keycloak: RemnawaveSettingsOauth2SettingKeycloak | None = None
    generic: RemnawaveSettingsOauth2SettingGeneric | None = None
    telegram: RemnawaveSettingsOauth2SettingTelegram | None = None


@dataclass(slots=True)
class StatusAuthenticationPasskey:
    enabled: bool


@dataclass(slots=True)
class StatusBranding:
    title: str | None
    logo_url: str | None


@dataclass(slots=True)
class RemnawaveSettings:
    passkey_settings: RemnawaveSettingsPasskeySetting | None
    oauth2_settings: RemnawaveSettingsOauth2Setting | None
    password_settings: StatusAuthenticationPasskey | None
    branding_settings: StatusBranding | None


@dataclass(slots=True)
class UpdateRemnawaveSettingsBodyOauth2Setting:
    github: RemnawaveSettingsOauth2SettingGithub
    pocketid: RemnawaveSettingsOauth2SettingPocketid
    yandex: RemnawaveSettingsOauth2SettingGithub
    keycloak: Omittable[RemnawaveSettingsOauth2SettingKeycloak] = OMITTED
    generic: Omittable[RemnawaveSettingsOauth2SettingGeneric] = OMITTED
    telegram: Omittable[RemnawaveSettingsOauth2SettingTelegram] = OMITTED


@dataclass(slots=True)
class UpdateRemnawaveSettingsBody:
    passkey_settings: Omittable[RemnawaveSettingsPasskeySetting] = OMITTED
    oauth2_settings: Omittable[UpdateRemnawaveSettingsBodyOauth2Setting] = (
        OMITTED
    )
    password_settings: Omittable[StatusAuthenticationPasskey] = OMITTED
    branding_settings: Omittable[StatusBranding] = OMITTED


@dataclass(slots=True)
class VerifyPasskeyRegistration:
    verified: bool


@dataclass(slots=True)
class VerifyPasskeyRegistrationBody:
    response: Any


@dataclass(slots=True)
class Passkey:
    id: str
    name: str
    created_at: datetime
    last_used_at: datetime


@dataclass(slots=True)
class Passkeys:
    passkeys: list[Passkey]


@dataclass(slots=True)
class DeletePasskeyBody:
    id: str


@dataclass(slots=True)
class UpdatePasskeyBody:
    id: str
    name: str


@dataclass(slots=True)
class Login:
    access_token: str


@dataclass(slots=True)
class LoginBody:
    username: str
    password: str


@dataclass(slots=True)
class StatusAuthenticationOauth2:
    providers: dict[str, Any]


@dataclass(slots=True)
class StatusAuthentication:
    passkey: StatusAuthenticationPasskey
    oauth2: StatusAuthenticationOauth2
    password: StatusAuthenticationPasskey


@dataclass(slots=True)
class Status:
    is_login_allowed: bool
    is_register_allowed: bool
    authentication: StatusAuthentication | None
    branding: StatusBranding


@dataclass(slots=True)
class OAuth2Authorize:
    authorization_url: str | None


@dataclass(slots=True)
class OAuth2AuthorizeBody:
    provider: OAuth2CallbackBodyProvider


@dataclass(slots=True)
class OAuth2CallbackBody:
    provider: OAuth2CallbackBodyProvider
    code: str
    state: str


@dataclass(slots=True)
class Tags:
    tags: list[str]


@dataclass(slots=True)
class NodePluginsTags:
    uuid: UUID
    tags: list[str]


@dataclass(slots=True)
class SubpageConfig:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    config: Any


@dataclass(slots=True)
class SubpageConfigs:
    total: int
    configs: list[SubpageConfig]


@dataclass(slots=True)
class UpdateSubpageConfigBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    config: Omittable[Any] = OMITTED


@dataclass(slots=True)
class SyncSnippetBody:
    name: str


@dataclass(slots=True)
class ReorderItem:
    view_position: int
    uuid: UUID


@dataclass(slots=True)
class ReorderBody:
    items: list[ReorderItem]


@dataclass(slots=True)
class CloneHostBody:
    clone_from_uuid: UUID


@dataclass(slots=True)
class UserActiveInternalSquad:
    uuid: UUID
    name: str


@dataclass(slots=True)
class UserTraffic:
    used_traffic_bytes: int
    lifetime_used_traffic_bytes: int
    online_at: datetime | None
    first_connected_at: datetime | None
    last_connected_node_uuid: UUID | None


@dataclass(slots=True)
class User:
    id: int
    short_uuid: str
    username: str
    status: UserStatus
    traffic_limit_bytes: int
    traffic_limit_strategy: UserTrafficLimitStrategy
    expire_at: datetime
    telegram_id: int | None
    email: str | None
    description: str | None
    tag: str | None
    hwid_device_limit: int | None
    external_squad_uuid: UUID | None
    trojan_password: str = field(repr=False)
    vless_uuid: UUID = field(repr=False)
    ss_password: str = field(repr=False)
    last_triggered_threshold: int
    sub_revoked_at: datetime | None
    last_traffic_reset_at: datetime | None
    created_at: datetime
    updated_at: datetime
    subscription_url: str = field(repr=False)
    active_internal_squads: list[UserActiveInternalSquad]
    user_traffic: UserTraffic


@dataclass(slots=True)
class CreateUserBody:
    username: str
    expire_at: datetime
    status: Omittable[UserStatus] = OMITTED
    short_uuid: Omittable[str] = OMITTED
    trojan_password: Omittable[str] = OMITTED
    vless_uuid: Omittable[UUID] = OMITTED
    ss_password: Omittable[str] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    created_at: Omittable[datetime] = OMITTED
    last_traffic_reset_at: Omittable[datetime] = OMITTED
    description: Omittable[str] = OMITTED
    tag: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int] = OMITTED
    active_internal_squads: Omittable[list[UUID]] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(slots=True)
class UpdateUserBody:
    username: Omittable[str] = OMITTED
    id: Omittable[int] = OMITTED
    status: Omittable[UpdateUserBodyStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED
    active_internal_squads: Omittable[list[UUID]] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(slots=True)
class Filter:
    id: str
    value: Any


@dataclass(slots=True)
class Sorting:
    id: str
    desc: bool


@dataclass(slots=True)
class Users:
    users: list[User]
    total: int


@dataclass(slots=True)
class UsersStream:
    users: list[User]
    next_cursor: str | None
    has_more: bool


@dataclass(slots=True)
class UserAccessibleNodesActiveNodeActiveSquad:
    squad_name: str
    active_inbounds: list[str]


@dataclass(slots=True)
class UserAccessibleNodesActiveNode:
    uuid: UUID
    node_name: str
    country_code: str
    config_profile_uuid: UUID
    config_profile_name: str
    active_squads: list[UserAccessibleNodesActiveNodeActiveSquad]


@dataclass(slots=True)
class UserAccessibleNodes:
    user_id: int
    active_nodes: list[UserAccessibleNodesActiveNode]


@dataclass(slots=True)
class UserSubscriptionRequestHistoryRecord:
    id: int
    user_id: int
    request_at: datetime
    srr_response_type: str
    request_ip: str | None = None
    user_agent: str | None = None
    srr_rule_name: str | None = None


@dataclass(slots=True)
class UserSubscriptionRequestHistory:
    total: int
    records: list[UserSubscriptionRequestHistoryRecord]


@dataclass(slots=True)
class RevokeUserSubscriptionBody:
    revoke_only_passwords: Omittable[bool] = OMITTED
    short_uuid: Omittable[str] = OMITTED


@dataclass(slots=True)
class ExtendUserBody:
    days: int


@dataclass(slots=True)
class UserRef:
    id: int
    username: str
    short_uuid: str


@dataclass(slots=True)
class ResolveUserBody:
    id: Omittable[int] = OMITTED
    short_uuid: Omittable[str] = OMITTED
    username: Omittable[str] = OMITTED


@dataclass(slots=True)
class BulkDeleteUsersByStatusBody:
    status: UserStatus


@dataclass(slots=True)
class BulkDeleteUsersBody:
    user_ids: list[int]


@dataclass(slots=True)
class BulkUpdateUsersBodyField:
    status: Omittable[UserStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(slots=True)
class BulkUpdateUsersBody:
    user_ids: list[int]
    fields: BulkUpdateUsersBodyField


@dataclass(slots=True)
class BulkUpdateUsersSquadsBody:
    user_ids: list[int]
    active_internal_squads: list[UUID]


@dataclass(slots=True)
class BulkExtendExpirationDateBody:
    user_ids: list[int]
    extend_days: int


@dataclass(slots=True)
class BulkAllUpdateUsersBody:
    status: Omittable[UserStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED


@dataclass(slots=True)
class BulkAllExtendExpirationDateBody:
    extend_days: int


@dataclass(slots=True)
class SubscriptionUser:
    short_uuid: str
    days_left: int
    traffic_used: str
    traffic_limit: str
    lifetime_traffic_used: str
    traffic_used_bytes: str
    traffic_limit_bytes: str
    lifetime_traffic_used_bytes: str
    username: str
    expires_at: datetime
    is_active: bool
    user_status: UserStatus
    traffic_limit_strategy: UserTrafficLimitStrategy


@dataclass(slots=True)
class Subscription:
    is_found: bool
    user: SubscriptionUser
    links: list[str]
    ss_conf_links: dict[str, Any]
    subscription_url: str


@dataclass(slots=True)
class Subscriptions:
    subscriptions: list[Subscription]
    total: int


@dataclass(slots=True)
class RawSubscriptionByShortUuidConvertedUserInfoHwidCheckup:
    subscription_allowed: bool
    max_device_reached: bool
    hwid_not_supported: bool
    limit_bypassed: bool


@dataclass(slots=True)
class RawSubscriptionByShortUuidConvertedUserInfo:
    days_left: int
    traffic_limit: str
    traffic_used: str
    lifetime_traffic_used: str
    hwid_checkup: RawSubscriptionByShortUuidConvertedUserInfoHwidCheckup | None


@dataclass(slots=True)
class RawSubscriptionByShortUuidResolvedProxyConfigStreamOverride:
    final_mask: Any
    sockopt: Any


@dataclass(slots=True)
class HostMapper:
    xray_json: list[Any] | None = None
    mihomo: list[Any] | None = None
    base64: list[Any] | None = None
    singbox: list[Any] | None = None


@dataclass(slots=True)
class RawSubscriptionByShortUuidResolvedProxyConfigClientOverride:
    shuffle_host: bool
    mihomo_x25519: bool
    mihomo_ip_version: HostMihomoIpVersion | None
    server_description: str | None
    xray_json_template: Any
    mapper: HostMapper


@dataclass(slots=True)
class RawSubscriptionByShortUuidResolvedProxyConfigMetadata:
    uuid: UUID
    tags: list[str]
    exclude_from_subscription_types: list[TemplateType]
    inbound_tag: str
    config_profile_uuid: UUID | None
    config_profile_inbound_uuid: UUID | None
    is_disabled: bool
    is_hidden: bool
    view_position: int
    remark: str
    vless_route_id: int | None
    raw_inbound: Any


@dataclass(slots=True)
class RawSubscriptionByShortUuidResolvedProxyConfig:
    final_remark: str
    address: str
    port: int
    stream_overrides: (
        RawSubscriptionByShortUuidResolvedProxyConfigStreamOverride
    )
    mux: Any
    client_overrides: (
        RawSubscriptionByShortUuidResolvedProxyConfigClientOverride
    )
    metadata: RawSubscriptionByShortUuidResolvedProxyConfigMetadata


@dataclass(slots=True)
class RawSubscriptionByShortUuid:
    user: User
    converted_user_info: RawSubscriptionByShortUuidConvertedUserInfo
    headers: dict[str, Any]
    resolved_proxy_configs: list[RawSubscriptionByShortUuidResolvedProxyConfig]


@dataclass(slots=True)
class SubpageConfigByShortUuid:
    subpage_config_uuid: UUID | None
    webpage_allowed: bool


@dataclass(slots=True)
class GetSubpageConfigByShortUuidBody:
    request_headers: dict[str, Any]


@dataclass(slots=True)
class ConnectionKeysByUserId:
    enabled_keys: list[str]
    hidden_keys: list[str]
    disabled_keys: list[str]


@dataclass(slots=True)
class Template:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    template_type: TemplateType
    template_json: Any
    encoded_template_yaml: str | None


@dataclass(slots=True)
class Templates:
    total: int
    templates: list[Template]


@dataclass(slots=True)
class UpdateTemplateBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    template_json: Omittable[dict[str, Any]] = OMITTED
    encoded_template_yaml: Omittable[str] = OMITTED


@dataclass(slots=True)
class CreateSubscriptionTemplateBody:
    name: str
    template_type: TemplateType


@dataclass(slots=True)
class ApiToken:
    uuid: UUID
    name: str
    expire_at: datetime
    scopes: list[str]
    created_at: datetime
    updated_at: datetime
    token: str


@dataclass(slots=True)
class CreateApiTokenBody:
    name: str
    expires_in_days: int
    scopes: Omittable[list[str]] = OMITTED


@dataclass(slots=True)
class ApiTokensToken:
    uuid: UUID
    name: str
    expire_at: datetime
    scopes: list[str]
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class ApiTokens:
    tokens: list[ApiTokensToken]


@dataclass(slots=True)
class ApiTokenScopesResourceEndpoint:
    key: str
    kind: ApiTokenScopesResourceEndpointKind
    method: str
    path: str
    description: str


@dataclass(slots=True)
class ApiTokenScopesResource:
    resource: str
    resource_scopes: list[str]
    endpoints: list[ApiTokenScopesResourceEndpoint]


@dataclass(slots=True)
class ApiTokenScopes:
    wildcard: str
    resources: list[ApiTokenScopesResource]


@dataclass(slots=True)
class ConfigProfileInbound:
    uuid: UUID
    profile_uuid: UUID
    tag: str
    type: str
    network: str | None
    security: str | None
    port: int | None
    raw_inbound: Any


@dataclass(slots=True)
class RecordNode:
    uuid: UUID
    name: str
    country_code: str


@dataclass(slots=True)
class ConfigProfile:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    config: Any
    inbounds: list[ConfigProfileInbound]
    nodes: list[RecordNode]
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class ConfigProfiles:
    total: int
    config_profiles: list[ConfigProfile]


@dataclass(slots=True)
class SharedList:
    name: str
    config: dict[str, Any]


@dataclass(slots=True)
class UpdateConfigProfileBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    config: Omittable[dict[str, Any]] = OMITTED


@dataclass(slots=True)
class InboundsInbound:
    uuid: UUID
    profile_uuid: UUID
    tag: str
    type: str
    network: str | None
    security: str | None
    port: int | None
    raw_inbound: Any
    active_squads: list[UUID]


@dataclass(slots=True)
class Inbounds:
    total: int
    inbounds: list[InboundsInbound]


@dataclass(slots=True)
class Snippet:
    name: str
    snippet: Any


@dataclass(slots=True)
class Snippets:
    total: int
    snippets: list[Snippet]


@dataclass(slots=True)
class CreateSnippetBody:
    name: str
    snippet: list[dict[str, Any]]


@dataclass(slots=True)
class InternalSquadInfo:
    members_count: int
    inbounds_count: int


@dataclass(slots=True)
class InternalSquad:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    info: InternalSquadInfo
    inbounds: list[ConfigProfileInbound]
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class InternalSquads:
    total: int
    internal_squads: list[InternalSquad]


@dataclass(slots=True)
class CreateInternalSquadBody:
    name: str
    inbounds: list[UUID]


@dataclass(slots=True)
class UpdateInternalSquadBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    inbounds: Omittable[list[UUID]] = OMITTED


@dataclass(slots=True)
class InternalSquadAccessibleNodesAccessibleNode:
    uuid: UUID
    node_name: str
    country_code: str
    config_profile_uuid: UUID
    config_profile_name: str
    active_inbounds: list[str]


@dataclass(slots=True)
class InternalSquadAccessibleNodes:
    squad_uuid: UUID
    accessible_nodes: list[InternalSquadAccessibleNodesAccessibleNode]


@dataclass(slots=True)
class NodeUsageNodeUser:
    id: int
    total_bytes: int


@dataclass(slots=True)
class InternalSquadUsage:
    squad_uuid: UUID
    users: list[NodeUsageNodeUser]
    next_cursor: str | None
    has_more: bool


@dataclass(slots=True)
class InternalSquadUserUsageDayNode:
    uuid: UUID
    total_bytes: int


@dataclass(slots=True)
class InternalSquadUserUsageDay:
    date: str
    nodes: list[InternalSquadUserUsageDayNode]


@dataclass(slots=True)
class InternalSquadUserUsage:
    days: list[InternalSquadUserUsageDay]


@dataclass(slots=True)
class ExternalSquadInfo:
    members_count: int


@dataclass(slots=True)
class ExternalSquadTemplate:
    template_uuid: UUID
    template_type: TemplateType


@dataclass(slots=True)
class ExternalSquadSubscriptionSetting:
    serve_json_at_base_subscription: bool | None = None
    is_show_custom_remarks: bool | None = None
    randomize_hosts: bool | None = None


@dataclass(slots=True)
class ExternalSquadHostOverride:
    server_description: str | None = None
    vless_route_id: int | None = None


@dataclass(slots=True)
class ExternalSquadHwidSetting:
    enabled: bool
    fallback_device_limit: int
    max_devices_announce: str | None


@dataclass(slots=True)
class ExternalSquadCustomRemark:
    expired_users: list[str]
    limited_users: list[str]
    disabled_users: list[str]
    empty_hosts: list[str]
    hwid_max_devices_exceeded: list[str]
    hwid_not_supported: list[str]


@dataclass(slots=True)
class ExternalSquad:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    info: ExternalSquadInfo
    templates: list[ExternalSquadTemplate]
    subscription_settings: ExternalSquadSubscriptionSetting | None
    host_overrides: ExternalSquadHostOverride | None
    response_headers_add: dict[str, Any]
    response_headers_remove: list[str]
    hwid_settings: ExternalSquadHwidSetting | None
    custom_remarks: ExternalSquadCustomRemark | None
    subpage_config_uuid: UUID | None
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class ExternalSquads:
    total: int
    external_squads: list[ExternalSquad]


@dataclass(slots=True)
class UpdateExternalSquadBodySubscriptionSetting:
    serve_json_at_base_subscription: Omittable[bool] = OMITTED
    is_show_custom_remarks: Omittable[bool] = OMITTED
    randomize_hosts: Omittable[bool] = OMITTED


@dataclass(slots=True)
class UpdateExternalSquadBodyHostOverride:
    server_description: Omittable[str | None] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED


@dataclass(slots=True)
class UpdateExternalSquadBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    templates: Omittable[list[ExternalSquadTemplate]] = OMITTED
    subscription_settings: Omittable[
        UpdateExternalSquadBodySubscriptionSetting
    ] = OMITTED
    host_overrides: Omittable[UpdateExternalSquadBodyHostOverride] = OMITTED
    response_headers_add: Omittable[dict[str, Any]] = OMITTED
    response_headers_remove: Omittable[list[str]] = OMITTED
    hwid_settings: Omittable[ExternalSquadHwidSetting | None] = OMITTED
    custom_remarks: Omittable[ExternalSquadCustomRemark | None] = OMITTED
    subpage_config_uuid: Omittable[UUID | None] = OMITTED


@dataclass(slots=True)
class NodeSecretKey:
    secret_key: str


@dataclass(slots=True)
class NodeIp:
    ip: str
    status: NodeIpStatus


@dataclass(slots=True)
class NodeConfigProfile:
    active_config_profile_uuid: UUID | None
    active_inbounds: list[ConfigProfileInbound]


@dataclass(slots=True)
class NodeProvider:
    uuid: UUID
    name: str
    favicon_link: str | None
    login_url: str | None
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class NodeSystemInfo:
    arch: str
    cpus: int
    cpu_model: str
    memory_total: int
    hostname: str
    platform: str
    release: str
    type: str
    version: str
    network_interfaces: list[str]


@dataclass(slots=True)
class NodeSystemStatInterface:
    interface: str
    rx_bytes_per_sec: float
    tx_bytes_per_sec: float
    rx_total: int
    tx_total: int


@dataclass(slots=True)
class NodeSystemStat:
    memory_free: int
    memory_used: int
    uptime: float
    load_avg: list[float]
    interface: NodeSystemStatInterface | None


@dataclass(slots=True)
class NodeSystem:
    info: NodeSystemInfo
    stats: NodeSystemStat


@dataclass(slots=True)
class NodeVersion:
    xray: str
    node: str


@dataclass(slots=True)
class Node:
    uuid: UUID
    id: int
    name: str
    address: str
    port: int | None
    proxy_url: str | None
    is_connected: bool
    is_disabled: bool
    is_connecting: bool
    last_status_change: datetime | None
    last_status_message: str | None
    is_traffic_tracking_active: bool
    traffic_reset_day: int | None
    traffic_limit_bytes: int | None
    traffic_used_bytes: int | None
    notify_percent: int | None
    view_position: int
    country_code: str
    consumption_multiplier: float
    node_consumption_multiplier: float
    tags: list[str]
    integration_uuids: list[UUID]
    ips: list[NodeIp]
    created_at: datetime
    updated_at: datetime
    config_profile: NodeConfigProfile
    provider_uuid: UUID | None
    provider: NodeProvider | None
    active_plugin_uuid: UUID | None
    system: NodeSystem | None
    versions: NodeVersion | None
    xray_uptime: int
    users_online: int
    note: str | None


@dataclass(slots=True)
class CreateNodeBodyConfigProfile:
    active_config_profile_uuid: UUID
    active_inbounds: list[UUID]


@dataclass(slots=True)
class CreateNodeBody:
    name: str
    address: str
    config_profile: CreateNodeBodyConfigProfile
    port: Omittable[int] = OMITTED
    proxy_url: Omittable[str | None] = OMITTED
    is_traffic_tracking_active: Omittable[bool] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    notify_percent: Omittable[int] = OMITTED
    traffic_reset_day: Omittable[int] = OMITTED
    country_code: Omittable[str] = OMITTED
    consumption_multiplier: Omittable[float] = OMITTED
    node_consumption_multiplier: Omittable[float] = OMITTED
    provider_uuid: Omittable[UUID | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    active_plugin_uuid: Omittable[UUID | None] = OMITTED
    integration_uuids: Omittable[list[UUID]] = OMITTED
    note: Omittable[str] = OMITTED
    ips: Omittable[list[NodeIp]] = OMITTED


@dataclass(slots=True)
class UpdateNodeBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    address: Omittable[str] = OMITTED
    port: Omittable[int] = OMITTED
    proxy_url: Omittable[str | None] = OMITTED
    is_traffic_tracking_active: Omittable[bool] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    notify_percent: Omittable[int] = OMITTED
    traffic_reset_day: Omittable[int] = OMITTED
    country_code: Omittable[str] = OMITTED
    consumption_multiplier: Omittable[float] = OMITTED
    node_consumption_multiplier: Omittable[float] = OMITTED
    config_profile: Omittable[CreateNodeBodyConfigProfile] = OMITTED
    provider_uuid: Omittable[UUID | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    active_plugin_uuid: Omittable[UUID | None] = OMITTED
    integration_uuids: Omittable[list[UUID]] = OMITTED
    note: Omittable[str | None] = OMITTED
    ips: Omittable[list[NodeIp]] = OMITTED


@dataclass(slots=True)
class RestartNodeBody:
    force_restart: bool


@dataclass(slots=True)
class ReorderNodesBody:
    nodes: list[ReorderItem]


@dataclass(slots=True)
class ProfileModificationBody:
    uuids: list[UUID]
    config_profile: CreateNodeBodyConfigProfile


@dataclass(slots=True)
class BulkNodesActionsBody:
    uuids: list[UUID]
    action: BulkNodesActionsBodyAction


@dataclass(slots=True)
class BulkNodesUpdateBodyField:
    country_code: Omittable[str] = OMITTED
    consumption_multiplier: Omittable[float] = OMITTED
    node_consumption_multiplier: Omittable[float] = OMITTED
    provider_uuid: Omittable[UUID | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    active_plugin_uuid: Omittable[UUID | None] = OMITTED
    integration_uuids: Omittable[list[UUID]] = OMITTED
    note: Omittable[str | None] = OMITTED


@dataclass(slots=True)
class BulkNodesUpdateBody:
    uuids: list[UUID]
    fields: BulkNodesUpdateBodyField


@dataclass(slots=True)
class RecordUser:
    username: str


@dataclass(slots=True)
class RecordReportActionReport:
    blocked: bool
    ip: str
    block_duration: int
    will_unblock_at: datetime
    user_id: str
    processed_at: datetime


@dataclass(slots=True)
class RecordReportXrayReport:
    email: str | None
    level: int | None
    protocol: str | None
    network: str
    source: str | None
    destination: str
    route_target: str | None
    original_target: str | None
    inbound_tag: str | None
    inbound_name: str | None
    inbound_local: str | None
    outbound_tag: str | None
    ts: int


@dataclass(slots=True)
class RecordReport:
    action_report: RecordReportActionReport
    xray_report: RecordReportXrayReport


@dataclass(slots=True)
class Record:
    id: int
    user_id: int
    node_id: int
    user: RecordUser
    node: RecordNode
    report: RecordReport
    created_at: datetime


@dataclass(slots=True)
class TorrentBlockerReports:
    records: list[Record]
    total: int


@dataclass(slots=True)
class TorrentBlockerReportsStatsStat:
    distinct_nodes: int
    distinct_users: int
    total_reports: int
    reports_last24_hours: int


@dataclass(slots=True)
class TorrentBlockerReportsStatsTopUser:
    user_id: int
    color: str
    username: str
    total: int


@dataclass(slots=True)
class TorrentBlockerReportsStatsTopNode:
    uuid: UUID
    country_code: str
    color: str
    name: str
    total: int


@dataclass(slots=True)
class TorrentBlockerReportsStats:
    stats: TorrentBlockerReportsStatsStat
    top_users: list[TorrentBlockerReportsStatsTopUser]
    top_nodes: list[TorrentBlockerReportsStatsTopNode]


@dataclass(slots=True)
class SharedListsSharedList:
    name: str
    type: str
    items_count: int


@dataclass(slots=True)
class SharedLists:
    total: int
    shared_lists: list[SharedListsSharedList]


@dataclass(slots=True)
class NodePlugin:
    uuid: UUID
    view_position: int
    name: str
    tags: list[str]
    plugin_config: Any


@dataclass(slots=True)
class NodePlugins:
    total: int
    node_plugins: list[NodePlugin]


@dataclass(slots=True)
class UpdateNodePluginBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    plugin_config: Omittable[Any] = OMITTED


@dataclass(slots=True)
class SyncNodePluginBody:
    uuid: UUID


@dataclass(slots=True)
class PluginExecutorBody:
    command: Any
    target_nodes: Any


@dataclass(slots=True)
class NodeIntegration:
    uuid: UUID
    name: str
    description: str | None
    config: dict[str, Any]


@dataclass(slots=True)
class NodeIntegrations:
    total: int
    node_integrations: list[NodeIntegration]


@dataclass(slots=True)
class CreateNodeIntegrationBody:
    name: str
    config: dict[str, Any]
    description: Omittable[str | None] = OMITTED


@dataclass(slots=True)
class UpdateNodeIntegrationBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    description: Omittable[str | None] = OMITTED
    config: Omittable[dict[str, Any]] = OMITTED
    restart_nodes: Omittable[bool] = OMITTED


@dataclass(slots=True)
class HostInbound:
    config_profile_uuid: UUID | None
    config_profile_inbound_uuid: UUID | None


@dataclass(slots=True)
class HostInternalSquad:
    mode: HostInternalSquadMode
    squads: list[UUID]


@dataclass(slots=True)
class Host:
    uuid: UUID
    view_position: int
    remark: str
    address: str
    port: int
    path: str | None
    sni: str | None
    host: str | None
    alpn: HostAlpn | None
    fingerprint: str | None
    is_disabled: bool
    xhttp_extra_params: Any
    mux_params: Any
    sockopt_params: Any
    final_mask: Any
    inbound: HostInbound
    server_description: str | None
    vless_route_id: int | None
    pinned_peer_cert_sha256: str | None
    verify_peer_cert_by_name: str | None
    shuffle_host: bool
    mihomo_x25519: bool
    mihomo_ip_version: HostMihomoIpVersion | None
    nodes: list[UUID]
    xray_json_template_uuid: UUID | None
    exclude_from_subscription_types: list[TemplateType]
    mapper: HostMapper
    internal_squads: HostInternalSquad
    security_layer: HostSecurityLayer | None = None
    tags: list[str] | None = None
    is_hidden: bool | None = None
    override_sni_from_address: bool | None = None
    keep_sni_blank: bool | None = None


@dataclass(slots=True)
class CreateHostBodyInbound:
    config_profile_uuid: UUID
    config_profile_inbound_uuid: UUID


@dataclass(slots=True)
class CreateHostBodyMapper:
    xray_json: Omittable[list[Any]] = OMITTED
    mihomo: Omittable[list[Any]] = OMITTED
    base64: Omittable[list[Any]] = OMITTED
    singbox: Omittable[list[Any]] = OMITTED


@dataclass(slots=True)
class CreateHostBody:
    inbound: CreateHostBodyInbound
    remark: str
    address: str
    port: int
    path: Omittable[str | None] = OMITTED
    sni: Omittable[str | None] = OMITTED
    host: Omittable[str | None] = OMITTED
    alpn: Omittable[HostAlpn | None] = OMITTED
    fingerprint: Omittable[str | None] = OMITTED
    is_disabled: Omittable[bool] = OMITTED
    security_layer: Omittable[HostSecurityLayer] = OMITTED
    xhttp_extra_params: Omittable[Any] = OMITTED
    mux_params: Omittable[Any] = OMITTED
    sockopt_params: Omittable[Any] = OMITTED
    final_mask: Omittable[Any] = OMITTED
    server_description: Omittable[str | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    is_hidden: Omittable[bool] = OMITTED
    override_sni_from_address: Omittable[bool] = OMITTED
    keep_sni_blank: Omittable[bool] = OMITTED
    pinned_peer_cert_sha256: Omittable[str | None] = OMITTED
    verify_peer_cert_by_name: Omittable[str | None] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED
    shuffle_host: Omittable[bool] = OMITTED
    mihomo_x25519: Omittable[bool] = OMITTED
    mihomo_ip_version: Omittable[HostMihomoIpVersion | None] = OMITTED
    nodes: Omittable[list[UUID]] = OMITTED
    xray_json_template_uuid: Omittable[UUID | None] = OMITTED
    exclude_from_subscription_types: Omittable[list[TemplateType]] = OMITTED
    mapper: Omittable[CreateHostBodyMapper] = OMITTED
    internal_squads: Omittable[HostInternalSquad] = OMITTED


@dataclass(slots=True)
class UpdateHostBody:
    uuid: UUID
    inbound: Omittable[CreateHostBodyInbound] = OMITTED
    remark: Omittable[str] = OMITTED
    address: Omittable[str] = OMITTED
    port: Omittable[int] = OMITTED
    path: Omittable[str | None] = OMITTED
    sni: Omittable[str | None] = OMITTED
    host: Omittable[str | None] = OMITTED
    alpn: Omittable[HostAlpn | None] = OMITTED
    fingerprint: Omittable[str | None] = OMITTED
    is_disabled: Omittable[bool] = OMITTED
    security_layer: Omittable[HostSecurityLayer] = OMITTED
    xhttp_extra_params: Omittable[Any] = OMITTED
    mux_params: Omittable[Any] = OMITTED
    sockopt_params: Omittable[Any] = OMITTED
    final_mask: Omittable[Any] = OMITTED
    server_description: Omittable[str | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    is_hidden: Omittable[bool] = OMITTED
    override_sni_from_address: Omittable[bool] = OMITTED
    keep_sni_blank: Omittable[bool] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED
    pinned_peer_cert_sha256: Omittable[str | None] = OMITTED
    verify_peer_cert_by_name: Omittable[str | None] = OMITTED
    shuffle_host: Omittable[bool] = OMITTED
    mihomo_x25519: Omittable[bool] = OMITTED
    mihomo_ip_version: Omittable[HostMihomoIpVersion | None] = OMITTED
    nodes: Omittable[list[UUID]] = OMITTED
    xray_json_template_uuid: Omittable[UUID | None] = OMITTED
    exclude_from_subscription_types: Omittable[list[TemplateType]] = OMITTED
    mapper: Omittable[CreateHostBodyMapper] = OMITTED
    internal_squads: Omittable[HostInternalSquad] = OMITTED


@dataclass(slots=True)
class Hosts:
    is_updated: bool


@dataclass(slots=True)
class ReorderHostsBody:
    hosts: list[ReorderItem]


@dataclass(slots=True)
class BulkDeleteHostsBody:
    uuids: list[UUID]


@dataclass(slots=True)
class UpdateManyHostsBody:
    uuids: list[UUID]
    inbound: Omittable[CreateHostBodyInbound] = OMITTED
    remark: Omittable[str] = OMITTED
    address: Omittable[str] = OMITTED
    port: Omittable[int] = OMITTED
    path: Omittable[str | None] = OMITTED
    sni: Omittable[str | None] = OMITTED
    host: Omittable[str | None] = OMITTED
    alpn: Omittable[HostAlpn | None] = OMITTED
    fingerprint: Omittable[str | None] = OMITTED
    is_disabled: Omittable[bool] = OMITTED
    security_layer: Omittable[HostSecurityLayer] = OMITTED
    xhttp_extra_params: Omittable[Any] = OMITTED
    mux_params: Omittable[Any] = OMITTED
    sockopt_params: Omittable[Any] = OMITTED
    final_mask: Omittable[Any] = OMITTED
    server_description: Omittable[str | None] = OMITTED
    tags: Omittable[list[str]] = OMITTED
    is_hidden: Omittable[bool] = OMITTED
    override_sni_from_address: Omittable[bool] = OMITTED
    keep_sni_blank: Omittable[bool] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED
    pinned_peer_cert_sha256: Omittable[str | None] = OMITTED
    verify_peer_cert_by_name: Omittable[str | None] = OMITTED
    shuffle_host: Omittable[bool] = OMITTED
    mihomo_x25519: Omittable[bool] = OMITTED
    mihomo_ip_version: Omittable[HostMihomoIpVersion | None] = OMITTED
    nodes: Omittable[list[UUID]] = OMITTED
    xray_json_template_uuid: Omittable[UUID | None] = OMITTED
    exclude_from_subscription_types: Omittable[list[TemplateType]] = OMITTED
    mapper: Omittable[CreateHostBodyMapper] = OMITTED
    internal_squads: Omittable[HostInternalSquad] = OMITTED


@dataclass(slots=True)
class NodeUsageNode:
    uuid: UUID
    users: list[NodeUsageNodeUser]


@dataclass(slots=True)
class NodeUsage:
    nodes: list[NodeUsageNode]


@dataclass(slots=True)
class GetNodeUsageBody:
    nodes_uuids: list[UUID]


@dataclass(slots=True)
class StatsNodeUsersUsageTopUser:
    color: str
    username: str
    total: int


@dataclass(slots=True)
class StatsNodeUsersUsage:
    categories: list[str]
    sparkline_data: list[int]
    top_users: list[StatsNodeUsersUsageTopUser]


@dataclass(slots=True)
class StatsUserUsageTopNode:
    uuid: UUID
    color: str
    name: str
    country_code: str
    total: int


@dataclass(slots=True)
class StatsUserUsageSery:
    uuid: UUID
    name: str
    color: str
    country_code: str
    total: int
    data: list[int]


@dataclass(slots=True)
class StatsUserUsage:
    categories: list[str]
    sparkline_data: list[int]
    top_nodes: list[StatsUserUsageTopNode]
    series: list[StatsUserUsageSery]


@dataclass(slots=True)
class Device:
    hwid: str
    user_id: int
    platform: str | None
    os_version: str | None
    device_model: str | None
    user_agent: str | None
    request_ip: str | None
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class HwidDevicesQuery:
    devices: list[Device]
    total: int


@dataclass(slots=True)
class UserHwidDevice:
    total: int
    devices: list[Device]


@dataclass(slots=True)
class CreateUserHwidDeviceBody:
    hwid: str
    user_id: int
    platform: Omittable[str] = OMITTED
    os_version: Omittable[str] = OMITTED
    device_model: Omittable[str] = OMITTED
    user_agent: Omittable[str] = OMITTED
    request_ip: Omittable[str] = OMITTED


@dataclass(slots=True)
class DeleteUserHwidDeviceBody:
    user_id: int
    hwid: str


@dataclass(slots=True)
class DeleteAllUserHwidDevicesBody:
    user_id: int


@dataclass(slots=True)
class HwidDevicesStatsByPlatformByApp:
    app: str
    count: int


@dataclass(slots=True)
class HwidDevicesStatsByPlatform:
    platform: str
    count: int
    by_app: list[HwidDevicesStatsByPlatformByApp]


@dataclass(slots=True)
class HwidDevicesStatsStat:
    total_unique_devices: int
    total_hwid_devices: int
    average_hwid_devices_per_user: float


@dataclass(slots=True)
class HwidDevicesStats:
    by_platform: list[HwidDevicesStatsByPlatform]
    stats: HwidDevicesStatsStat


@dataclass(slots=True)
class TopUsersByHwidDevicesUser:
    id: int
    username: str
    devices_count: int


@dataclass(slots=True)
class TopUsersByHwidDevices:
    users: list[TopUsersByHwidDevicesUser]
    total: int


@dataclass(slots=True)
class InfraProviderBillingHistory:
    total_amount: float
    total_bills: int


@dataclass(slots=True)
class InfraProviderBillingNodeDetail:
    node_uuid: UUID
    country_code: str


@dataclass(slots=True)
class InfraProviderBillingNode:
    name: str
    details: InfraProviderBillingNodeDetail | None


@dataclass(slots=True)
class InfraProvider:
    uuid: UUID
    name: str
    favicon_link: str | None
    login_url: str | None
    created_at: datetime
    updated_at: datetime
    billing_history: InfraProviderBillingHistory
    billing_nodes: list[InfraProviderBillingNode]


@dataclass(slots=True)
class InfraProviders:
    total: int
    providers: list[InfraProvider]


@dataclass(slots=True)
class CreateInfraProviderBody:
    name: str
    favicon_link: Omittable[str] = OMITTED
    login_url: Omittable[str] = OMITTED


@dataclass(slots=True)
class UpdateInfraProviderBody:
    uuid: UUID
    name: Omittable[str] = OMITTED
    favicon_link: Omittable[str | None] = OMITTED
    login_url: Omittable[str | None] = OMITTED


@dataclass(slots=True)
class RecordProvider:
    uuid: UUID
    name: str
    favicon_link: str | None


@dataclass(slots=True)
class InfraBillingRecordRecord:
    uuid: UUID
    provider_uuid: UUID
    amount: float
    billed_at: datetime
    provider: RecordProvider


@dataclass(slots=True)
class InfraBillingRecord:
    records: list[InfraBillingRecordRecord]
    total: int


@dataclass(slots=True)
class CreateInfraBillingRecordBody:
    provider_uuid: UUID
    amount: float
    billed_at: datetime


@dataclass(slots=True)
class InfraBillingNodeProvider:
    uuid: UUID
    name: str
    login_url: str | None
    favicon_link: str | None


@dataclass(slots=True)
class InfraBillingNodeBillingNode:
    uuid: UUID
    node_uuid: UUID | None
    name: str | None
    provider_uuid: UUID
    provider: InfraBillingNodeProvider
    node: RecordNode | None
    next_billing_at: datetime
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class InfraBillingNodeStat:
    upcoming_nodes_count: int
    current_month_payments: float
    total_spent: float


@dataclass(slots=True)
class InfraBillingNode:
    total_billing_nodes: int
    billing_nodes: list[InfraBillingNodeBillingNode]
    available_billing_nodes: list[RecordNode]
    total_available_billing_nodes: int
    stats: InfraBillingNodeStat


@dataclass(slots=True)
class UpdateInfraBillingNodeBody:
    uuids: list[UUID]
    next_billing_at: datetime


@dataclass(slots=True)
class CreateInfraBillingNodeBody:
    provider_uuid: UUID
    node_uuid: UUID | None
    name: str | None
    next_billing_at: datetime


@dataclass(slots=True)
class SubscriptionRequestHistoryRecord:
    id: int
    user_id: int
    srr_response_type: str
    srr_rule_name: str | None
    request_ip: str | None
    user_agent: str | None
    request_at: datetime


@dataclass(slots=True)
class SubscriptionRequestHistory:
    records: list[SubscriptionRequestHistoryRecord]
    total: int


@dataclass(slots=True)
class SubscriptionRequestHistoryStatsHourlyRequestStat:
    date_time: datetime
    request_count: int


@dataclass(slots=True)
class SubscriptionRequestHistoryStats:
    by_parsed_app: list[HwidDevicesStatsByPlatformByApp]
    hourly_request_stats: list[SubscriptionRequestHistoryStatsHourlyRequestStat]


@dataclass(slots=True)
class MetadataBuild:
    time: str
    number: str


@dataclass(slots=True)
class MetadataGitBackend:
    commit_sha: str
    branch: str
    commit_url: str


@dataclass(slots=True)
class MetadataGitFrontend:
    commit_sha: str
    commit_url: str


@dataclass(slots=True)
class MetadataGit:
    backend: MetadataGitBackend
    frontend: MetadataGitFrontend


@dataclass(slots=True)
class Metadata:
    version: str
    build: MetadataBuild
    git: MetadataGit


@dataclass(slots=True)
class ConfigurationNotification:
    webhook: bool
    bandwidth_usage: list[float] | None
    not_connected_after: list[float] | None
    expiration_notifications: list[float] | None


@dataclass(slots=True)
class ConfigurationService:
    clean_usage_history: bool
    disable_user_usage_records: bool
    disable_srh_records: bool
    export_to_redis_stream: bool


@dataclass(slots=True)
class ConfigurationMisc:
    short_uuid_length: int
    sub_public_domain: str
    user_usage_ignore_below_bytes: int


@dataclass(slots=True)
class Configuration:
    notifications: ConfigurationNotification
    service: ConfigurationService
    misc: ConfigurationMisc


@dataclass(slots=True)
class StatsCpu:
    cores: int


@dataclass(slots=True)
class StatsMemory:
    total: int
    free: int
    used: int


@dataclass(slots=True)
class StatsUser:
    status_counts: dict[str, Any]
    total_users: int


@dataclass(slots=True)
class StatsOnlineStat:
    last_day: int
    last_week: int
    never_online: int
    online_now: int


@dataclass(slots=True)
class StatsNode:
    total_online: int
    total_bytes_lifetime: str


@dataclass(slots=True)
class Stats:
    cpu: StatsCpu
    memory: StatsMemory
    uptime: float
    timestamp: int
    users: StatsUser
    online_stats: StatsOnlineStat
    nodes: StatsNode


@dataclass(slots=True)
class BandwidthStatsBandwidthLast30Day:
    current: str
    previous: str
    difference: str


@dataclass(slots=True)
class BandwidthStats:
    bandwidth_last_two_days: BandwidthStatsBandwidthLast30Day
    bandwidth_last_seven_days: BandwidthStatsBandwidthLast30Day
    bandwidth_last30_days: BandwidthStatsBandwidthLast30Day
    bandwidth_calendar_month: BandwidthStatsBandwidthLast30Day
    bandwidth_current_year: BandwidthStatsBandwidthLast30Day


@dataclass(slots=True)
class NodesStatisticsLastSevenDay:
    node_name: str
    date: str
    total_bytes: str


@dataclass(slots=True)
class NodesStatistics:
    last_seven_days: list[NodesStatisticsLastSevenDay]


@dataclass(slots=True)
class RemnawaveHealthRuntimeMetric:
    rss: int
    heap_used: int
    heap_total: int
    external: int
    array_buffers: int
    event_loop_delay_ms: float
    event_loop_p99_ms: float
    active_handles: int
    uptime: float
    pid: int
    timestamp: int
    instance_id: str
    instance_type: str


@dataclass(slots=True)
class RemnawaveHealth:
    runtime_metrics: list[RemnawaveHealthRuntimeMetric]


@dataclass(slots=True)
class NodesMetricsNodeInboundsStat:
    tag: str
    upload: str
    download: str


@dataclass(slots=True)
class NodesMetricsNode:
    node_uuid: str
    node_name: str
    country_emoji: str
    provider_name: str
    users_online: int
    inbounds_stats: list[NodesMetricsNodeInboundsStat]
    outbounds_stats: list[NodesMetricsNodeInboundsStat]


@dataclass(slots=True)
class NodesMetrics:
    nodes: list[NodesMetricsNode]


@dataclass(slots=True)
class X25519Keypair:
    public_key: str
    private_key: str


@dataclass(slots=True)
class X25519:
    keypairs: list[X25519Keypair]


@dataclass(slots=True)
class SrrMatcherMatchedRuleCondition:
    header_name: str
    operator: SrrMatcherMatchedRuleConditionOperator
    value: str
    case_sensitive: bool


@dataclass(slots=True)
class SrrMatcherMatchedRuleResponseModificationHeader:
    key: str
    value: str


@dataclass(slots=True)
class SrrMatcherMatchedRuleResponseModificationEncryption:
    method: SrrMatcherMatchedRuleResponseModificationEncryptionMethod
    key: str


@dataclass(slots=True)
class SrrMatcherMatchedRuleResponseModification:
    headers: list[SrrMatcherMatchedRuleResponseModificationHeader] | None = None
    apply_headers_to_end: bool | None = None
    subscription_template: str | None = None
    ignore_host_xray_json_template: bool | None = None
    ignore_serve_json_at_base_subscription: bool | None = None
    additional_extended_clients_regex: list[str] | None = None
    disable_hwid_check: bool | None = None
    encryption: SrrMatcherMatchedRuleResponseModificationEncryption | None = (
        None
    )
    exclude_hosts_by_tags: list[str] | None = None
    respond_with_remarks: list[str] | None = None


@dataclass(slots=True)
class SrrMatcherMatchedRule:
    name: str
    enabled: bool
    operator: SrrMatcherMatchedRuleOperator
    conditions: list[SrrMatcherMatchedRuleCondition]
    response_type: SrrMatcherResponseType
    description: str | None = None
    response_modifications: SrrMatcherMatchedRuleResponseModification | None = (
        None
    )


@dataclass(slots=True)
class SrrMatcher:
    matched: bool
    response_type: SrrMatcherResponseType
    matched_rule: SrrMatcherMatchedRule | None
    input_headers: dict[str, Any]
    output_headers: dict[str, Any]


@dataclass(slots=True)
class DebugSrrMatcherBodyResponseRuleSetting:
    disable_subscription_access_by_path: Omittable[bool] = OMITTED


@dataclass(slots=True)
class DebugSrrMatcherBodyResponseRuleResponseModification:
    headers: Omittable[
        list[SrrMatcherMatchedRuleResponseModificationHeader]
    ] = OMITTED
    apply_headers_to_end: Omittable[bool] = OMITTED
    subscription_template: Omittable[str] = OMITTED
    ignore_host_xray_json_template: Omittable[bool] = OMITTED
    ignore_serve_json_at_base_subscription: Omittable[bool] = OMITTED
    additional_extended_clients_regex: Omittable[list[str]] = OMITTED
    disable_hwid_check: Omittable[bool] = OMITTED
    encryption: Omittable[
        SrrMatcherMatchedRuleResponseModificationEncryption
    ] = OMITTED
    exclude_hosts_by_tags: Omittable[list[str]] = OMITTED
    respond_with_remarks: Omittable[list[str]] = OMITTED


@dataclass(slots=True)
class DebugSrrMatcherBodyResponseRuleRule:
    name: str
    enabled: bool
    operator: SrrMatcherMatchedRuleOperator
    conditions: list[SrrMatcherMatchedRuleCondition]
    response_type: SrrMatcherResponseType
    description: Omittable[str] = OMITTED
    response_modifications: Omittable[
        DebugSrrMatcherBodyResponseRuleResponseModification
    ] = OMITTED


@dataclass(slots=True)
class DebugSrrMatcherBodyResponseRule:
    version: Literal["1"]
    rules: list[DebugSrrMatcherBodyResponseRuleRule]
    settings: Omittable[DebugSrrMatcherBodyResponseRuleSetting] = OMITTED


@dataclass(slots=True)
class DebugSrrMatcherBody:
    response_rules: DebugSrrMatcherBodyResponseRule


@dataclass(slots=True)
class RecapThisMonth:
    users: int
    traffic: str


@dataclass(slots=True)
class RecapTotal:
    users: int
    nodes: int
    traffic: str
    nodes_ram: str
    nodes_cpu_cores: int
    distinct_countries: int


@dataclass(slots=True)
class Recap:
    this_month: RecapThisMonth
    total: RecapTotal
    version: str
    init_date: datetime


@dataclass(slots=True)
class StatsDigestUser:
    created_count: int
    expired_count: int


@dataclass(slots=True)
class StatsDigestTraffic:
    total_bytes: str
    by_users_created_in_range_bytes: str


@dataclass(slots=True)
class StatsDigestHwidDevice:
    created_count: int


@dataclass(slots=True)
class StatsDigest:
    users: StatsDigestUser
    traffic: StatsDigestTraffic
    hwid_devices: StatsDigestHwidDevice


@dataclass(slots=True)
class HttpStatsRoute:
    method: str
    route: str
    count: int


@dataclass(slots=True)
class HttpStats:
    routes: list[HttpStatsRoute]
    total: int


@dataclass(slots=True)
class SubscriptionSettingsResponseRuleSetting:
    disable_subscription_access_by_path: bool | None = None


@dataclass(slots=True)
class SubscriptionSettingsResponseRule:
    version: Literal["1"]
    rules: list[SrrMatcherMatchedRule]
    settings: SubscriptionSettingsResponseRuleSetting | None = None


@dataclass(slots=True)
class SubscriptionSettings:
    uuid: UUID
    serve_json_at_base_subscription: bool
    is_show_custom_remarks: bool
    custom_remarks: ExternalSquadCustomRemark
    custom_response_headers: dict[str, Any] | None
    randomize_hosts: bool
    response_rules: SubscriptionSettingsResponseRule | None
    hwid_settings: ExternalSquadHwidSetting | None
    created_at: datetime
    updated_at: datetime


@dataclass(slots=True)
class UpdateSubscriptionSettingsBody:
    uuid: UUID
    serve_json_at_base_subscription: Omittable[bool] = OMITTED
    is_show_custom_remarks: Omittable[bool] = OMITTED
    custom_remarks: Omittable[ExternalSquadCustomRemark] = OMITTED
    custom_response_headers: Omittable[dict[str, Any]] = OMITTED
    randomize_hosts: Omittable[bool] = OMITTED
    response_rules: Omittable[DebugSrrMatcherBodyResponseRule] = OMITTED
    hwid_settings: Omittable[ExternalSquadHwidSetting] = OMITTED


@dataclass(slots=True)
class JobRef:
    job_id: str


@dataclass(slots=True)
class ConnectionsByUserResultProgress:
    total: int
    completed: int
    percent: int


@dataclass(slots=True)
class ConnectionsByNodeResultUserIp:
    ip: str
    last_seen: datetime


@dataclass(slots=True)
class ConnectionsByUserResultNode:
    node_uuid: UUID
    node_name: str
    country_code: str
    ips: list[ConnectionsByNodeResultUserIp]


@dataclass(slots=True)
class ConnectionsByUserResultResult:
    success: bool
    user_id: int
    nodes: list[ConnectionsByUserResultNode]


@dataclass(slots=True)
class ConnectionsByUserResult:
    is_completed: bool
    is_failed: bool
    progress: ConnectionsByUserResultProgress
    result: ConnectionsByUserResultResult | None


@dataclass(slots=True)
class DropConnectionsBody:
    drop_by: Any
    target_nodes: Any


@dataclass(slots=True)
class ConnectionsByNodeResultUser:
    user_id: int
    ips: list[ConnectionsByNodeResultUserIp]


@dataclass(slots=True)
class ConnectionsByNodeResultResult:
    success: bool
    node_uuid: UUID
    users: list[ConnectionsByNodeResultUser]


@dataclass(slots=True)
class ConnectionsByNodeResult:
    is_completed: bool
    is_failed: bool
    result: ConnectionsByNodeResultResult | None


@dataclass(slots=True)
class GeocheckByNodeBody:
    ip: Omittable[str] = OMITTED
    interface: Omittable[str] = OMITTED


@dataclass(slots=True)
class GeocheckByNodeResultImage:
    format: Literal["svg"]
    media_type: Literal["image/svg+xml"]
    encoding: Literal["base64"]
    data: str


@dataclass(slots=True)
class GeocheckByNodeResultResult:
    success: bool
    node_uuid: UUID
    image: GeocheckByNodeResultImage | None
    raw_report: dict[str, Any] | None
    message: str | None


@dataclass(slots=True)
class GeocheckByNodeResult:
    is_completed: bool
    is_failed: bool
    result: GeocheckByNodeResultResult | None


@dataclass(slots=True)
class NodeMetadata:
    metadata: dict[str, Any]


@dataclass(slots=True)
class CrmEventData:
    provider_name: str
    node_name: str
    next_billing_at: datetime
    login_url: str


@dataclass(slots=True)
class CrmEvent:
    scope: Literal["crm"]
    event: CrmEventName
    timestamp: datetime
    data: CrmEventData


@dataclass(slots=True)
class ErrorsEventData:
    description: str


@dataclass(slots=True)
class ErrorsEvent:
    scope: Literal["errors"]
    event: Literal["errors.bandwidth_usage_threshold_reached_max_notifications"]
    timestamp: datetime
    data: ErrorsEventData


@dataclass(slots=True)
class NodeEvent:
    scope: Literal["node"]
    event: NodeEventName
    timestamp: datetime
    data: Node


@dataclass(slots=True)
class ServiceEventDataLoginAttempt:
    username: str
    ip: str
    user_agent: str
    description: str | None = None
    password: str | None = None


@dataclass(slots=True)
class ServiceEventDataSubpageConfig:
    action: ServiceEventDataSubpageConfigAction
    uuid: UUID


@dataclass(slots=True)
class ServiceEventDataApiToken:
    name: str
    uuid: UUID
    expire_at: datetime
    scopes: list[str]


@dataclass(slots=True)
class ServiceEventData:
    login_attempt: ServiceEventDataLoginAttempt | None = None
    panel_version: str | None = None
    subpage_config: ServiceEventDataSubpageConfig | None = None
    api_token: ServiceEventDataApiToken | None = None


@dataclass(slots=True)
class ServiceEvent:
    scope: Literal["service"]
    event: ServiceEventName
    timestamp: datetime
    data: ServiceEventData


@dataclass(slots=True)
class TorrentBlockerEventData:
    node: Node
    user: User
    report: RecordReport


@dataclass(slots=True)
class TorrentBlockerEvent:
    scope: Literal["torrent_blocker"]
    event: Literal["torrent_blocker.report"]
    timestamp: datetime
    data: TorrentBlockerEventData


@dataclass(slots=True)
class UserEventMeta:
    not_connected_after_hours: float | None = None
    expiration: float | None = None


@dataclass(slots=True)
class UserEvent:
    scope: Literal["user"]
    event: UserEventName
    timestamp: datetime
    data: User
    meta: UserEventMeta | None


@dataclass(slots=True)
class UserHwidDevicesEventData:
    user: User
    hwid_user_device: Device


@dataclass(slots=True)
class UserHwidDevicesEvent:
    scope: Literal["user_hwid_devices"]
    event: UserHwidDevicesEventName
    timestamp: datetime
    data: UserHwidDevicesEventData
