# @generated by tools/codegen -- do not edit
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from adaptix import Omittable, Omitted

from remnawave._generated.enums import (
    CreateHostRequestAlpn,
    CreateHostRequestFingerprint,
    HostSecurityLayer,
    OAuth2CallbackRequestProvider,
    SrrMatcherMatchedRuleConditionOperator,
    SrrMatcherMatchedRuleOperator,
    SrrMatcherResponseType,
    TemplateTemplateType,
    UpdateUserRequestStatus,
    UserStatus,
    UserTrafficLimitStrategy,
)

OMITTED = Omitted()


@dataclass(frozen=True, slots=True)
class RemnawaveSettingsPasskeySetting:
    enabled: bool
    rp_id: str | None
    origin: str | None


@dataclass(frozen=True, slots=True)
class RemnawaveSettingsOauth2SettingGithub:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    allowed_emails: list[str]


@dataclass(frozen=True, slots=True)
class RemnawaveSettingsOauth2SettingPocketid:
    enabled: bool
    client_id: str | None
    client_secret: str | None
    plain_domain: str | None
    allowed_emails: list[str]


@dataclass(frozen=True, slots=True)
class RemnawaveSettingsOauth2Setting:
    github: RemnawaveSettingsOauth2SettingGithub
    pocketid: RemnawaveSettingsOauth2SettingPocketid
    yandex: RemnawaveSettingsOauth2SettingGithub


@dataclass(frozen=True, slots=True)
class RemnawaveSettingsTgAuthSetting:
    enabled: bool
    bot_token: str | None
    admin_ids: list[str]


@dataclass(frozen=True, slots=True)
class StatusAuthenticationPasskey:
    enabled: bool


@dataclass(frozen=True, slots=True)
class StatusBranding:
    title: str | None
    logo_url: str | None


@dataclass(frozen=True, slots=True)
class RemnawaveSettings:
    passkey_settings: RemnawaveSettingsPasskeySetting | None
    oauth2_settings: RemnawaveSettingsOauth2Setting | None
    tg_auth_settings: RemnawaveSettingsTgAuthSetting | None
    password_settings: StatusAuthenticationPasskey | None
    branding_settings: StatusBranding | None


@dataclass(frozen=True, slots=True)
class UpdateRemnawaveSettingsRequest:
    passkey_settings: Omittable[RemnawaveSettingsPasskeySetting] = OMITTED
    oauth2_settings: Omittable[RemnawaveSettingsOauth2Setting] = OMITTED
    tg_auth_settings: Omittable[RemnawaveSettingsTgAuthSetting] = OMITTED
    password_settings: Omittable[StatusAuthenticationPasskey] = OMITTED
    branding_settings: Omittable[StatusBranding] = OMITTED


@dataclass(frozen=True, slots=True)
class VerifyPasskeyRegistration:
    verified: bool


@dataclass(frozen=True, slots=True)
class VerifyPasskeyRegistrationRequest:
    response: Any


@dataclass(frozen=True, slots=True)
class PasskeyPasskey:
    id: str
    name: str
    created_at: datetime
    last_used_at: datetime


@dataclass(frozen=True, slots=True)
class Passkey:
    passkeys: list[PasskeyPasskey]


@dataclass(frozen=True, slots=True)
class DeletePasskeyRequest:
    id: str


@dataclass(frozen=True, slots=True)
class Login:
    access_token: str


@dataclass(frozen=True, slots=True)
class LoginRequest:
    username: str
    password: str


@dataclass(frozen=True, slots=True)
class StatusAuthenticationTgAuth:
    enabled: bool
    bot_id: int | None


@dataclass(frozen=True, slots=True)
class StatusAuthenticationOauth2:
    providers: dict[str, Any]


@dataclass(frozen=True, slots=True)
class StatusAuthentication:
    passkey: StatusAuthenticationPasskey
    tg_auth: StatusAuthenticationTgAuth
    oauth2: StatusAuthenticationOauth2
    password: StatusAuthenticationPasskey


@dataclass(frozen=True, slots=True)
class Status:
    is_login_allowed: bool
    is_register_allowed: bool
    authentication: StatusAuthentication | None
    branding: StatusBranding


@dataclass(frozen=True, slots=True)
class TelegramCallbackRequest:
    id: int
    first_name: str
    auth_date: int
    hash: str
    last_name: Omittable[str] = OMITTED
    username: Omittable[str] = OMITTED
    photo_url: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class OAuth2Authorize:
    authorization_url: str | None


@dataclass(frozen=True, slots=True)
class OAuth2AuthorizeRequest:
    provider: OAuth2CallbackRequestProvider


@dataclass(frozen=True, slots=True)
class OAuth2CallbackRequest:
    provider: OAuth2CallbackRequestProvider
    code: str
    state: str


@dataclass(frozen=True, slots=True)
class UserActiveInternalSquad:
    uuid: UUID
    name: str


@dataclass(frozen=True, slots=True)
class UserLastConnectedNode:
    connected_at: datetime
    node_name: str
    country_code: str


@dataclass(frozen=True, slots=True)
class UserHapp:
    crypto_link: str


@dataclass(frozen=True, slots=True)
class User:
    uuid: UUID
    short_uuid: str
    username: str
    used_traffic_bytes: int
    lifetime_used_traffic_bytes: int
    sub_last_user_agent: str | None
    sub_last_opened_at: datetime | None
    expire_at: datetime
    online_at: datetime | None
    sub_revoked_at: datetime | None
    last_traffic_reset_at: datetime | None
    trojan_password: str = field(repr=False)
    vless_uuid: UUID = field(repr=False)
    ss_password: str = field(repr=False)
    description: str | None
    tag: str | None
    telegram_id: int | None
    email: str | None
    hwid_device_limit: int | None
    first_connected_at: datetime | None
    created_at: datetime
    updated_at: datetime
    active_internal_squads: list[UserActiveInternalSquad]
    external_squad_uuid: UUID | None
    subscription_url: str = field(repr=False)
    last_connected_node: UserLastConnectedNode | None
    happ: UserHapp
    status: UserStatus | None = None
    traffic_limit_bytes: int | None = None
    traffic_limit_strategy: UserTrafficLimitStrategy | None = None
    last_triggered_threshold: int | None = None


@dataclass(frozen=True, slots=True)
class CreateUserRequest:
    username: str
    expire_at: datetime
    status: Omittable[UserStatus] = OMITTED
    short_uuid: Omittable[str] = OMITTED
    trojan_password: Omittable[str] = OMITTED
    vless_uuid: Omittable[UUID] = OMITTED
    ss_password: Omittable[str] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    created_at: Omittable[datetime] = OMITTED
    last_traffic_reset_at: Omittable[datetime] = OMITTED
    description: Omittable[str] = OMITTED
    tag: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int] = OMITTED
    active_internal_squads: Omittable[list[UUID]] = OMITTED
    uuid: Omittable[UUID] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateUserRequest:
    username: Omittable[str] = OMITTED
    uuid: Omittable[UUID] = OMITTED
    status: Omittable[UpdateUserRequestStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED
    active_internal_squads: Omittable[list[UUID]] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(frozen=True, slots=True)
class UsersPage:
    users: list[User]
    total: int


@dataclass(frozen=True, slots=True)
class Host:
    is_deleted: bool


@dataclass(frozen=True, slots=True)
class Tags:
    tags: list[str]


@dataclass(frozen=True, slots=True)
class UserAccessibleNodesActiveNodeActiveSquad:
    squad_name: str
    active_inbounds: list[str]


@dataclass(frozen=True, slots=True)
class UserAccessibleNodesActiveNode:
    uuid: UUID
    node_name: str
    country_code: str
    config_profile_uuid: UUID
    config_profile_name: str
    active_squads: list[UserAccessibleNodesActiveNodeActiveSquad]


@dataclass(frozen=True, slots=True)
class UserAccessibleNodes:
    user_uuid: UUID
    active_nodes: list[UserAccessibleNodesActiveNode]


@dataclass(frozen=True, slots=True)
class UserSubscriptionRequestHistoryRecord:
    id: int
    user_uuid: UUID
    request_at: datetime
    request_ip: str | None
    user_agent: str | None


@dataclass(frozen=True, slots=True)
class UserSubscriptionRequestHistory:
    total: int
    records: list[UserSubscriptionRequestHistoryRecord]


@dataclass(frozen=True, slots=True)
class RevokeUserSubscriptionBody:
    short_uuid: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class DeleteUsers:
    affected_rows: int


@dataclass(frozen=True, slots=True)
class BulkDeleteUsersByStatusRequest:
    status: Omittable[UserStatus] = OMITTED


@dataclass(frozen=True, slots=True)
class BulkDeleteHostsRequest:
    uuids: list[UUID]


@dataclass(frozen=True, slots=True)
class BulkUpdateUsersRequestField:
    status: Omittable[UserStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED
    external_squad_uuid: Omittable[UUID | None] = OMITTED


@dataclass(frozen=True, slots=True)
class BulkUpdateUsersRequest:
    uuids: list[UUID]
    fields: BulkUpdateUsersRequestField


@dataclass(frozen=True, slots=True)
class BulkUpdateUsersSquadsRequest:
    uuids: list[UUID]
    active_internal_squads: list[UUID]


@dataclass(frozen=True, slots=True)
class Node:
    event_sent: bool


@dataclass(frozen=True, slots=True)
class BulkAllUpdateUsersRequest:
    status: Omittable[UserStatus] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    traffic_limit_strategy: Omittable[UserTrafficLimitStrategy] = OMITTED
    expire_at: Omittable[datetime] = OMITTED
    description: Omittable[str | None] = OMITTED
    telegram_id: Omittable[int | None] = OMITTED
    email: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    hwid_device_limit: Omittable[int | None] = OMITTED


@dataclass(frozen=True, slots=True)
class UserUsageByRange:
    user_uuid: UUID
    node_uuid: UUID
    node_name: str
    country_code: str
    total: int
    date: str


@dataclass(frozen=True, slots=True)
class SubscriptionInfoUser:
    short_uuid: str
    days_left: int
    traffic_used: str
    traffic_limit: str
    lifetime_traffic_used: str
    traffic_used_bytes: str
    traffic_limit_bytes: str
    lifetime_traffic_used_bytes: str
    username: str
    expires_at: datetime
    is_active: bool
    user_status: UserStatus
    traffic_limit_strategy: UserTrafficLimitStrategy


@dataclass(frozen=True, slots=True)
class SubscriptionInfo:
    is_found: bool
    user: SubscriptionInfoUser
    links: list[str]
    ss_conf_links: dict[str, Any]
    subscription_url: str
    happ: UserHapp


@dataclass(frozen=True, slots=True)
class SubscriptionUser:
    short_uuid: str
    days_left: int
    traffic_used: str
    traffic_limit: str
    username: str
    expires_at: datetime
    is_active: bool
    user_status: UserStatus
    traffic_limit_strategy: UserTrafficLimitStrategy


@dataclass(frozen=True, slots=True)
class Subscription:
    is_found: bool
    user: SubscriptionUser
    links: list[str]
    ss_conf_links: dict[str, Any]
    subscription_url: str


@dataclass(frozen=True, slots=True)
class SubscriptionsPage:
    subscriptions: list[Subscription]
    total: int


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidConvertedUserInfo:
    days_left: int
    traffic_limit: str
    traffic_used: str
    lifetime_traffic_used: str
    is_hwid_limited: bool


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHostPassword:
    ss_password: str
    trojan_password: str
    vless_password: str


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHostAdditionalParam:
    mode: str | None = None
    heartbeat_period: int | None = None


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHostProtocolOptionSs:
    method: str | None = None


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHostProtocolOption:
    ss: RawSubscriptionByShortUuidRawHostProtocolOptionSs | None = None


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHostDbData:
    raw_inbound: dict[str, Any] | None
    inbound_tag: str
    uuid: str
    config_profile_uuid: str | None
    config_profile_inbound_uuid: str | None
    is_disabled: bool
    view_position: int
    remark: str
    is_hidden: bool
    tag: str | None
    vless_route_id: int | None


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuidRawHost:
    password: RawSubscriptionByShortUuidRawHostPassword
    address: str | None = None
    alpn: str | None = None
    fingerprint: str | None = None
    host: str | None = None
    network: str | None = None
    path: str | None = None
    public_key: str | None = None
    port: int | None = None
    protocol: str | None = None
    remark: str | None = None
    short_id: str | None = None
    sni: str | None = None
    spider_x: str | None = None
    tls: str | None = None
    header_type: str | None = None
    additional_params: (
        RawSubscriptionByShortUuidRawHostAdditionalParam | None
    ) = None
    x_http_extra_params: dict[str, Any] | None = None
    mux_params: dict[str, Any] | None = None
    sockopt_params: dict[str, Any] | None = None
    server_description: str | None = None
    flow: str | None = None
    allow_insecure: bool | None = None
    shuffle_host: bool | None = None
    mihomo_x25519: bool | None = None
    mldsa65_verify: str | None = None
    encryption: str | None = None
    protocol_options: (
        RawSubscriptionByShortUuidRawHostProtocolOption | None
    ) = None
    db_data: RawSubscriptionByShortUuidRawHostDbData | None = None


@dataclass(frozen=True, slots=True)
class RawSubscriptionByShortUuid:
    user: User
    converted_user_info: RawSubscriptionByShortUuidConvertedUserInfo
    headers: dict[str, Any]
    raw_hosts: list[RawSubscriptionByShortUuidRawHost]


@dataclass(frozen=True, slots=True)
class Template:
    uuid: UUID
    name: str
    template_type: TemplateTemplateType
    template_json: Any
    encoded_template_yaml: str | None


@dataclass(frozen=True, slots=True)
class Templates:
    total: int
    templates: list[Template]


@dataclass(frozen=True, slots=True)
class UpdateTemplateRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    template_json: Omittable[dict[str, Any]] = OMITTED
    encoded_template_yaml: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class CreateSubscriptionTemplateRequest:
    name: str
    template_type: TemplateTemplateType


@dataclass(frozen=True, slots=True)
class ApiToken:
    token: str
    uuid: str


@dataclass(frozen=True, slots=True)
class CreateApiTokenRequest:
    token_name: str


@dataclass(frozen=True, slots=True)
class FindAllApiTokensApiKey:
    uuid: UUID
    token: str
    token_name: str
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class FindAllApiTokensDoc:
    is_docs_enabled: bool
    scalar_path: str | None
    swagger_path: str | None


@dataclass(frozen=True, slots=True)
class FindAllApiTokens:
    api_keys: list[FindAllApiTokensApiKey]
    docs: FindAllApiTokensDoc


@dataclass(frozen=True, slots=True)
class ConfigProfileInbound:
    uuid: UUID
    profile_uuid: UUID
    tag: str
    type: str
    network: str | None
    security: str | None
    port: int | None
    raw_inbound: Any


@dataclass(frozen=True, slots=True)
class ConfigProfileNode:
    uuid: UUID
    name: str
    country_code: str


@dataclass(frozen=True, slots=True)
class ConfigProfile:
    uuid: UUID
    name: str
    config: Any
    inbounds: list[ConfigProfileInbound]
    nodes: list[ConfigProfileNode]
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class ConfigProfiles:
    total: int
    config_profiles: list[ConfigProfile]


@dataclass(frozen=True, slots=True)
class CreateConfigProfileRequest:
    name: str
    config: dict[str, Any]


@dataclass(frozen=True, slots=True)
class UpdateConfigProfileRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    config: Omittable[dict[str, Any]] = OMITTED


@dataclass(frozen=True, slots=True)
class InboundsInbound:
    uuid: UUID
    profile_uuid: UUID
    tag: str
    type: str
    network: str | None
    security: str | None
    port: int | None
    raw_inbound: Any
    active_squads: list[UUID]


@dataclass(frozen=True, slots=True)
class Inbounds:
    total: int
    inbounds: list[InboundsInbound]


@dataclass(frozen=True, slots=True)
class SnippetSnippet:
    name: str
    snippet: Any


@dataclass(frozen=True, slots=True)
class Snippet:
    total: int
    snippets: list[SnippetSnippet]


@dataclass(frozen=True, slots=True)
class DeleteSnippetRequest:
    name: str


@dataclass(frozen=True, slots=True)
class CreateSnippetRequest:
    name: str
    snippet: list[dict[str, Any]]


@dataclass(frozen=True, slots=True)
class InternalSquadInfo:
    members_count: int
    inbounds_count: int


@dataclass(frozen=True, slots=True)
class InternalSquad:
    uuid: UUID
    name: str
    info: InternalSquadInfo
    inbounds: list[ConfigProfileInbound]
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class InternalSquads:
    total: int
    internal_squads: list[InternalSquad]


@dataclass(frozen=True, slots=True)
class CreateInternalSquadRequest:
    name: str
    inbounds: list[UUID]


@dataclass(frozen=True, slots=True)
class UpdateInternalSquadRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    inbounds: Omittable[list[UUID]] = OMITTED


@dataclass(frozen=True, slots=True)
class InternalSquadAccessibleNodesAccessibleNode:
    uuid: UUID
    node_name: str
    country_code: str
    config_profile_uuid: UUID
    config_profile_name: str
    active_inbounds: list[str]


@dataclass(frozen=True, slots=True)
class InternalSquadAccessibleNodes:
    squad_uuid: UUID
    accessible_nodes: list[InternalSquadAccessibleNodesAccessibleNode]


@dataclass(frozen=True, slots=True)
class ExternalSquadInfo:
    members_count: int


@dataclass(frozen=True, slots=True)
class ExternalSquadTemplate:
    template_uuid: UUID
    template_type: TemplateTemplateType


@dataclass(frozen=True, slots=True)
class ExternalSquadSubscriptionSetting:
    profile_title: str | None = None
    support_link: str | None = None
    profile_update_interval: int | None = None
    is_profile_webpage_url_enabled: bool | None = None
    serve_json_at_base_subscription: bool | None = None
    add_username_to_base_subscription: bool | None = None
    is_show_custom_remarks: bool | None = None
    happ_announce: str | None = None
    happ_routing: str | None = None
    randomize_hosts: bool | None = None


@dataclass(frozen=True, slots=True)
class ExternalSquadHostOverride:
    server_description: str | None = None
    vless_route_id: int | None = None


@dataclass(frozen=True, slots=True)
class ExternalSquad:
    uuid: UUID
    name: str
    info: ExternalSquadInfo
    templates: list[ExternalSquadTemplate]
    subscription_settings: ExternalSquadSubscriptionSetting | None
    host_overrides: ExternalSquadHostOverride | None
    response_headers: dict[str, Any] | None
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class ExternalSquads:
    total: int
    external_squads: list[ExternalSquad]


@dataclass(frozen=True, slots=True)
class UpdateExternalSquadRequestSubscriptionSetting:
    profile_title: Omittable[str] = OMITTED
    support_link: Omittable[str] = OMITTED
    profile_update_interval: Omittable[int] = OMITTED
    is_profile_webpage_url_enabled: Omittable[bool] = OMITTED
    serve_json_at_base_subscription: Omittable[bool] = OMITTED
    add_username_to_base_subscription: Omittable[bool] = OMITTED
    is_show_custom_remarks: Omittable[bool] = OMITTED
    happ_announce: Omittable[str | None] = OMITTED
    happ_routing: Omittable[str | None] = OMITTED
    randomize_hosts: Omittable[bool] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateExternalSquadRequestHostOverride:
    server_description: Omittable[str | None] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateExternalSquadRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    templates: Omittable[list[ExternalSquadTemplate]] = OMITTED
    subscription_settings: Omittable[
        UpdateExternalSquadRequestSubscriptionSetting
    ] = OMITTED
    host_overrides: Omittable[UpdateExternalSquadRequestHostOverride] = OMITTED
    response_headers: Omittable[dict[str, Any] | None] = OMITTED


@dataclass(frozen=True, slots=True)
class PubKey:
    pub_key: str


@dataclass(frozen=True, slots=True)
class NodeConfigProfile:
    active_config_profile_uuid: UUID | None
    active_inbounds: list[ConfigProfileInbound]


@dataclass(frozen=True, slots=True)
class NodeProvider:
    uuid: UUID
    name: str
    favicon_link: str | None
    login_url: str | None
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class Node2:
    uuid: UUID
    name: str
    address: str
    port: int | None
    is_connected: bool
    is_disabled: bool
    is_connecting: bool
    is_node_online: bool
    is_xray_running: bool
    last_status_change: datetime | None
    last_status_message: str | None
    xray_version: str | None
    node_version: str | None
    xray_uptime: str
    is_traffic_tracking_active: bool
    traffic_reset_day: int | None
    traffic_limit_bytes: int | None
    traffic_used_bytes: int | None
    notify_percent: int | None
    users_online: int | None
    view_position: int
    country_code: str
    consumption_multiplier: float
    cpu_count: int | None
    cpu_model: str | None
    total_ram: str | None
    created_at: datetime
    updated_at: datetime
    config_profile: NodeConfigProfile
    provider_uuid: UUID | None
    provider: NodeProvider | None


@dataclass(frozen=True, slots=True)
class CreateNodeRequestConfigProfile:
    active_config_profile_uuid: UUID
    active_inbounds: list[UUID]


@dataclass(frozen=True, slots=True)
class CreateNodeRequest:
    name: str
    address: str
    config_profile: CreateNodeRequestConfigProfile
    port: Omittable[int] = OMITTED
    is_traffic_tracking_active: Omittable[bool] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    notify_percent: Omittable[int] = OMITTED
    traffic_reset_day: Omittable[int] = OMITTED
    country_code: Omittable[str] = OMITTED
    consumption_multiplier: Omittable[float] = OMITTED
    provider_uuid: Omittable[UUID | None] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateNodeRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    address: Omittable[str] = OMITTED
    port: Omittable[int] = OMITTED
    is_traffic_tracking_active: Omittable[bool] = OMITTED
    traffic_limit_bytes: Omittable[int] = OMITTED
    notify_percent: Omittable[int] = OMITTED
    traffic_reset_day: Omittable[int] = OMITTED
    country_code: Omittable[str] = OMITTED
    consumption_multiplier: Omittable[float] = OMITTED
    config_profile: Omittable[CreateNodeRequestConfigProfile] = OMITTED
    provider_uuid: Omittable[UUID | None] = OMITTED


@dataclass(frozen=True, slots=True)
class RestartAllNodesRequestBody:
    force_restart: Omittable[bool] = OMITTED


@dataclass(frozen=True, slots=True)
class ReorderHostRequestHost:
    view_position: int
    uuid: UUID


@dataclass(frozen=True, slots=True)
class ReorderNodeRequest:
    nodes: list[ReorderHostRequestHost]


@dataclass(frozen=True, slots=True)
class HostInbound:
    config_profile_uuid: UUID | None
    config_profile_inbound_uuid: UUID | None


@dataclass(frozen=True, slots=True)
class Host2:
    uuid: UUID
    view_position: int
    remark: str
    address: str
    port: int
    path: str | None
    sni: str | None
    host: str | None
    alpn: str | None
    fingerprint: str | None
    x_http_extra_params: Any
    mux_params: Any
    sockopt_params: Any
    inbound: HostInbound
    server_description: str | None
    tag: str | None
    vless_route_id: int | None
    shuffle_host: bool
    mihomo_x25519: bool
    nodes: list[UUID]
    is_disabled: bool | None = None
    security_layer: HostSecurityLayer | None = None
    is_hidden: bool | None = None
    override_sni_from_address: bool | None = None
    allow_insecure: bool | None = None


@dataclass(frozen=True, slots=True)
class CreateHostRequestInbound:
    config_profile_uuid: UUID
    config_profile_inbound_uuid: UUID


@dataclass(frozen=True, slots=True)
class CreateHostRequest:
    inbound: CreateHostRequestInbound
    remark: str
    address: str
    port: int
    path: Omittable[str] = OMITTED
    sni: Omittable[str] = OMITTED
    host: Omittable[str] = OMITTED
    alpn: Omittable[CreateHostRequestAlpn | None] = OMITTED
    fingerprint: Omittable[CreateHostRequestFingerprint | None] = OMITTED
    is_disabled: Omittable[bool] = OMITTED
    security_layer: Omittable[HostSecurityLayer] = OMITTED
    x_http_extra_params: Omittable[Any] = OMITTED
    mux_params: Omittable[Any] = OMITTED
    sockopt_params: Omittable[Any] = OMITTED
    server_description: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    is_hidden: Omittable[bool] = OMITTED
    override_sni_from_address: Omittable[bool] = OMITTED
    allow_insecure: Omittable[bool] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED
    shuffle_host: Omittable[bool] = OMITTED
    mihomo_x25519: Omittable[bool] = OMITTED
    nodes: Omittable[list[UUID]] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateHostRequest:
    uuid: UUID
    inbound: Omittable[CreateHostRequestInbound] = OMITTED
    remark: Omittable[str] = OMITTED
    address: Omittable[str] = OMITTED
    port: Omittable[int] = OMITTED
    path: Omittable[str] = OMITTED
    sni: Omittable[str] = OMITTED
    host: Omittable[str] = OMITTED
    alpn: Omittable[CreateHostRequestAlpn | None] = OMITTED
    fingerprint: Omittable[CreateHostRequestFingerprint | None] = OMITTED
    is_disabled: Omittable[bool] = OMITTED
    security_layer: Omittable[HostSecurityLayer] = OMITTED
    x_http_extra_params: Omittable[Any] = OMITTED
    mux_params: Omittable[Any] = OMITTED
    sockopt_params: Omittable[Any] = OMITTED
    server_description: Omittable[str | None] = OMITTED
    tag: Omittable[str | None] = OMITTED
    is_hidden: Omittable[bool] = OMITTED
    override_sni_from_address: Omittable[bool] = OMITTED
    vless_route_id: Omittable[int | None] = OMITTED
    allow_insecure: Omittable[bool] = OMITTED
    shuffle_host: Omittable[bool] = OMITTED
    mihomo_x25519: Omittable[bool] = OMITTED
    nodes: Omittable[list[UUID]] = OMITTED


@dataclass(frozen=True, slots=True)
class Host3:
    is_updated: bool


@dataclass(frozen=True, slots=True)
class ReorderHostRequest:
    hosts: list[ReorderHostRequestHost]


@dataclass(frozen=True, slots=True)
class SetInboundToManyHostsRequest:
    uuids: list[UUID]
    config_profile_uuid: UUID
    config_profile_inbound_uuid: UUID


@dataclass(frozen=True, slots=True)
class SetPortToManyHostsRequest:
    uuids: list[UUID]
    port: int


@dataclass(frozen=True, slots=True)
class NodeUserUsageByRange:
    user_uuid: UUID
    username: str
    node_uuid: UUID
    total: int
    date: str


@dataclass(frozen=True, slots=True)
class NodesRealtimeUsage:
    node_uuid: UUID
    node_name: str
    country_code: str
    download_bytes: int
    upload_bytes: int
    total_bytes: int
    download_speed_bps: int
    upload_speed_bps: int
    total_speed_bps: int


@dataclass(frozen=True, slots=True)
class Device:
    hwid: str
    user_uuid: UUID
    platform: str | None
    os_version: str | None
    device_model: str | None
    user_agent: str | None
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class HwidDevices:
    devices: list[Device]
    total: int


@dataclass(frozen=True, slots=True)
class UserHwidDevice:
    total: int
    devices: list[Device]


@dataclass(frozen=True, slots=True)
class CreateUserHwidDeviceRequest:
    hwid: str
    user_uuid: UUID
    platform: Omittable[str] = OMITTED
    os_version: Omittable[str] = OMITTED
    device_model: Omittable[str] = OMITTED
    user_agent: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class DeleteUserHwidDeviceRequest:
    user_uuid: UUID
    hwid: str


@dataclass(frozen=True, slots=True)
class DeleteAllUserHwidDevicesRequest:
    user_uuid: UUID


@dataclass(frozen=True, slots=True)
class HwidDevicesStatsByPlatform:
    platform: str
    count: int


@dataclass(frozen=True, slots=True)
class HwidDevicesStatsByApp:
    app: str
    count: int


@dataclass(frozen=True, slots=True)
class HwidDevicesStatsStat:
    total_unique_devices: int
    total_hwid_devices: int
    average_hwid_devices_per_user: int


@dataclass(frozen=True, slots=True)
class HwidDevicesStats:
    by_platform: list[HwidDevicesStatsByPlatform]
    by_app: list[HwidDevicesStatsByApp]
    stats: HwidDevicesStatsStat


@dataclass(frozen=True, slots=True)
class NodesUsageByRange:
    node_uuid: UUID
    node_name: str
    node_country_code: str
    total: int
    total_download: int
    total_upload: int
    human_readable_total: str
    human_readable_total_download: str
    human_readable_total_upload: str
    date: str


@dataclass(frozen=True, slots=True)
class InfraProviderBillingHistory:
    total_amount: int
    total_bills: int


@dataclass(frozen=True, slots=True)
class InfraProviderBillingNode:
    node_uuid: UUID
    name: str
    country_code: str


@dataclass(frozen=True, slots=True)
class InfraProvider:
    uuid: UUID
    name: str
    favicon_link: str | None
    login_url: str | None
    created_at: datetime
    updated_at: datetime
    billing_history: InfraProviderBillingHistory
    billing_nodes: list[InfraProviderBillingNode]


@dataclass(frozen=True, slots=True)
class InfraProviders:
    total: int
    providers: list[InfraProvider]


@dataclass(frozen=True, slots=True)
class CreateInfraProviderRequest:
    name: str
    favicon_link: Omittable[str] = OMITTED
    login_url: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class UpdateInfraProviderRequest:
    uuid: UUID
    name: Omittable[str] = OMITTED
    favicon_link: Omittable[str | None] = OMITTED
    login_url: Omittable[str | None] = OMITTED


@dataclass(frozen=True, slots=True)
class InfraBillingHistoryRecordRecordProvider:
    uuid: UUID
    name: str
    favicon_link: str | None


@dataclass(frozen=True, slots=True)
class InfraBillingHistoryRecordRecord:
    uuid: UUID
    provider_uuid: UUID
    amount: int
    billed_at: datetime
    provider: InfraBillingHistoryRecordRecordProvider


@dataclass(frozen=True, slots=True)
class InfraBillingHistoryRecord:
    records: list[InfraBillingHistoryRecordRecord]
    total: int


@dataclass(frozen=True, slots=True)
class CreateInfraBillingHistoryRecordRequest:
    provider_uuid: UUID
    amount: int
    billed_at: datetime


@dataclass(frozen=True, slots=True)
class InfraBillingNodeBillingNodeProvider:
    uuid: UUID
    name: str
    login_url: str | None
    favicon_link: str | None


@dataclass(frozen=True, slots=True)
class InfraBillingNodeBillingNode:
    uuid: UUID
    node_uuid: UUID
    provider_uuid: UUID
    provider: InfraBillingNodeBillingNodeProvider
    node: ConfigProfileNode
    next_billing_at: datetime
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class InfraBillingNodeStat:
    upcoming_nodes_count: int
    current_month_payments: int
    total_spent: int


@dataclass(frozen=True, slots=True)
class InfraBillingNode:
    total_billing_nodes: int
    billing_nodes: list[InfraBillingNodeBillingNode]
    available_billing_nodes: list[ConfigProfileNode]
    total_available_billing_nodes: int
    stats: InfraBillingNodeStat


@dataclass(frozen=True, slots=True)
class UpdateInfraBillingNodeRequest:
    uuids: list[UUID]
    next_billing_at: datetime


@dataclass(frozen=True, slots=True)
class CreateInfraBillingNodeRequest:
    provider_uuid: UUID
    node_uuid: UUID
    next_billing_at: Omittable[datetime] = OMITTED


@dataclass(frozen=True, slots=True)
class TorrentBlockerReport:
    id: int
    user_uuid: UUID
    request_ip: str | None
    user_agent: str | None
    request_at: datetime


@dataclass(frozen=True, slots=True)
class SubscriptionRequestsPage:
    records: list[TorrentBlockerReport]
    total: int


@dataclass(frozen=True, slots=True)
class SubscriptionRequestHistoryStatsHourlyRequestStat:
    date_time: datetime
    request_count: int


@dataclass(frozen=True, slots=True)
class SubscriptionRequestHistoryStats:
    by_parsed_app: list[HwidDevicesStatsByApp]
    hourly_request_stats: list[SubscriptionRequestHistoryStatsHourlyRequestStat]


@dataclass(frozen=True, slots=True)
class StatsCpu:
    cores: int
    physical_cores: int


@dataclass(frozen=True, slots=True)
class StatsMemory:
    total: int
    free: int
    used: int
    active: int
    available: int


@dataclass(frozen=True, slots=True)
class StatsUser:
    status_counts: dict[str, Any]
    total_users: int
    total_traffic_bytes: str


@dataclass(frozen=True, slots=True)
class StatsOnlineStat:
    last_day: int
    last_week: int
    never_online: int
    online_now: int


@dataclass(frozen=True, slots=True)
class StatsNode:
    total_online: int


@dataclass(frozen=True, slots=True)
class Stats:
    cpu: StatsCpu
    memory: StatsMemory
    uptime: float
    timestamp: int
    users: StatsUser
    online_stats: StatsOnlineStat
    nodes: StatsNode


@dataclass(frozen=True, slots=True)
class BandwidthStatsBandwidthLast30Day:
    current: str
    previous: str
    difference: str


@dataclass(frozen=True, slots=True)
class BandwidthStats:
    bandwidth_last_two_days: BandwidthStatsBandwidthLast30Day
    bandwidth_last_seven_days: BandwidthStatsBandwidthLast30Day
    bandwidth_last30_days: BandwidthStatsBandwidthLast30Day
    bandwidth_calendar_month: BandwidthStatsBandwidthLast30Day
    bandwidth_current_year: BandwidthStatsBandwidthLast30Day


@dataclass(frozen=True, slots=True)
class NodesStatisticsLastSevenDay:
    node_name: str
    date: str
    total_bytes: str


@dataclass(frozen=True, slots=True)
class NodesStatistics:
    last_seven_days: list[NodesStatisticsLastSevenDay]


@dataclass(frozen=True, slots=True)
class RemnawaveHealthPm2Stat:
    name: str
    memory: str
    cpu: str


@dataclass(frozen=True, slots=True)
class RemnawaveHealth:
    pm2_stats: list[RemnawaveHealthPm2Stat]


@dataclass(frozen=True, slots=True)
class NodesMetricsNodeInboundsStat:
    tag: str
    upload: str
    download: str


@dataclass(frozen=True, slots=True)
class NodesMetricsNode:
    node_uuid: str
    node_name: str
    country_emoji: str
    provider_name: str
    users_online: int
    inbounds_stats: list[NodesMetricsNodeInboundsStat]
    outbounds_stats: list[NodesMetricsNodeInboundsStat]


@dataclass(frozen=True, slots=True)
class NodesMetrics:
    nodes: list[NodesMetricsNode]


@dataclass(frozen=True, slots=True)
class X25519Keypair:
    public_key: str
    private_key: str


@dataclass(frozen=True, slots=True)
class X25519:
    keypairs: list[X25519Keypair]


@dataclass(frozen=True, slots=True)
class EncryptHappCryptoLink:
    encrypted_link: str


@dataclass(frozen=True, slots=True)
class EncryptHappCryptoLinkRequest:
    link_to_encrypt: str


@dataclass(frozen=True, slots=True)
class SrrMatcherMatchedRuleCondition:
    header_name: str
    operator: SrrMatcherMatchedRuleConditionOperator
    value: str
    case_sensitive: bool


@dataclass(frozen=True, slots=True)
class SrrMatcherMatchedRuleResponseModificationHeader:
    key: str
    value: str


@dataclass(frozen=True, slots=True)
class SrrMatcherMatchedRuleResponseModification:
    headers: list[SrrMatcherMatchedRuleResponseModificationHeader] | None = None
    subscription_template: str | None = None


@dataclass(frozen=True, slots=True)
class SrrMatcherMatchedRule:
    name: str
    enabled: bool
    operator: SrrMatcherMatchedRuleOperator
    conditions: list[SrrMatcherMatchedRuleCondition]
    response_type: SrrMatcherResponseType
    description: str | None = None
    response_modifications: SrrMatcherMatchedRuleResponseModification | None = (
        None
    )


@dataclass(frozen=True, slots=True)
class SrrMatcher:
    matched: bool
    response_type: SrrMatcherResponseType
    matched_rule: SrrMatcherMatchedRule | None
    input_headers: dict[str, Any]
    output_headers: dict[str, Any]


@dataclass(frozen=True, slots=True)
class DebugSrrMatcherRequestResponseRuleRuleResponseModification:
    headers: Omittable[
        list[SrrMatcherMatchedRuleResponseModificationHeader]
    ] = OMITTED
    subscription_template: Omittable[str] = OMITTED


@dataclass(frozen=True, slots=True)
class DebugSrrMatcherRequestResponseRuleRule:
    name: str
    enabled: bool
    operator: SrrMatcherMatchedRuleOperator
    conditions: list[SrrMatcherMatchedRuleCondition]
    response_type: SrrMatcherResponseType
    description: Omittable[str] = OMITTED
    response_modifications: Omittable[
        DebugSrrMatcherRequestResponseRuleRuleResponseModification
    ] = OMITTED


@dataclass(frozen=True, slots=True)
class DebugSrrMatcherRequestResponseRule:
    version: Literal["1"]
    rules: list[DebugSrrMatcherRequestResponseRuleRule]


@dataclass(frozen=True, slots=True)
class DebugSrrMatcherRequest:
    response_rules: DebugSrrMatcherRequestResponseRule


@dataclass(frozen=True, slots=True)
class SubscriptionSettingsResponseRule:
    version: Literal["1"]
    rules: list[SrrMatcherMatchedRule]


@dataclass(frozen=True, slots=True)
class SubscriptionSettings:
    uuid: UUID
    profile_title: str
    support_link: str
    profile_update_interval: int
    is_profile_webpage_url_enabled: bool
    serve_json_at_base_subscription: bool
    add_username_to_base_subscription: bool
    is_show_custom_remarks: bool
    happ_announce: str | None
    happ_routing: str | None
    expired_users_remarks: list[str]
    limited_users_remarks: list[str]
    disabled_users_remarks: list[str]
    custom_response_headers: dict[str, Any] | None
    randomize_hosts: bool
    response_rules: SubscriptionSettingsResponseRule | None
    created_at: datetime
    updated_at: datetime


@dataclass(frozen=True, slots=True)
class UpdateSubscriptionSettingsRequest:
    uuid: UUID
    profile_title: Omittable[str] = OMITTED
    support_link: Omittable[str] = OMITTED
    profile_update_interval: Omittable[int] = OMITTED
    is_profile_webpage_url_enabled: Omittable[bool] = OMITTED
    serve_json_at_base_subscription: Omittable[bool] = OMITTED
    add_username_to_base_subscription: Omittable[bool] = OMITTED
    is_show_custom_remarks: Omittable[bool] = OMITTED
    happ_announce: Omittable[str | None] = OMITTED
    happ_routing: Omittable[str | None] = OMITTED
    expired_users_remarks: Omittable[list[str]] = OMITTED
    limited_users_remarks: Omittable[list[str]] = OMITTED
    disabled_users_remarks: Omittable[list[str]] = OMITTED
    custom_response_headers: Omittable[dict[str, Any]] = OMITTED
    randomize_hosts: Omittable[bool] = OMITTED
    response_rules: Omittable[DebugSrrMatcherRequestResponseRule] = OMITTED
