# @generated by tools/codegen -- do not edit

from adaptix import Provider, name_mapping

from remnawave._generated.models import (
    ExternalSquadCustomRemark,
)

NAME_MAPPING: tuple[Provider, ...] = (
    name_mapping(
        ExternalSquadCustomRemark,
        map={
            "hwid_max_devices_exceeded": "HWIDMaxDevicesExceeded",
            "hwid_not_supported": "HWIDNotSupported",
        },
    ),
)
