# @generated by tools/codegen -- do not edit

from adaptix import Provider, name_mapping

from remnawave._generated.models import (
    ExternalSquadCustomRemark,
    TelegramCallbackRequest,
)

NAME_MAPPING: tuple[Provider, ...] = (
    name_mapping(
        TelegramCallbackRequest,
        map={
            "first_name": "first_name",
            "last_name": "last_name",
            "photo_url": "photo_url",
            "auth_date": "auth_date",
        },
    ),
    name_mapping(
        ExternalSquadCustomRemark,
        map={
            "hwid_max_devices_exceeded": "HWIDMaxDevicesExceeded",
            "hwid_not_supported": "HWIDNotSupported",
        },
    ),
)
