# @generated by tools/codegen -- do not edit
from typing import TypeAlias

# В этой версии API события вебхуков ещё не описаны. Карта пуста, поэтому
# WebhookReceiver.parse на любом теле сообщит о неизвестной области.
# Never здесь был бы точнее по смыслу, но тогда общий для всех версий
# parse перестаёт типизироваться: функция с возвратом Never не вправе
# выполнять return.
WebhookEvent: TypeAlias = object

BY_SCOPE: dict[str, type[WebhookEvent]] = {}
