# @generated by tools/codegen -- do not edit
from typing import TypeAlias

from remnawave._generated.models import (
    CrmEvent,
    ErrorsEvent,
    NodeEvent,
    ServiceEvent,
    UserEvent,
    UserHwidDevicesEvent,
)

WebhookEvent: TypeAlias = (
    CrmEvent
    | ErrorsEvent
    | NodeEvent
    | ServiceEvent
    | UserEvent
    | UserHwidDevicesEvent
)

BY_SCOPE: dict[str, type[WebhookEvent]] = {
    "crm": CrmEvent,
    "errors": ErrorsEvent,
    "node": NodeEvent,
    "service": ServiceEvent,
    "user": UserEvent,
    "user_hwid_devices": UserHwidDevicesEvent,
}
